### ISSUE TITLE
[Master Schedule] Improve Show Category Filtering

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#10]
**Is your feature request related to a problem? Please describe.**

Currently, you can filter shows by category, but the UI is simple and needs to be improved. Doing so would affect both the master calendar and the tabbed browsing.

**Describe the solution you'd like**

When filtering the master calendar, we should reduce the opacity of all shows that are not the selected Category on the master calendar.

We should reduce the opacity of all shows not in the selected Category in the tabbed browsing experience.

**Describe alternatives you've considered**

There are no specific alternatives.

**Additional context**

**Comment by majick777** [comment]
What kind of context are you meaning for the (genre) filtering to take place in?

**Comment by majick777** [comment]
Now that we have multiple Genre highlighting working, I'm not sure if this issue is still relevent?

**Comment by tonyzeoli** [comment]
Yep, you're right. Let's close this.
