### ISSUE TITLE
Add Shift Button Not Clickable

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#100]
**Describe the bug**
The Add Shift button is not clickable to add a new shift in the Show Scheduler

**To Reproduce**
1. Go to any Show Edit view.
2. Click Add Shift
3. Nothing happens

**Expected behavior**
Should be able to add shift.

**Screenshots**

**Comment by majick777** [comment]
Temporary glitch to switching to the use of `wp_add_inline_scripts` for admin... documentation insists that after WP 5, enqueueing a matching script handle is not necessary for the inline styles to be printed - and yet this is exactly what is not happening here. :-? So instead, just enqueueing a file for now with matching script handle anyway.

**Comment by tonyzeoli** [comment]
Ha! That's weird! Well, we'll just go that route then.
