### ISSUE TITLE
Add "View" to Show Post in admin bar

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#101]
**Is your feature request related to a problem? Please describe.**
Usually, when you are editing a post type of POST, there is a View Post in the admin menu bar. This is missing for the Post Type of Show.

**Describe the solution you'd like**
We need the user to be able to View Post on the front end from this link that is usually available.

It looks like there's supposed to be a "view_item" in the array.

https://developer.wordpress.org/reference/functions/get_post_type_labels/

**Describe alternatives you've considered**
N/A

**Additional context**
Screenshot.
![screenshot-radiostationdemo com-2019 12 27-16_00_39](https://user-images.githubusercontent.com/4053819/71533000-4f752600-28c4-11ea-9465-9bce7b21ec7a.png)

**Comment by majick777** [comment]
Easy one. Added for 2.3.0 for Shows, Playlists and Overrides. (Also supports Previews for Drafts.)
