### ISSUE TITLE
Remove Shift button not clickable

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#102]
**Describe the bug**
click on remove shift and nothing happens

**To Reproduce**
1. Go to a show post, then a Shift that's been generated
2. Click on "Remove Shift"
3. Nothing happens

**Expected behavior**
Remove Shift should remove the shift

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by majick777** [comment]
Duplicate cause as #100

**Comment by tonyzeoli** [comment]
Sounds good! I'll check.
