### ISSUE TITLE
Genres meta box is duplicated in the post admin sidebar

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#103]
**Is your developer task related to a problem or a requirement? Please describe.**
I noticed the Genres post meta box is duplicated in the Show post edit view sidebar.

**Describe the solution you'd like**
Please check.

**Describe alternatives you've considered**
N/A

**Additional context**

N/A

**Comment by majick777** [comment]
This was actually the from the Language taxonomy not being declared correctly. Somehow a variable that was there went missing and it was taking on the settings from the Genre taxonomy. Fixed now.

**Comment by tonyzeoli** [comment]
Awesome, thanks!
