### ISSUE TITLE
On remove then save, show entries reappear

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#104]
**Describe the bug**
When click remove, then update, the schedule entries reappear and are not deleted.

**To Reproduce**
1. Go to "Really Long Show Name to test bug"
2. Click on remove for both show schedule entries
3. Click Update
4. When screen refreshes, both entries reappear.

**Expected behavior**
Entries should be removed.

**Screenshots**

See video: https://www.loom.com/share/96ab2b86cddd4f758bd8ff7691e8add0

**Comment by majick777** [comment]
Good catch. There was no logic in place handling the case where all shifts were cleared, just updates and removals of shifts when there was still one remaining. Should be fine now, retest and close if satisfied.

**Comment by tonyzeoli** [comment]
This is fixed. Good work, Tony. Thanks!
