### ISSUE TITLE
Blog Post attached to Show does not display the Excerpt

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#105]
**Describe the bug**
I posted a blog post and assigned to Show 1. When check the Show 1 archive page, the Post thumbnail displays and the post title displays, but not the Post Excerpt.

**To Reproduce**
1. Go to Posts
2. Create a Post and add all elements, including an excerpt
3. Assign the Post to Show 1
4. Publish the Post
5. Check the front end view on the Show 1 archive page and the excerpt is not there

**Expected behavior**
Display the excerpt with "Read More" link.

**Screenshots**

<img width="391" alt="Screen Shot 2019-12-27 at 10 20 36 PM" src="https://user-images.githubusercontent.com/4053819/71538355-929cbc80-28f7-11ea-8e15-c3e2cc3a081e.png">

**Additional Information**
Maybe we can push this one to @trystant, as it should be an easy fix and he can get his feet wet.

**Comment by majick777** [comment]
Fixed, I had just commented out the excerpt output line when debugging an issue with excerpts elsewhere. Now seems to be working fine again.
