### ISSUE TITLE
[Show Conflict Checker] Admin notice  box appears and disappears randomly when resetting show times

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#109]
**Describe the bug**
When editing Show 4 (or any show for that matter), the conflict catcher box appears and disappears at random when you save changes to any Show time.

**To Reproduce**
1. Go to a Show Page and see if the Conflict Catcher box appears (if not, that's another bug)
2. If the Conflict Catcher box is apparent, it should show some conflicting times. Change the times from 3 am to 5 am to some other times later in the day.
3. Save
4. The conflict catcher box disappears, but there are still conflicts displaying that are disabled and the warning message is still there just above the show times that were added.

**Expected behavior**
The Conflict Catcher box is always apparent unless there are no conflicts. It should then say, you're Schedule has no conflicts.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Possibly fixed to due bugfix in conflict checker. A question is raised though from this, since the shift is disabled on saving, should the shift conflict checker show Disabled shifts? I'd say not... But now that shifts are disabled on saving, they should appear in the Show list as such?

**Comment by tonyzeoli** [comment]
I checked a Show admin and I don't see the Conflict Catcher meta box at the top with a "Your schedule contains no conflicts." message.

Should we do that or no?

No, I don't think it needs to show disabled shifts - you can see that when a shift is disabled and it's got the red dotted border around it, so that's fine.

Any disabled shift that has a conflict should not appear on the Show List on the Show page, because it's been disabled, so there should be no reason for it to appear until fixed.

**Comment by majick777** [comment]
I don't think we should show a message in admin when there are no conflicts. Admin notices should only show when there is information to display.

I think maybe we should consider further when to show the disables shifts in Show List view... or at least indicate in that view that a Show has disabled shifts? Since it is the main management interface list... otherwise they would be hard to find say if a conflict was fixed on another show, you want to re-enable the shift and can't remember what show it was disabled on.

**Comment by tonyzeoli** [comment]
If a show is disabled because of a conflict, then you'll see that in the conflict catcher and fix the show that was disabled. Is there a use case for leaving a show disabled? Sure, I guess having a warning in the List view would be helpful, but the problem with that is there are so many options to add to a list view in the View Options at the top of the screen. Someone could turn it off and hide it from the list view if they wanted. Or, when you have other plugins adding columns to the list view, it could get pushed out depending on the content from the other plugins.

What do you think in that regard?

Alternatively, could we just have a Settings panel page listing all disabled shows, so that the user can see a white number in a red circle for that panel and then click on it and see which shows are disabled?

**Comment by majick777** [comment]
Actually realized this is already how I have it, disabled shifts are highlighted in red on the Show List column but do not appear in the Conflict Checker. I think this is fine really and we needn't worry about it much further at this point.

**Comment by tonyzeoli** [comment]
Okay, cool! Sounds good.
