### ISSUE TITLE
Merge Tabbed Schedule Tutorial into Shortcode

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#11]
**Is your feature request related to a problem? Please describe.**

Currently, the tabbed schedule is something the user might attempt via a Tutorial specifying some custom development. Tabbed schedule should be included as a setting.

**Describe the solution you'd like**

Add a Settings Panel to the plugin under a new Settings > Radio Station link. In the Settings panel, prompt the user to select GRID or TABS for the output of the schedule in the shortcode.

**Describe alternatives you've considered**

No alternatives at this time.

**Additional context**

Find the code for tabbed schedule and implement as a feature in the plugin.

**Comment by majick777** [comment]
Are there any other main plugin options that need to be considered for adding to an admin page?

**Comment by tonyzeoli** [comment]
At this point, I believe giving the user the ability to toggle between the grid Calendar and Tabbed browsing would be more efficient than asking the user to follow the Tutorial the original developer supplied in the documentation. I don't have any specific features outside of this request at this time. I think it's important to roll this into a cohesive feature/option than leave it outside for a developer to implement. I can't think of anything else at this time to add to the admin page for the plugin.

**Comment by majick777** [comment]
I think I'll tackle this next... although, I don't think it actually needs to be a plugin admin setting. The way the schedule shortcode works is to take a display attribute from the shortcode... The tutorial then further styles the "list" type shortcode. Incorporating that tutorial, this can be merged into a new "tabs" schedule display type that is also available via the shortcode without affecting existing users who already have the "list" type one in place.

**Comment by majick777** [comment]
Decided it doesn't matter including this one in free version as tutorial already available to do this, I think there is sufficient features for pro version now without this. Instead we may want to consider adding a single shortcode that allows for instant switching between Table and Tab views.
