### ISSUE TITLE
Show Producer meta box selections do not stay highlighted but do display

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#111]
**Describe the bug**
When selecting the Show Producers, the meta box selection values do not stay highlighted, so you're not sure who you selected. But, they do display on the page.

**To Reproduce**
1. Go to Show 4
2. View the Producers Meta Box
3. Select 2 Producers
4. Save page
5. View the meta box and the Producers are not highlighted like the DJ/host metabox to the left
6. View the Show page and see that the Producers do display.

**Expected behavior**

**Screenshots**

<img width="521" alt="Screen Shot 2020-01-05 at 11 34 46 PM" src="https://user-images.githubusercontent.com/4053819/71795459-40088200-3014-11ea-937e-2406718ada84.png">

**Comment by majick777** [comment]
Fixed.
