### ISSUE TITLE
Language Type displays word "Language" and not the actual word for the language

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#112]
**Describe the bug**
When selecting a Language in the Show Edit view, the Language is selected but on the page itself the word is "Language" and not the actual work (e.g. Spanish) that should be there.

**To Reproduce**
1. Go to Show 4
2. Click on the language selector and select Spanish
3. Save the page
4. View the Show page and see the language says, "Language: Language"

**Expected behavior**
Should say, Language: Spanish

Also, should default to English

And, should not be linked.

Related to #113 

**Screenshots**

<img width="635" alt="Screen Shot 2020-01-05 at 11 38 18 PM" src="https://user-images.githubusercontent.com/4053819/71795585-e6548780-3014-11ea-97b1-20c5752a150d.png">

**Comment by majick777** [comment]
Fixed.
