### ISSUE TITLE
Open Show website link in new browser tab

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#115]
**Describe the bug**
The website link on the Show page opens in the same window taking the user offsite.

**To Reproduce**
1. Go to Show Edit view
2. Add link to show website
3. Go to Show Page
4. Click Link
5. Website opens in same tab

**Expected behavior**
Website should open in a new browser tab.

**Comment by majick777** [comment]
Added a `target=_blank` attribute to the Show link.

**Comment by tonyzeoli** [comment]
Great, thanks!
