### ISSUE TITLE
Player volume bar needs padding right

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#116]
**Describe the bug**
The audio player volume bar butts up against the right side of the player container. Needs a few pixels of padding.

**To Reproduce**
1. Go to Show 4 page
2. View Player volume bar
3. See the white volume bar extends to the side of its grey container.

**Expected behavior**
Should have a little space between the end of the bar and the right side of the container.

**Screenshots**

<img width="218" alt="Screen Shot 2020-01-06 at 12 05 22 AM" src="https://user-images.githubusercontent.com/4053819/71796382-48fb5280-3018-11ea-8e6c-f5583f5b23cc.png">

**Comment by majick777** [comment]
Ok done.
