### ISSUE TITLE
[Show Page] Fix spacing above and below content

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#121]
**Describe the bug**
The spacing of title and content needs to be adjusted. See attached screenshot. This needs to tightened up a bit.

**Expected behavior**
Show Info and Show Times headings need to start at the top of the column. Show description content too far from the Show Description heading.

**Screenshots**

![screenshot-radiostationdemo com-2020 01 06-08_25_51](https://user-images.githubusercontent.com/4053819/71820947-bf22a800-305e-11ea-9907-c786c9ed19f8.png)

**Comment by majick777** [comment]
Headings had changed from h3 to h4, so margin top style rule no longer matched. Fixed.

**Comment by tonyzeoli** [comment]
I'm still seeing a lot of whitespace above the titles and below the titles. I thought the titles like Show Info are supposed to be aligned at the top of the left vertical line and not somewhat down a bit.

<img width="722" alt="Screen Shot 2020-01-06 at 11 08 01 PM" src="https://user-images.githubusercontent.com/4053819/71867751-765c0500-30d9-11ea-8ed0-c27885c0a9a4.png">

**Comment by tonyzeoli** [comment]
Also, probably another issue, but the Show Times is being pushed below the show avatar. Is that supposed to be like that? I don't think so as I've seen it where it's aligned to the right of the Show Info section.

**Comment by majick777** [comment]
I missed uploading this fix to the demo site is all. 

As for the Show Times block being pushed there, the current setting is set to top blocks there, and the content area is quite narrow on this theme. The minimum block section width is set to 250px which I believe is optimal, so basically below 700px total available content width the blocks start collapsing like this so as to be responsive for mobile view where the total screen width is narrower.

As a user I would not use the "top" blocks setting with this theme (or in combination with the sidebar), or would add some styles to adjust the blocks to better suit the theme. While the layout should look similar on all themes, we are going by an average content width for all available themes, and it's difficult to say what that is. But I'd say 700px is about right, whereas at 100% zoom in chrome this is about 625px content width (plus the sidebar) which I think is a significant enough difference to say that in this case the combination of this theme and setting is just not suitable.

**Comment by tonyzeoli** [comment]
Okay, I'll change the setting so that it fits correctly. Thanks!

**Comment by tonyzeoli** [comment]
I changed the setting to right align and the columns stack below the show avatar.

**Comment by trystant** [comment]
I've been doing "local" development on this digital ocean instance [here](https://radio.grandkru.com).  While I have 2.2.9b of the plugin downloaded & working, I likely don't have enough of the station set up.  Once I set up the password for the demo site, I can go through that, compare it to mine & make adjustments.

**Comment by tonyzeoli** [comment]
@trystant okay, that URL could not be reached. You were already set up with access on your personal Gmail, so please try to login again or change your password on the radiostationdemo.com/wp-admin login screen.
