### ISSUE TITLE
Link Back to Schedule Page from Show Pages

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#122]
**Is your feature request related to a problem? Please describe.**
When viewing a Show Page and Show Times, there is no link back to the station's full Show Schedule.

**Describe the solution you'd like**
If we had a selector in the Settings screen to select the preferred Show Calendar page, selecting a page adds a link to the bottom of the Show Times column for: "View Full Schedule." This should be in smaller text at the bottom of the list of Show Times. Maybe there's a small Calendar icon to the left of text.

Since we don't auto generate a Calendar page like The Event Calendar does, it's best that the admin is able to choose from Pages that exist from a drop-down menu for what page they used the Shorcode on.

You can say something like:

**Show Schedule Page**
Selecting the page to which you included the Show Schedule shortcode. A link to this page will appear at the bottom of the Show Times column on the Show Page.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by majick777** [comment]
There is a setting already to select the Schedule page as described, so I changed the issue title to just adding that link on single show pages.

**Comment by majick777** [comment]
Added link back to Schedule page (if set in Settings) below single show time list.
