### ISSUE TITLE
Show More button on Show Description impacted

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#124]
**Describe the bug**
Can't see the full Show More button on the Show Description

**To Reproduce**
1. Go to Show 1
2. View Show More button
3. Can only see half of the button

**Expected behavior**
View the full button

**Screenshots**
<img width="655" alt="Screen Shot 2020-01-06 at 11 03 39 PM" src="https://user-images.githubusercontent.com/4053819/71867656-0c436000-30d9-11ea-9767-346c50bf972f.png">

**Desktop (please complete the following information):**
Mac OS 10.13.6
Chrome (latest)

**Comment by majick777** [comment]
Fixed. I also added some extra code to remove the fade overlay and buttons if it did not overflow (as the overlay and buttons were showing on short descriptions.)
