### ISSUE TITLE
Show 9 conflicts with Show 9 not on the same day and entries are not disabled

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#127]
**Describe the bug**
When login to view Show 9, I found that the two scheduled times are said to conflict, even though they are on Thursday and Friday from 11 pm to 1 am. And, the conflicting shows are not disabled nor do the have a red dotted line around them.

**To Reproduce**
1. Go to Show 9 Edit view
2. View the Conflict Catcher, which states Show 9 conflicts with Show 9
3. Scroll down to Time entries and check whereas there are two entries and one is for Thursday and the other for Friday, so they should not conflict.

**Expected behavior**
A show should not conflict if it's the same show on two different days.

**Screenshots**

No screenshot taken, please login and view.

**Comment by majick777** [comment]
For me it said Show 9 overnight shift conflicts Friday shift conflicted with Show 7 Saturday night shift... which was certainly not right in any case. 

This led me to find an incorrect data key in the conflict checker for overnight shift start times. With that fixed, it seemed to have cleared the incorrect conflict. So I'll close this particular issue, if there are other incorrect conflicts then can check/fix on a case by case basis.
