### ISSUE TITLE
Schedule Override Calendar picker needs z-index adjustment

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#128]
**Describe the bug**
I checked the Schedule Override function and clicked on the calendar and it falls behind the TinyMCE band/row.

**To Reproduce**
1. Go Shedule Override
2. Click on Calendar picker
3. View calendar picker is behind the tinymce buttons/row.

**Expected behavior**

Calendar picker should be avail over the tinymce bar.

**Screenshots**
<img width="935" alt="Screen Shot 2020-01-09 at 10 34 18 PM" src="https://user-images.githubusercontent.com/4053819/72123762-5d00c600-3330-11ea-8276-b422a96a35b5.png">

**Comment by majick777** [comment]
Fixed. I've added a targeted style rule so that the z-index for the datepicker is greater than the editor buttons which are set with a high z-index (1000)

**Comment by tonyzeoli** [comment]
Confirmed fix in Chrome for Mac.
