### ISSUE TITLE
[Master Schedule Table] Month/Day Under Day of Week, Year above Day of Week Centered

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#129]
**Is your feature request related to a problem? Please describe.**

I'd like to print the current month/day/ under the day of the week - like this: 12/2 so that the user knows what date the show falls on. Right now, they see the day of the week, but not the actual date.

I thought about adding 12/2/2020, but no room for the year unless we print it above the days and center it.

**Comment by tonyzeoli** [comment]
@trystant I've got this one issue assigned to you and I'm planning on getting 2.3.0 out next week. Can you let me know if you have the time to complete this task by mid-week and then I can test and add to the release next week? Thanks!

**Comment by majick777** [comment]
While adding in some more date-based calculations, I've added date and month as a subheading below the day on the Table view. I don't think year is really necessary yet, as at this point it will always be for the current week.

**Comment by tonyzeoli** [comment]
SO COOL! Great stuff, my man! Looks awesome.
