### ISSUE TITLE
Date & time not saved in Schedule Override

### ISSUE THREAD

**Issue by montereyjeff** [netmix/radio-station#13]
**Describe the bug**
After entering a Schedule Override, the date and time blank out after clicking Publish. They also blank out when trying to Update.

**To Reproduce**
1. Add a Schedule Override that includes a date and time
2. Click Publish
3. Observe that the Date and Time are now blank

**Expected behavior**
Date and time should be retained for a schedule override.

**Comment by tonyzeoli** [comment]
Thank you for submitting this issue. We'll be looking at this asap and will keep this issue ticket updated.

**Comment by majick777** [comment]
Have fixed the issue with metabox data sanitization and is saving properly now for next release.
