### ISSUE TITLE
Add Widget for Radio Times caused fatal error

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#131]
**Describe the bug**

I added the Radio Times widget and it caused a fatal error on the master calendar view.

**To Reproduce**
1. Move Radio Times widget to the top of the main sidebar under Widgets
1. Go to master calendar page
2. See fatal error message

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
This widget is in still development and will be moved to a feature branch shortly, so the error is because there is nothing there yet but a class wrapper with not much in it... So I'll close this here as it will become part of the overall Clock features.

**Comment by tonyzeoli** [comment]
Okay, I'll make sure to not test it again so as not to disrupt. Once it's move to a feature branch, it'll be out of the way and not available.

**Comment by majick777** [comment]
I've created the feature branch and the issue for this widget and clock display in general is now #126.
