### ISSUE TITLE
[Master Schedule] Table View - Improve display for mobile devices

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#132]
**Describe the bug**

The master calendar grid view squeezes in portrait mode for mobile devices. Is fine in landscape. The right edge of the calendar also squeezes right up to the right border.

**To Reproduce**
1. Go to the demo site and view the master calendar in a mobile device in portrait mode
2. See how all days are squeezed and cannot read the content well in each showtime box.

**Expected behavior**

We discussed having a left/right arrow in the portrait mobile view to shift the days of the week in the mobile view, so that only one or two columns are present to the viewer and they can shift left or right to see other days.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: latest
 - Browser: Chrome for iPhone
- Version: latest

**Additional context**

**Comment by majick777** [comment]
Had a good go at this with some javascript width responsiveness on pageload and resize, a little bit mindbending to calculate which columns to display but seems to be working well! Check it out. :-)

Never thought to handle responsive table columns like this, very cool idea thanks! Definitely something I will consider implementing in other projects in the future.
