### ISSUE TITLE
Conflict Catcher Issues

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#134]
**Describe the bug**

When checking the Show List View, I found that there are conflicts that display in the List View, but do not trigger the Conflict Catcher or trigger red border around the conflicts when editing the Show Edit view.

**To Reproduce**
1. Go to Shows List View
2. View Shows 8 and 12 have conflicts
3. Note conflict catcher does not display
4. Edit one of the Shows and not conflicts red dashed border is not around the affected times and the affected times are not disabled.

**Expected behavior**

The Conflict Catcher should be at the top of the screen in the List View.
The conflicts should be apparent in the Show Edit view with red dashed border and disabled.

**Screenshots**

<img width="1544" alt="Screen Shot 2020-01-12 at 9 22 19 PM" src="https://user-images.githubusercontent.com/4053819/72230301-700ad480-3582-11ea-9f15-1af74cb9cd2d.png">

**Desktop (please complete the following information):**
 - OS: 10.13.6
 - Browser: Chrome
 - Version: 79.0.3945.88 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Show 12 is inactive. Show 8 shift is disabled. 
So these are not going to show in the Conflict Checker.
This is the intended behaviour as discussed in #109

**Comment by majick777** [comment]
One thing though, with Show 12 inactive... the shifts still all have the green boxes around them... So I will change those to reflect the state of the Show.

**Comment by tonyzeoli** [comment]
Okay, thanks. I wasn’t sure because the list view showed the read dotted lines. I’ll check the fix. Thanks!
