### ISSUE TITLE
[Maser Schedule] Tabbed View - Left align Genres Under Show Title

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#135]
**Describe the bug**

In the Tabbed View in mobile, if the Show Title is really long or the Genres have multiple, this causes an issue where you have to swipe left to see the content that extends the screen well past the mobile view.

**To Reproduce**
1. On a mobile phone, pull up the Tabbed calendar view
2. View the way the Genres are way out to the right
3. Swipe left to view the Genres

**Expected behavior**

Here's another instance where having these two columns makes things a bit messy. Let's left align the Genres under the Show Title and ensure that the user does not have to swipe left to see the Genres out to the right. There's no business reason for the Genres to be out there on the right anyway other than aesthetics. Let's simplify and make it:

Show Title
Genres
Show Times

**Screenshots**

You can see this by simply viewing on the phone.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS:
 - Browser Chrome
 - Version 

**Additional context**

**Comment by majick777** [comment]
Fixed.

**Comment by tonyzeoli** [comment]
Confirmed. Thanks.
