### ISSUE TITLE
[Playlist Widget] HTML Format Breaking Layout

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#136]
**Describe the bug**

The Playlist widget settings has a text field and not a check box for Show Title.

I created a playlist, assigned it to show 7 and scheduled a show from 9 pm to 11 pm EST on Sunday night for testing purposes to test the widget while I was online. The playlist widget does not display the last song played.

**To Reproduce**
1. Go to Playlists and check the Show 7 playlist
2. Add an available shift from an empty time slot that matches the time you are testing
3. View the widget in the sidebar
4. No playlist available

**Expected behavior**

I believe the playlist is supposed to show the last song played if the playlist is matched to a show and that show is currently on the air.

**Screenshots**

<img width="363" alt="Screen Shot 2020-01-12 at 10 31 20 PM" src="https://user-images.githubusercontent.com/4053819/72231877-c2042800-358b-11ea-8f21-61c73536bcc4.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tonyzeoli** [comment]
Now that the Playlist is printing to the page, for some reason it disrupts the sidebar and pushes everything into the footer from that widget and all widgets below.

<img width="1552" alt="Screen Shot 2020-01-13 at 12 50 36 PM" src="https://user-images.githubusercontent.com/4053819/72279067-5493de00-3603-11ea-845c-2c5db2508b94.png">

**Comment by majick777** [comment]
There was a rogue `echo` statement of a `</div>` tag in the playlist shortcode which was breaking the HTML structure. This is fixed now.

**Comment by tonyzeoli** [comment]
Okay cool, thanks for fixing.
