### ISSUE TITLE
[Current Show Widget] Missing Display of No Show Scheduled Message

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#138]
**Describe the bug**

@trystant Here's one for you. @majick777 passing along to Mark.

If there is no show on air at the current time, the Show/DJ OnAir widget does not indicate anything. There is no notification.

**To Reproduce**
1. Go to radiostationdemo.com sidebar and view Show/DJ On-Air widget when there is no show scheduled on the calendar.
2. View empty space.

**Expected behavior**

We should have a message in the widget that states: "No show scheduled at this time. Please check back later."

**Screenshots**

<img width="303" alt="Screen Shot 2020-01-13 at 2 12 49 PM" src="https://user-images.githubusercontent.com/4053819/72284370-d3424880-360e-11ea-9e96-9914b42f8819.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
There is a field in the widget options for this text. It was empty (and defaulted to empty.) I have set the default text to be "No Show scheduled for this time."

**Comment by tonyzeoli** [comment]
Ah! I didn’t know that you could set the message. I’ll need to check the widget interface next time. Sorry!
