### ISSUE TITLE
[Master Schedule] List View needs Genres below Show Title

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#139]
**Describe the bug**

There are no Genres present in the List View

**To Reproduce**
1. https://radiostationdemo.com/master-schedule/list-view/
2. View Shows
3. No Genres listed

**Expected behavior**

We need to add a line for Genres under the Title but above the Show Time. Adding another bug under separate ticket for the filter action on Genres in the list view.

**Screenshots**

<img width="1552" alt="Screen Shot 2020-01-14 at 11 38 06 AM" src="https://user-images.githubusercontent.com/4053819/72363170-5ec8e180-36c2-11ea-8b41-f6a11f9d1a69.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Whoops, that commit did not include this fix yet as was intended, was trying to do all those ones together as they all related master schedule view enhancements.

**Comment by majick777** [comment]
Added this now, along with some other Schedule display fixes.
