### ISSUE TITLE
[Master Schedule] Filter Genres in List View

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#140]
**Describe the bug**

The user cannot filter genres in the List View

**To Reproduce**
1. Go to List View
2. Click on a genre
3. There are no genres to filter in the list.

**Expected behavior**

The user should be able to filter genres in the list - maybe it's a background color for the row(s) or some designation that we come up with.

Also related to #139 

**Screenshots**

<img width="1552" alt="Screen Shot 2020-01-14 at 11 38 06 AM" src="https://user-images.githubusercontent.com/4053819/72363419-d139c180-36c2-11ea-9799-03d9b59ba34b.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Fixed.

**Comment by tonyzeoli** [comment]
Confirmed. Thanks!
