### ISSUE TITLE
[Admin Notices] Upgrade Notice not dismissing

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#141]
**Describe the bug**

Andrew reports the upgrade notice does not click on his import/export view and was wondering if there was some type of conditional on specific pages to close or is it just not working properly overall.

**To Reproduce**
1. Go to admin
2. Click on X to close upgrade notice

**Expected behavior**

Close on Click

**Screenshots**

<img width="644" alt="Screen Shot 2020-01-14 at 3 13 29 PM" src="https://user-images.githubusercontent.com/4053819/72378983-79aa4e80-36e0-11ea-8830-2cdac0642367.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
`%20` in a querystring is whitespace and should not be there before the `?` in the AJAX URL.
So I've fixed that typo and that should fix the problem. The notice dismissal has been testing when I wrote it but at some point in code cleanup this has been introduced. I will retest it before closing.

**Comment by tonyzeoli** [comment]
@voyager131 please pull the fix and check thanks

**Comment by voyager131** [comment]
I can confirm dismiss works now with the latest code form branch **develop**

**Comment by tonyzeoli** [comment]
Thanks, @voyager131 !
