### ISSUE TITLE
Store 24hr time in database and associate where currently applied

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#144]
**Is your developer task related to a problem or a requirement? Please describe.**

@voyager131 recommends storing 24h time in the database, as he needs that time stored as a 24hr value for the import / export feature he is working on.

**Describe the solution you'd like**

We may have to replace where time is needed across the site.

@majick777 and @voyager131 will work together to identify and replace current time functions to adopt the new method needed by Andrew to set time on a 24hr clock and store that time in the DB.

A station can then select display of time as 12 hr or 24 hr in the Settings panel, as Show Times, Playlist times, or Widget times.

Write filter to convert 24h to am/pm and insert that whenever am/pm is called for

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by majick777** [comment]
As discussed, the existing data structure is stored in 12 hour time and schedule calculations are based on this. It would be too much work for no substantial benefit to change this when the conversion between these two time formats is an easy one.

**Comment by tonyzeoli** [comment]
Got it! Good call!
