### ISSUE TITLE
Style Legacy Widgets

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#146]
**Describe the bug**

@majick777 mentioned needing to style legacy widgets - so opening a ticket here for this task.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Duplicate of #86 and #153, which have more specifics, so closing this one out.
