### ISSUE TITLE
Automattic Pages Issue

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#147]
**Describe the bug**

When go to the Show Archive or Playlist Archive pages on the demo site, the page(s) return errors.

**To Reproduce**
1. Go to https://radiostationdemo.com/automatic-pages/shows-archive-page/ or https://radiostationdemo.com/automatic-pages/playlists-archive-page/
2. See error

**Expected behavior**

Should be able to see pages.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Fixed. Since the new internal excerpting function applies `the_content` filters, this was causing an endless loop because the automatic pages are also triggered via the same filter. Removing this filter when an automatic page is triggered now prevents this from happening.
