### ISSUE TITLE
Replace MailChimp form with ConvertKit form in plugin notice

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#148]
**Is your developer task related to a problem or a requirement? Please describe.**

I'm switching from MailChimp to ConvertKit.

**Describe the solution you'd like**

Here is the javascript for convert kit:

<script async data-uid="9f9332b7bc" src="https://expert-artist-2760.ck.page/9f9332b7bc/index.js"></script>

**Describe alternatives you've considered**

N/A

**Additional context**

ConvertKit has a better system for driving leads into a landing page, which is going to be necessary when we market PRO.

**Comment by majick777** [comment]
An alternative approach here might be to have a generic form that takes the user to a Netmix website page where the actual form is embedded (and use the posted data to populate the form.) Having different form codes in the plugin itself means if a user hasn't updated the plugin and tries to use an old form (eg. Mailchimp form code) then they won't get added to the list. But this way whatever form code is on the site can be updated without this happening.

I'd also recommend whatever we do here, that once the new form is released in the next plugin update, and the existing subscribers transferred to ConvertKit, that the existing MailChimp account be left active for at least a month so as to catch any subscribers from old plugin versions (ie. who haven't updated yet.)

**Comment by tonyzeoli** [comment]
Let's hold on this for now. Yes, agreed about the old form - it'll always be active, so it'll still ingest subscribers. I don't want to remove it from the plugin and force a click - it'll still cause the same issue and we're getting subs now that may not have subbed if they had to click. Convert Kit is free for under 100 subs, but after that, it's $29 a month. My wife is pushing on me to migrate, but there's not specific reason to at the moment and we're over the 100 now anyway. MailChimp is up to 2,000 subs, but it's by email volume, so if you have 500 subs, you can send 4 emails a month. 1000 subs, then two emails a month. ConvertKit will give you 100 more subs if someone signs up with your affiliate link, so I'm trying to get 4 or 5 people to sign up so I can grow the account to 500.

**Comment by tonyzeoli** [comment]
I'm leaving this open for now and not related to a milestone. We may need this in the future, but not sure yet.

**Comment by majick777** [comment]
I'll close this old issue as sounds like we are staying with Mailchimp.
