### ISSUE TITLE
Help page is blank

### ISSUE THREAD

**Issue by montereyjeff** [netmix/radio-station#15]
**Describe the bug**
On the dashboard, clicking Radio Station, Help shows a blank result in 2.2.1.

**Comment by tonyzeoli** [comment]
Thank you. I've seen this and am planning to fix in the next release.

**Comment by majick777** [comment]
Thanks @montereyjeff looks like there were some issues uploading to the SVN and the help template file went missing, will be fixed in the next release upload.
