### ISSUE TITLE
Playlist / Now Playing Widget Show Title text field should be checkbox

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#152]
**Describe the bug**
In the Playlist widget, the Show Title is a text field and not a checkbox.

**To Reproduce**
1. Go to Now Playing widget
2. Open Widget
3. View first row for Show Title
4. See text field

**Expected behavior**

Should be a checkbox.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Fixed. Was set to checkbox, but missing a double quote to close the name attribute, causing the input type to be ignored and set to default (text).

**Comment by tonyzeoli** [comment]
Confirmed fix.
