### ISSUE TITLE
[Show Widget] Current Show Widget Changes

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#153]
**Is your feature request related to a problem? Please describe.**

List of changes to Current Show widget for 2.3.0 launch.

**Describe the solution you'd like**

- Move Remaining Time from below the Show Times to below the Show Excerpt
- Add "Remaining Time:" subtitle and move the time to a line below, on its own line
- Add subtitle "Show Times:" above list of Show Times in the widget
- Add spacing between DJ name and excerpt
- Add "About This Show:" subheader over excerpt
- Check spacing above Playlist link once you move the Remaining Time: 00:00:00 below the excerpt.

**Describe alternatives you've considered**

N/A

**Additional context**

See current widget screenshot attached.

<img width="321" alt="Screen Shot 2020-03-02 at 12 32 07 PM" src="https://user-images.githubusercontent.com/4053819/75701929-9bf12f00-5c82-11ea-9cb9-d3d88460cc03.png">

**Comment by majick777** [comment]
Okay, I've made those requested changes so far, with a few caveats...
- I've moved View Playlist link to below Host display.
- I didn't add the About the Show subheading, as I think that one is unnecessary.

**Comment by majick777** [comment]
@tonyzeoli Can you confirm any final changes that may be needed here (and for any of the other widgets) as this is the last major remaining open ticket for 2.3.0! :-O

**Comment by majick777** [comment]
Some minor changes:
- Added a link to the Show description read more hellip [...]
- Separate earlier display for the current show shift
- Indicated the current show shift in full schedule with disc
https://radiostationdemo.com/widgets/

Reopen if there is anything further...
