### ISSUE TITLE
[Show Edit] Remove conflict statement when remove time entry

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#154]
**Describe the bug**

When in the Show page admin, if there is a conflict on a show time, if remove the entry, the conflict stays present. Should also remove if the conflicted entry is removed.

**To Reproduce**
1. Go to any show admin page that has a conflict (or create a conflict)
2. View the entry and see the conflict text below.
3. Remove the entry.
4. Conflict text perists and does not go away, even though the entry was removed.

**Expected behavior**

If I have a conflict show time and I remove the show time, then the conflict text should remove, as well.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Okay got it, the shift conflict for the shift is now removed with the shift.

**Comment by tonyzeoli** [comment]
Cool! Thanks for taking care of that.
