### ISSUE TITLE
[Show Widgets] Check 24-hour widget show time entries

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#158]
**Describe the bug**

Shows 8 pm to 8200 pm.

**To Reproduce**
1. Go to Widget page on radio station demo site
2. Check the Current Show widgets
3. Check the 24 hour widget
4. Show 8 (if scheduled at the time you check) displays 8 am - 8200 pm

**Expected behavior**

Should display the later time in 24-hour time

**Screenshots**

<img width="321" alt="Screen Shot 2020-03-02 at 1 10 13 PM" src="https://user-images.githubusercontent.com/4053819/75704582-9cd88f80-5c87-11ea-8b2c-bbc51774bb2e.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
This one is fixed now. The code was using a legacy function for the 24 hour conversions.
