### ISSUE TITLE
Day of Week heading missing in schedule grid view

### ISSUE THREAD

**Issue by montereyjeff** [netmix/radio-station#16]
**Describe the bug**
In version 2.2.1 the Day of the Week heading (Monday, Tuesday, Wednesday, etc.) is missing in the schedule grid view.

**Screenshots**
Example: https://kspb.org/wordpress/schedule/

**Comment by majick777** [comment]
@montereyjeff good pickup didn't notice that one, typo in the weekday variable for translation, fixed for next release.
