### ISSUE TITLE
Conflict Catcher Show List and Disable Show Issues

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#160]
**Describe the bug**

In order to take a screenshot of the Show List view of a Conflict Catcher result, I added an entry for Show 4 from 12 am to 1 am on Monday. I noted that that conflict displays as an admin notification, but:

- does not display in the show list
- does not display around the time entry
- does not disable

**To Reproduce**
1. Go to Show 4 Edit View
2. Check Monday time entry from 12 to 1 am
3. This conflicts with Show 1 according to the admin notification
4. Show List outline does not display, Show conflict for time entry does not display, and Show is not disabled due to the conflict.

**Expected behavior**

- Should display conflict up on the Show List
- Should display a warning around the time entry
- Should disable itself since it's in conflict with another show

**Screenshots**

<img width="1544" alt="Screen Shot 2020-03-05 at 1 19 11 PM" src="https://user-images.githubusercontent.com/4053819/76012491-5f247280-5ee4-11ea-8775-bb833e3dfb71.png">

<img width="1235" alt="Screen Shot 2020-03-05 at 1 22 58 PM" src="https://user-images.githubusercontent.com/4053819/76012543-76636000-5ee4-11ea-9e8a-bca4f862c7ef.png">

<img width="932" alt="Screen Shot 2020-03-05 at 1 29 41 PM" src="https://user-images.githubusercontent.com/4053819/76013212-91829f80-5ee5-11ea-9230-25a6100244a7.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tonyzeoli** [comment]
@majick777 Looks like this is fixed. Tested tonight and see that all is back in place. You haven't closed this, so I'm making an assumption it's still being worked on.

**Comment by majick777** [comment]
Issue is fixed now, just needed to retested the shift disabling before closing.

**Comment by tonyzeoli** [comment]
cool! great work!
