### ISSUE TITLE
[Docs] Add screenshots to readmes

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#164]
**Is your developer task related to a problem or a requirement? Please describe.**

We should have screenshots in the WordPress.org page. If we can add those to the read.md file, that would be great.

**Describe the solution you'd like**

Display screenshots in the WordPress plugin page.

**Describe alternatives you've considered**

**Additional context**

**Comment by majick777** [comment]
I currently have these Screenshots (saved from the pre-release post):

1. Weekly Schedule View
2. Show Page Layout
3. Admin Settings Panel
4. Show Conflict Display

It should be noted these correspond to WordPress SVN /assets/screenshot-x.png files.
Also that changes to WordPress SVN assets can be updated separately to the release (and the plugin readme.txt can also be changed on the repository without a new release.)

**Comment by majick777** [comment]
This was done just before 2.3.0 release. For reference the screenshots for this release are:

1. Table Schedule View
2. Tabbed Schedule View
3. Show Page Layout
4. Playlist Page Layout
5. Current Show Widget
6. Show Archive List Shortcode
7. Admin Settings Panel
8. Show Conflict Display
