### ISSUE TITLE
[Shortcodes] Make End of Time Display Enable or Disable

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#166]
**Is your feature request related to a problem? Please describe.**

Is it possible to either add the ability to remove the end time from each show or make it option? I know this can be achieved by editing the master-schedule-tabs.php however it would be nice to have this as a setting

**Describe the solution you'd like**

In the admin, add feature to allow user to enable or disable End of Time function.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by majick777** [comment]
I don't think there needs to be an option for something minor like this as it's more a diplay thing.
It can be simply hidden with some CSS. 

I've added an extra span class to the existing one to help with that targeting so it can be removed sitewide by:

`.rs-end-time, .rs-sep {display: none;}`

Or for a particular context, as for example for list view: 

`#master-schedule-tabs .rs-end-time, #master-schedule-tabs rs-sep {display: none;}`
