### ISSUE TITLE
[Table Schedule] Add attribute to set day starting hour / hide hour rows

### ISSUE THREAD

**Issue by PAOK1926** [netmix/radio-station#179]
hello again,

another feature would be to set the starting hour of the program at master-schedule shortcode.
Day starts at 6,7,8 am usually.. :)

**Comment by majick777** [comment]
Thanks for the suggestion. I have actually considered doing this in the past, but it hasn't been the right time to do it, given this is actually a way more complex change than it might seem. So we probably won't prioritize this particular possibility just yet, but we'll see how we go.

**Comment by tonyzeoli** [comment]
@PAOK1926 I'm doing some cleanup work here in Git and came across this ticket. I'm trying to understand this a little better. Are you saying that you want the Schedule display to start not at 12 midnight, but at - say - 7 am? So, if you only have shows scheduled between 7 am and 12 midnight that all seven days only display from 7 am to 12 midnight and leave off anything after midnight to 6:59 am?

@majick777 So, what he's suggesting is to hide a row that has no entries for a time slot. Should this just be a shortcode feature or a full feature? If the rule is hiding a row for any timeslot with no entries, then that might hide, for example, 12 midnight to 7 am and if there are no shows from 6 pm to 7 pm, then that time slot would be hidden too.

I also feel as if this should be a PRO feature, given that it's probably a rare request and anyone who wants something this time intensive should understand it takes a fair amount of time to develop and support. I'm going to tag this as PRO.

**Comment by majick777** [comment]
This came up again in another ticket, and the resolution was to simply add CSS to hide the desired timeslot rows in the table. (As this only applies to table view with empty rows.) I think this is still a viable solution and the best thing to do if a particular station doesn't want to display those empty hour rows. 
Maximally we could add a shortcode attribute that would add these styles (so they wouldn't have to be added to a stylesheet... I don't see this is a priority issue but we could easily do that.

**Comment by tonyzeoli** [comment]
@majick777 Seems that we should close this issue for now.
