### ISSUE TITLE
A DJ is replicated multiple times in Show Edit View sidebar module

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#18]
**Describe the bug**

The DJ user is replicated in the selection module in the Show Edit View

**To Reproduce**
1. Go to Dashboard > Shows
2. Click on Show to Edit
3. View list of DJs
4. If you're a DJ, you'll see yourself replicated multiple times

**Expected behavior**

All DJs are supposed to be listed. Nourma and I have DJ profiles. My profile name is "tonyzeoli."

**Screenshots**

<img width="1548" alt="radio-station-dj-replicated-multiple-times" src="https://user-images.githubusercontent.com/4053819/61835863-9d848a00-ae4b-11e9-9cfe-c0401524a341.png">

**Comment by majick777** [comment]
This is an issue with the display labels, they have the different DJ IDs are selectable just displaying the same label for all of them. My bad on this one as I placed modified option label code (to include username) outside the user option loop. Fixed for next release.
