### ISSUE TITLE
table view

### ISSUE THREAD

**Issue by herr-der-mails** [netmix/radio-station#182]
Hello 
i'll like this great plugin but i have one think that i dont like at the moment,
thats the table view, the radtio station i work on, is only 12hours on air, so i dont need the full table, is there any way to reduce the table to the hours we ware on air?

**Comment by tonyzeoli** [comment]
Hi, I'm sorry. We want to answer your question, but this is not our support forum. This is for bugs and feature requests.

Please post your issue here: [](https://wordpress.org/support/plugin/radio-station/) and we'll get to it as soon as we can.
