### ISSUE TITLE
[Schedule Table/Tabs] Javascript for Arrows

### ISSUE THREAD

**Issue by herr-der-mails** [netmix/radio-station#185]
`<a href="javacript:void(0);" onclick="radio_shift_tab('left');" title="Previous Day">◄</a>`
occur an error at firefox (the right button event the same)
the event url dosnt reload the page

the script say reload /https://myurl.de
i think is because of the adiditonal slash at the event. this is only at firefox.
i have search for the line at wordpress plugin editor, but i could not find the php file where the javascript code is.

i hope somone els can help fix this.

regards

**Comment by majick777** [comment]
@herr-der-mails Thanks for pointing that out, yes it seems like Firefox is ignoring `javascript:void(0);` and so I have added to the arrow functions a return false to prevent the default click action triggering the change in window location.

I have added this to 2.3.1 and also pushed to the fix to the develop branch.

**Comment by XLRradio** [comment]
This weren't just firefox issue, Microsoft Edge had a problem with the Arrows and javascript message too

**Comment by XLRradio** [comment]
@majick777

**Comment by majick777** [comment]
Thanks for confirming. Adding the return false to the javascript function is a common practice fix to prevent the default click so should work for all browsers, even very old versions.
