### ISSUE TITLE
[Schedule] Not Displaying Some Shows

### ISSUE THREAD

**Issue by agrady10** [netmix/radio-station#189]
Any shows ending at the bottom of the hour are not displayed to that amount of time on the schedule.  If a show begins at the bottom of the hour just after another show ends, the second show is not indicated at all but the previous show extends to the following show's end time.

**Comment by majick777** [comment]
@agrady10 I'm trying to reproduce this. Can you provide some more exact shift times that this is happening with? And maybe clarify what is meant by "the bottom of the hour"?

As you can see on the demo site, there are plenty of shows that have a start time equal to the previous show's end time and they display fine, so I'm going to need some more nformation.
https://radiostationdemo.com/master-schedule/table-view/

**Comment by agrady10** [comment]
The show times are 8:30 - 10:30 with the next show beginning at 10:30 -2:00. 
Same issue occurs with a show ending at the 30 min mark (bottom of the hour)  with two different shows. 
For reference, https://thebluegrassjamboree.com/schedule
Both are on Saturday; first occurrence in the morning, second in the evening. 





Annette Grady, Owner/Host

The Bluegrass Jamboree           

(919) 920-3405                                    

www.thebluegrassjamboree.com





---- On Sun, 19 Apr 2020 03:47:00 -0400 notifications@github.com wrote ----



@agrady10 I'm trying to reproduce this. Can you provide some more exact shift times that this is happening with? And maybe clarify what is meant by "the bottom of the hour"?

As you can see on the demo site, there are plenty of shows that have a start time equal to the previous show's end time and they display fine, so I'm going to need some more nformation.
https://radiostationdemo.com/master-schedule/table-view/

**Comment by majick777** [comment]
@agrady10 Thanks for the added information.

Confirmed. Added a fix to reset the showcontinued flag that was causing second show shifts in a cell to not display empty. Added to develop branch for release in 2.3.1
