### ISSUE TITLE
[Plugin Conflict] Possible conflict with Yoast SEO plugin

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#190]
**Describe the bug**
Reported here by @gusaus: https://github.com/OpenProducer/openproducer-platform/issues/9
"I verified again that Yoast is the cause of the show pages not displaying properly. So it's currently disabled."

**To Reproduce**
Install Yoast SEO with Radio Station and check show pages.

**Additional context**
First noted in conjunction with Newspack, so unlikely but possible conflict is related to thae combination of the 3.

**Comment by tonyzeoli** [comment]
@majick777 I can confirm Yoast breaks Radio Station Show page. When activated, the left sidebar goes away on a Show page.

**Comment by majick777** [comment]
Confirmed. Due to Yoast calling `the_content` filter multiple times (by using `the_excerpt` to generate Twitter and Opengraph data) and Radio Station removing it's content filters after use  then the content changes are lost on the second time filtering. And a similar thing was happening to all Automatic Pages (blank.)

https://github.com/Yoast/wordpress-seo/issues/5956

It's not really optimal for Yoast to be doing this on every single pageload though, it could be something that is generated and stored when the post is being published/updated.

The reason for this filter removal in Radio Station was in place was so that excerpt generated within the post content did not create an endless loop. So the solution was to re-add these filters after the content has been generating (including excerpts.) Added fix to develop for 2.3.1 release.

**Comment by tonyzeoli** [comment]
@majick777 Thanks!!!!!! Good work.
