### ISSUE TITLE
[Widgets] Dynamic Reload Feature

### ISSUE THREAD

**Issue by XLRradio** [netmix/radio-station#195]
Hi all, 
 @majick777 
Just a question. Has auto update of widgets been included in this plugin yet? as on the old version it didn't include it and had to get a plugin to do it.
Thank You

**Comment by majick777** [comment]
Are you referring to widgets reloading themselves when the show finished / new one starts?
Or do you mean something else by "auto updates"?

**Comment by XLRradio** [comment]
like a auto refresher.

**Comment by majick777** [comment]
Yes, we have started work on this feature already and it will be part of the Pro version.

**Comment by majick777** [comment]
@XLRRadio Do you have the name of the plugin you used in the end? While we have this feature in the Pro version now, another user is lookin to implement this also.

**Comment by XLRradio** [comment]
Hey, the wp plugin used is "wp Auto Reload Widget"

**Comment by majick777** [comment]
@XLRradio Thanks for that I'll pass it on. :-)

**Comment by DSFM93** [comment]
Hi @XLRradio, would you happen to be using that auto reload widget for the 'Current Show On Air' or 'Upcoming Shows' widgets? Can't get it to work for either of those.

**Comment by XLRradio** [comment]
> Hi @XLRradio, would you happen to be using that auto reload widget for the 'Current Show On Air' or 'Upcoming Shows' widgets? Can't get it to work for either of those.

Hello

![image](https://user-images.githubusercontent.com/63446711/130609845-87cef3fe-4237-4de0-b85d-1719dcdd7937.png)

In the  plugin settings as you can see above it needs the title and ID of the widget you want to auto reload

Under appearance > widgets you need the widget id filled in and matching in the reload widgets plugin

![image](https://user-images.githubusercontent.com/63446711/130610191-2db3bdcf-ce11-47d6-beac-05f7b0d81b07.png)

Then that should work

hope this helps

**Comment by DSFM93** [comment]
Mine is pretty similar to that! (ID's & Titles aside).

Could there be an issue with what widget area I used? I made a custom one specifically for those widgets.
![Auto Reload](https://user-images.githubusercontent.com/89457267/130621937-b3dfaddb-c734-40a5-8dd9-70fc303e3269.PNG)
![Upcoming Shows](https://user-images.githubusercontent.com/89457267/130621942-4c2e8133-43bb-4764-9a2a-db99e9e03a3e.PNG)
![Show Info](https://user-images.githubusercontent.com/89457267/130621944-6b5ebae0-b76b-42a0-8d89-f0a2e3283f0b.PNG)

**Comment by XLRradio** [comment]
@DSFM93 the only difference i see, is where u got the box to AJAX load is currently set to default we have that set to OFF

and we only have the widgets put in the main sidebar so nowhere special

**Comment by DSFM93** [comment]
Figured out the issue. I'm using Elementor so those two widgets weren't linked to any of the widget areas that came with the theme! Still relatively new to WordPress so I just assumed those widget setting would work anytime that widget showed up on the page. Thanks for the help @XLRradio @majick777
