### ISSUE TITLE
[Options] Add Station Logo URL and Tagline Fields

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#199]
Add a plugin option for setting a Station Logo URL, and a Station Tagline field, which can be added to the Data API output for display.

**Comment by tonyzeoli** [comment]
Moving this to 2.3.3.

**Comment by majick777** [comment]
@tonyzeoli Station Logo and Station Title fields have been added to the develop version for 2.3.3.8 release... 
Not sure we really need an extra "tagline" field as per this issue, but it would be easy enough to add if we want one.

**Comment by tonyzeoli** [comment]
Got it, thank!
