### ISSUE TITLE
Add support for Rest API

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#2]
Developers should be able to pull information via Rest API.

**Comment by majick777** [comment]
Had a go at this and got some REST endpoints working, but will need a bit more to get the data in a format for outputting. Decided I will probably leave this for 2.3.1 so it doesn't hold up 2.3.0 release.

**Comment by tonyzeoli** [comment]
Very cool!

**Comment by majick777** [comment]
All seem to be working well, all routes output in JSON data format for consumption of API by HTTP requests and AJAX. Added a plugin option to disable them too. Decided to included in 2.3.0 after all. 

Opened related documentation issue: #84 for specifying the endpoints that are now available.
