### ISSUE TITLE
Upcoming DJ On Air widget printing strange number next to the time

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#20]
**Describe the bug**
<img width="286" alt="Screen Shot 2019-07-24 at 9 21 18 PM" src="https://user-images.githubusercontent.com/4053819/61838851-3968c280-ae59-11e9-9853-03fb2280bf5f.png">

**To Reproduce**

1. View Widget in sidebar of https://netmix.co/radio-station-demo
2. View number printed next to time stamp.
3. Not sure what this is or should it be there.

**Expected behavior**

Unsure - not sure why that number of being printed on the page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tonyzeoli** [comment]
This is related to the closed ticket here: https://github.com/netmix/radio-station/issues/14

**Comment by majick777** [comment]
The number is a UNIX timestamp format which was not being converted to weekday before translation. Fixed for next release.

**Comment by majick777** [comment]
The number is a UNIX timestamp format which was not being converted to weekday before translation. Fixed for next release.

**Comment by majick777** [comment]
The number is a UNIX timestamp format which was not being converted to weekday before translation. Fixed for next release.
