### ISSUE TITLE
[Show File] Optional Disable Download of Audio File

### ISSUE THREAD

**Issue by XLRradio** [netmix/radio-station#206]
Hi all not a bug as such but when we put the link to the lastest audio file in, it shows the audio file on the show page but how do we get rid of the download button next to it? we don't want people to download the file just listen to it.

![image](https://user-images.githubusercontent.com/63446711/81056556-a61dec80-8ec2-11ea-9427-4f22424c649f.png)

thank you

**Comment by tonyzeoli** [comment]
@majick777 Can you add a setting to disable the download for audio files, please. Some stations may not be able to allow music downloads and they can't have a download button next to the audio icon. We can do something like reduce the opacity of the download button and render it not available and maybe add "Download Not Available"

**Comment by majick777** [comment]
Added to develop version 2.3.1.1 for 2.3.2 release.
