### ISSUE TITLE
Playlist remove function only removes second row of data

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#21]
**Describe the bug**

When you create a playlist and add a second row for a new track, if you try to remove, it will only remove the second row of data and not the first row, which is the song name, artist, album name, and label.

**To Reproduce**
1. Add New Playlist
2. Add first Playlist entry and save.
3. Add second Playlist entry and save.
4. Try and remove the second Playlist entry.
5. The second row of the track meta data disappears but the first row with song/artist/album/label stays present and does not remove.

**Expected behavior**

Click Remove should remove both the first row and the second row of the entry.
<img width="1548" alt="Screen Shot 2019-07-24 at 10 28 05 PM" src="https://user-images.githubusercontent.com/4053819/61841533-16431080-ae63-11e9-8fe8-a172f674521e.png">

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Side effect of splitting the track data into two rows for the display overflow fix. Updated the jQuery to remove both rows now. Added to next release.
