### ISSUE TITLE
[Shortcodes] List of Hosts/DJs, Producers, and Editors (tabbed)

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#210]
**Is your feature request related to a problem? Please describe.**

Associated with equest for automatic page with list of Host/DJs, Producers, and Editors here: [](https://github.com/netmix/radio-station/issues/209)

Should enable a shortcode same as automatic page.

**Describe the solution you'd like**

Shortcode for list of station staffers.

**Describe alternatives you've considered**

**Additional context**

This is associated with [](https://github.com/netmix/radio-station/issues/209)

**Comment by majick777** [comment]
The automatic page would just use the shortcode so we don't need to treat them as separate issues, when the shortcode is ready will be easy to add an automatic page for it.

**Comment by tonyzeoli** [comment]
Got it, thanks!
