### ISSUE TITLE
404 error on show page 2

### ISSUE THREAD

**Issue by penarthsounds** [netmix/radio-station#215]
On the 2nd page of the "Shows" option it goes to a 404 error. www.penarthsounds.co.uk

**Comment by tonyzeoli** [comment]
Sorry, I clicked on the Shows tab, it returned a list of Shows. Then I clicked on a Show title and returned the show page. Also, this is a forum for bugs and feature requests. For general suoort inquiries please post to the suooort forum on the WordPress.org plugin page.

**Comment by tonyzeoli** [comment]
Closing this issue here. If you have any additional issues please post to the plugin page at https://wordpress.org/plugins/radio-station.

**Comment by penarthsounds** [comment]
If you scroll down to the bottom of the Shows page, it goes onto a second page. That's where the 404 happens.
