### ISSUE TITLE
[Archive Shortcode] Add pagination to Archive list shortcodes

### ISSUE THREAD

**Issue by penarthsounds** [netmix/radio-station#217]
Hi.

On my shows page, as the shows continue onto a second page (next page link is at the bottom of the shows page), the link to the second page of shows is broken. It's missing a "/".

It should link to http://penarthsounds.co.uk/shows/page/2

but instead it links to http://penarthsounds.co.uk/showspage/2/

How do I insert the missing "/"?

**Comment by majick777** [comment]
@penarthsounds Archive pages are created by WordPress and the content is served via your theme's archive template - usually `archive.php` in your parent/child theme directory (see https://wphierarchy.com)

So this looks like there is a bug in the navigation module of the archive template in the theme (which may be a separate template or function) and it would be best to report it to the theme's author, as this isn't something we have any control over.

An alternative  (or a workaround in the meanwhile), using the Radio Station plugin, would be to create a Page called "Shows" (and thus with a slug "shows") and then use the Show Archive shortcode on the page: `[shows-archive]`
see: https://netmix.com/radio-station/docs/Shortcodes/#shows-archive-shortcode
Note however this will display somewhat differently to the in-built theme archive and this shortcode does support pagination (yet.)

**Comment by majick777** [comment]
@penarthsounds Actually I will just repurpose this issue for adding pagination to that shortcode.

**Comment by majick777** [comment]
Pagination prototype has been added to Archive Shortcodes. Will leave this open pending some further testing.

**Comment by majick777** [comment]
Closing as this was actually added in 2.3.3.9
