### ISSUE TITLE
[Documentation] Sync website Docs with develop branch

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#219]
In order to have the latest Documentation automatically available on Netmix.com, we can synchronize the documentation file contents directly from the Github repo develop branch.

**Comment by tonyzeoli** [comment]
@majick777 I believe this is completed, is that correct?

**Comment by majick777** [comment]
@tonyzeoli No it is still being manually synced. I will get to this one in time, it just isn't that much of a priority when it takes a short time to sync manually.

**Comment by majick777** [comment]
Also I think that we should just sync this to master branch rather than develop, or it could be confusing for users.

**Comment by tonyzeoli** [comment]
Okay, we'll leave this open until you get to it. Thanks!

**Comment by majick777** [comment]
Docs are now synced to Github `/docs/` (`master` branch) and refresh automatically every 24 hours.
