### ISSUE TITLE
Unexpected Array Printed Before Master Schedule

### ISSUE THREAD

**Issue by Fishy49** [netmix/radio-station#220]
**Describe the bug**
An array of `shift_keys` is printed when the master schedule is displayed via a shortcode and overrides are active in the schedule

**To Reproduce**
1. Create some shows and add shifts to them
2. Create an override within the next week so that it'll display on the master schedule
3. Create a page and use the shortcode to display the master schedule: `[master-schedule list="table"]`
4. Navigate to the page you just created and notice the array printed before the schedule table.

**Expected behavior**
Only see the master schedule on the page

**Screenshots**
![image](https://user-images.githubusercontent.com/5632528/83047679-4ffa2000-a00e-11ea-9598-5c7da8cd23dc.png)

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.4
 - Browser Chrome
 - Version 83

**Additional context**
The issue is this unprotected `print_r`:
https://github.com/netmix/radio-station/blob/master/includes/support-functions.php#L1051

**Comment by tonyzeoli** [comment]
@majick777 Just tagging you on this to pick up. Let us know what you find out.

**Comment by majick777** [comment]
@Fishy49 Confirmed. Thanks for reporting. I have commented out the offending `print_r`
