### ISSUE TITLE
Highlight current show in Tabbed View and List View

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#223]
**Is your feature request related to a problem? Please describe.**

A user asked about highlighting a current show in tabbed view in the support forum.

[](https://wordpress.org/support/topic/highlight-on-air-now-in-tabbed-schedule/)

**Describe the solution you'd like**

If the show is the current show in tabbed view or list view, should have a red border and the list item should be able to be targeted, so that it can have a background or change some other style in the list item. Currently, the list item looks like a print out of the genres and not the Post ID of the Show Entry.

Maybe, we switch it to Post Id, so that what each individual entry can be targeted by ID for custom styling?

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by majick777** [comment]
The class and border for List view have already been added (along with the dynamic schedule checking via javascript to highlight the current show.) see #218

The List view being left unstyled unintentionally, doesn't have the class or checking added to it yet, so we may as well add the same for that view, even though it won't display, by having the class the current show can be styled.

**Comment by tonyzeoli** [comment]
Ah, okay, so it will be in the next release. Cool.

Did you mean in the second paragraph to say "tabbed" view?

**Comment by majick777** [comment]
Added List view classes (with dynamic update) to 2.3.1.3 for 2.3.2 release.
