### ISSUE TITLE
[Release] Radio Station 2.3.2

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#224]
Release ticket for version 2.3.2.

**Comment by tonyzeoli** [comment]
@majick777

This is a checklist ticket to ensure that we've got everything in place for the next release.

1. Check version number updated to 2.3.2
2. Check all changelog items added
3. Check update notice items added
4. Check documentation is updated
5. Check if need any additional screenshots

**Comment by majick777** [comment]
Waiting on shift conflict fix confirmations from #232 and #234 
1. Version number will need to be bumped to 2.3.2 from 2.3.1.x before release.
2. All changelog items are kept up to date as they are added.
3. Notice items have been updated.
4. Documentation updated (some minor shortcode changes)
5. No additional screenshots needed for this release.

**Comment by tonyzeoli** [comment]
Release completed.
