### ISSUE TITLE
[Master Schedule] Show Days shortcode attribute

### ISSUE THREAD

**Issue by Ajames0807** [netmix/radio-station#227]
I am trying to display a single day on the master schedule, I have used the shortcode: [master-schedule days=”Monday”] but this doesn’t show Monday or any day, am I doing something wrong?

**Comment by tonyzeoli** [comment]
You shouldn't be doing something wrong. That looks correct according to the shortcode FAQ.

Did you copy and paste the " marks? Try to make sure your quotes are correctly typed manually and see if that's the issue.

**Comment by majick777** [comment]
@Ajames0807 Seems to have been a typo on my part rather than yours (day vs weekday in the code.) I've added a fix to the latest development versions 2.3.1.5 for 2.3.2 release. 

https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing
