### ISSUE TITLE
Display Today's Schedule

### ISSUE THREAD

**Issue by pozitronios** [netmix/radio-station#228]
Display Today's Schedule, for example:
![image](https://user-images.githubusercontent.com/66794856/85169470-8aa15200-b274-11ea-9793-5b2c42f7dd12.png)

**Comment by tonyzeoli** [comment]
Um, can you please elaborate. We're not mind readers here, lol. Is this an issue or a feature request?

**Comment by pozitronios** [comment]
Hello, sorry I apologize, this is a feature request to have a shortcode to display today's shows. However instead of displaying a day from midnight to midnight (start - end of the day) it would be more useful to display the schedule like the example picture above, makes more sense.

**Comment by majick777** [comment]
@pozitronios You can use the Master Schedule shortcode for this:
`[master-schedule view="list"]`

For a list of available shortcode attributes see: https://netmix.com/radio-station/docs/shortcodes/

This view is an (intentially) unstyled list view that you can use to add some CSS styling to make the looks closer to what you want, for example adding floats and fonts etc.
