### ISSUE TITLE
Changing shows does not update in live schedule

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#230]
**Describe the bug**
Updating show title and avatar, but it doesn't update in the front end schedule.

**To Reproduce**
1. Go to an existing show
2. Change the title and Avatar
3. Update, and check the front end schedule
4. See error where it does not update/reflect the change to the schedule

**Expected behavior**
Schedule should update based on back end changes.

**Comment by astevens93** [comment]
Closing issue, took some to commit to the database.

**Comment by tonyzeoli** [comment]
Okay, thanks. Yeah...I was surprised to hear of this, as no one has reported it.

**Comment by astevens93** [comment]
No worries, it was my hastiness in wanting to see changes updated. Took about 30 minutes I think.  I have submitted an issue I have faced on the Wordpress Plugin page around the Overriding of Schedule items and an issue it seems to cause me.
