### ISSUE TITLE
[Conflict Checker] Show conflict detected on every day

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#234]
**Using Dev Version 2.3.1.7**

**Describe the bug**
I have a show every day that runs 10.00pm - 12.00am and since the Dev Version 2.3.1.7, it detects a conflict with every show.
So ALL my shows are in conflict with this show.

**To Reproduce**
1. Set up a show that runs 10.00pm - 12.00am (as in Midnight) every day.
2. It will be in conflict with every show that already exists in the schedule.

**Expected behavior**
No show conflict, because there is no conflict.

**Screenshots**
https://snipboard.io/hJQkj2.jpg

**Additional context**
Running Dev Version 2.3.1.7

**Comment by astevens93** [comment]
To add to this, it creates a problem as I cannot update any existing shows because the show conflict disables the show given it finds a conflict all of the time.

Schedule override works fine.

**Comment by astevens93** [comment]
Thanks for marking this as something to work on @majick777 
Is this an easy fix to make so we can use the Dev version in the meantime, or will it be something I should wait for in the next public release.  

Thanks again,

**Comment by majick777** [comment]
@astevens93 We are on the verge of releasing 2.3.2 and hoping this issue is the final hurdle.
Try out development version 2.3.1.8 I have had another go at the shift conflict checker as per #232

**Comment by astevens93** [comment]
Super, it seems to work!  I will check that the 10pm - 12 am show highlights when the time comes, and will report back if not.
I'm sure it will though.

Cheers. Look forward to the official 2.3.2 release.

**Comment by astevens93** [comment]
Still have issues but on other days/parts - but not registering as show conflict, just not allowing me to make active, and added comment to #232

**Comment by astevens93** [comment]
To refer back to this, the 10pm - 12am show is not highlighting as On Air like other shows do. Issues relating to the conflicts referred to in #232 may be related.

**Comment by majick777** [comment]
@astevens93 You can recheck the show highlighting for midnight times on Tab view it should be fine in 2.3.1.9 now.

**Comment by astevens93** [comment]
Yes works perfectly thank you.
