### ISSUE TITLE
Tabbed view doesn't collapse, doesn't bring up day on tab

### ISSUE THREAD

**Issue by boywondr16** [netmix/radio-station#238]
Not sure what brought this on, but trying to use tabbed display for my station's schedule gives a 2-level tab setup with only the active day being able to be accessed. Day links don't work, tabs don't collapse down to be just one row.

I have the settings unchecked for the page to be automatic and have run into this using either the [master-schedule view="tabbed"] or [master-schedule view="tabs"] setup.

http://www.1310kfka.com/home/schedule/

**Comment by tonyzeoli** [comment]
This has been fixed in the latest development version. We're just about to release this as 2.3.2, but there's now a new issue that just popped up that we need to fix first. So, please be patient while we work this out.

**Comment by majick777** [comment]
@boywondr16 I can see there is a javascript error in the development version you are using (the countdown function was being called when countdown not enabled on the widget.) 

You should be able to temporarily resolve this error by disabling the AJAX loading of the Current Show widget, as this looks to be what is breaking the Schedule View javascript also.

As @tonyzeoli mentioned we are just checking on one last issue in the development version before pushing 2.3.2 #237

**Comment by majick777** [comment]
@boywondr16 Development version 2.3.1.11 is up, which includes this fix (do not use 2.3.1.10 has a schedule display bug.)

**Comment by boywondr16** [comment]
Thank you!
