### ISSUE TITLE
Functions Filter for hiding day of week in schedule details for widget/shortcode

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#240]
Hi,
Just referencing filter created for #237 to hide 'day' from Current Show/Upcoming Widget.

I cannot get to work in my functions.php file in the latest dev version 2.3.1.12.

As we identified there isn't a big need for this from most users so no rush to fix, but I cannot get it to work in latest version unfortunately. Just to flag.

Note to match for shortcode `$args['widget']` will be 0. And to do it for both just exclude that condition entirely.
This would do it for both Current and Upcoming Shows Widgets and Shortcodes:

```
add_filter( 'radio_station_time_format_start', 'custom_time_format_start', 10, 3 );
function custom_time_format_start( $format, $context, $args ) {
    if ( ( 'current-show' == $context ) && ( 'upcoming-shows' == $context ) ) {
        $format = 'g:i a'; 
    }
    return $format;
}
````

_Originally posted by @majick777 in https://github.com/netmix/radio-station/issues/237#issuecomment-655603433_

**Comment by majick777** [comment]
@astevens93 The example I gave has AND `&&` instead of OR `||` in the condition, but it will never equal both, so just change it to OR: `||' and it should work fine.

**Comment by astevens93** [comment]
Hi @majick777 I still cannot get this to work in my child theme function file, seems odd as it worked in a previous version!
Cleared browser cache to check.

**Comment by majick777** [comment]
@astevens93 I tested it as it is and seemed to work fine for me. There isn't any difference in this filter since it was put in place. You could try putting it in a single PHP file in `/wp-content/mu-plugins/` (or adding it via a Code Snippet plugin) to debug further.

**Comment by astevens93** [comment]
That worked in mu-plugins - did not think of that!  Thanks @majick777 .  
Right that means I've made myself another task of finding out why it's not running in my functions.php!

Appreciate all your help, as you can tell I am a heavy user of the plugin but not the most clued up on Wordpress coding so appreciate your patience.
