### ISSUE TITLE
[Schedule View - Tabs] Cannot access first tab or last tab in mobile view

### ISSUE THREAD

**Issue by XLRradio** [netmix/radio-station#242]
**Describe the bug**
When on the "tabbed view" option we cannot scroll left to Monday's schedule

**To Reproduce**
1. Go to 'xlrradio.co.uk'
2. Click on 'schedule.'
3. try clicking left arrow 'on schedule'

**Expected behavior**
obviously expecting it to click back to be able to view monday.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser edge
 - Version latest

**Comment by tonyzeoli** [comment]
I've confirmed this issue in mobile on your site and on our demo site. 

@majick777 I've confirmed in mobile, if you're on Monday, you can't click to Sunday on radiostationdemo.com. We should get out a fix for this asap as 2.3.2.1. Let me know what you find out.

**Comment by XLRradio** [comment]
@tonyzeoli is not only in mobile. its the Tabs schedule. on desktop computers you can view tuesday to sunday but if you want to click the arrow to view the day before ie monday you cant

**Comment by tonyzeoli** [comment]
@XLRradio okay, thanks for that. On desktop I saw all the tabs on our demo site, but did not click them. My error. I’ve corrected the title and @majick will respond shortly with a fix I’m sure.

**Comment by majick** [comment]
Please stop tagging me in your issues.  I'm not the person you're trying to tag.  Thanks!

**Comment by XLRradio** [comment]
i think he meant @majick777

**Comment by tonyzeoli** [comment]
@majick So sorry! I meant @majick777 - don't know how you ended up in my autocomplete!

**Comment by majick777** [comment]
@XLRradio I took the opportunity to improve the code for the tab and table responsiveness and combine it better with the left/right arrows, this should resolve the issue. Added to development version 2.3.2.1 for 2.3.3

@tonyzeoli Previously the responsiveness was based on fixed widths but with the addition of being able to display certain days via the shortcode, it made sense to change this to detect the actual widths for each column and use those for a better result (previouslt there was a small margin of error where the tabs could still split into two lines.)
