### ISSUE TITLE
[v 2.3.2.1] Radio Time and Your Time Do Not Display

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#244]
**Describe the bug**

On RadioStationDemo.com, the Master Schedule Radio Time and Your Time views are no longer displayed.

Running Radio Station 2.,3.2.1

**To Reproduce**
1. Go to https://radiostationdemo.com
2. Click on Master Schedule (any view)
3. View null for Radio Time and Your Time clock

**Expected behavior**

View clock.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac Catalina 10.15.5
 - Browser [e.g. chrome, safari] Chrome for Mac
 - Version [e.g. 22] Version 84.0.4147.89

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] IPhone
 - OS: [e.g. iOS8.1] iOS 10
 - Browser [e.g. stock browser, safari] Chrome for iOS
 - Version [e.g. 22] not sure

**Additional context**

<img width="1512" alt="Screen Shot 2020-07-23 at 11 40 48 PM" src="https://user-images.githubusercontent.com/4053819/88359001-18be9b80-cd3f-11ea-87a9-790057a9a186.png">

**Comment by tonyzeoli** [comment]
Not sure what happened, but working now.

**Comment by majick777** [comment]
@tonyzeoli Possibly was just happening when I was testing the new width responsiveness javascript.

**Comment by tonyzeoli** [comment]
most likely, yes...wasn't aware you were working on the site at the
time...all good now though.
