### ISSUE TITLE
[Netmix.com] Login page broke with recent updates

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#245]
**Describe the bug**

The /wp-admin login page on Netmix broke with the most recent plugin updates.

**To Reproduce**
1. Go to https://netmix.com/wp-admin
2. View page
3. Stylesheet seems to have gone away for the page
4. Nav menu broken, logo missing
5. Many elements on the page are now unsettled including around the login text fields and sidebar.

**Expected behavior**

Correct styles appearing.

**Screenshots**

<img width="1512" alt="Screen Shot 2020-07-24 at 12 05 19 AM" src="https://user-images.githubusercontent.com/4053819/88359753-d5b1f780-cd41-11ea-955a-c0cc229fcc97.png">

**Comment by majick777** [comment]
@tonyzeoli Were you testing any accessibility plugins? Seems like autoptimize cached the javascript for one and was applying it. This was breaking the HTML not just on the login page but the entire site. 
I also couldn't login at all, and had to clear my cookies for the site. And disable Jetpack temporarily as it seems it was blocking logins. 
When enabling, disabling and updating plugins we should clear the Autoptimize cache, this should happen automatically but seems it may not be in some cases.

**Comment by tonyzeoli** [comment]
Okay, I will definitely do that. I think there's an issue with Autoptimze 2.7.5 anyway. You can see that on [their support page as a sticky post.](https://wordpress.org/support/topic/2-7-5-known-issues/). This may have been an issue as it was an issue on the Bookstr.com site I'm working on.
