### ISSUE TITLE
Tabbed View additional text appearing on upgrade to 2.3.2

### ISSUE THREAD

**Issue by KerryB1** [netmix/radio-station#246]
Just upgraded to 2.3.2 and noted additional text appearing on Tabbed schedule view .  This appears when text is included in a show description.

![image](https://user-images.githubusercontent.com/68817551/88482849-c908eb80-cf5b-11ea-9cf2-38797a4bd14b.png)

Note that the first entry , Sunday teatime Show does not have any text in the Show description entry.
Second entry ,  Weekly News Review has text in the Show description entry.

To  Reproduce,  select the Tabbed View of Master schedule.  Create a new show and add  a show description.   Text should then appear on a refreshed schedule page. 

Does not appear to replicate on other Schedule views

Running on Chrome browser.
Wordpress version confirmed as compatible for RadioStation ( On Ionos platform)

Issue noted a soon as upgrade to new 2.3.2 version completed
 
New to Radio Station plugin

**Comment by majick777** [comment]
@KerryB1 I did enable the Show Description display by default in version 2.3.2 for the Tabbed view. But have decided to revert that, since it's possible other plugins interfere with the description excerpt. We are just pushing version 2.3.3 so I've added this change as a last minute hotfix.

**Comment by tonyzeoli** [comment]
Please download version 2.3.3 from the [WordPress plugin page.](https://wordpress.org/plugins/radio-station).

**Comment by KerryB1** [comment]
Hi

 

Thanks for the quick response.

Have tested the update and  show information now appearing as expected.

 

It appears the rogue text was being picked up from the  page that the Master Schedule was being displayed on and not the Show Description text.

Worth noting that Master Schedule page needs to be blank on these releases as any content was ignored on 3.2.1 and before

 

Kerry
