### ISSUE TITLE
[Plugin Settings] Can't change 12 hour format to 24 hour format

### ISSUE THREAD

**Issue by larryl79** [netmix/radio-station#247]
**Describe the bug**
Can't change 12 hour format to 24H format in settings.

**To Reproduce**
1. Go to 'settings'
2. Click on 'time format 24h'
3. save settings
4. See error : it turns back to 12H format

ver: 2.3.1, 2.3.2

**Comment by majick777** [comment]
@larryl79 Thanks for reporting. I've added this as a last minute hotfix to 2.3.3 which we are pushing out shortly.

**Comment by tonyzeoli** [comment]
Should be out before midnight EST.

**Comment by tonyzeoli** [comment]
Please take the latest version, 2.3.3, from the [WordPress plugin page.](https://wordpress.org/plugins/radio-station)

**Comment by larryl79** [comment]
I repulled 2.3.3 from wordpress and I've got still same issue.

**Comment by majick777** [comment]
@larryl79 Sorry, seems like I had a network glitch on last push and didn't notice. My connection is truly next level horrible today. You can download and install the plugin from the Github master branch while we get that last fix resynced to WordPress SVN.

**Comment by larryl79** [comment]
Hmmm stange... I dunno what's going on then. I just pulled master zip from here, deactivate and delete plugin, delete %radio_station% from wp-options, extract zip, upload into appropriate dir, activate plugin and still same issue. so I banging my head now into the desk...

**Comment by tonyzeoli** [comment]
@larryl79 I just released 2.3.3.1 within the last 30 minutes of this post on the WordPress plugin page after @majick777 included the hotfix missed in 2.3.3. Please try again.

**Comment by tonyzeoli** [comment]
@larryl79 I just checked my install on radiostationdemo.com and was able to switch 12 to 24 hours and 24 to 12 and save.

**Comment by larryl79** [comment]
I updated it now. Actually it was saved to 24H format, just not shown it in setting. now is perfect.

**Comment by tonyzeoli** [comment]
@larryl79 Great. Glad we got that fixed for you. We'd appreciate a review of the plugin on our WordPress plugin page at https://wordpress.org/plugins/radio-station. Please take a moment to review. We appreciate it.

**Comment by tonyzeoli** [comment]
@larryl79 When you complete the translation, send us the .po / .mo files and we'll include them. Thank you for your help with this. It is very important for us to have quality translations in other languages.

**Comment by larryl79** [comment]
Sure.
