### ISSUE TITLE
[Schedule Overrides] Link to or copy data from existing Show

### ISSUE THREAD

**Issue by larryl79** [netmix/radio-station#249]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
enable add exist show to schedule override without fill out anything just click on show name, and show + dj-s will be added for that overridden schedule.

**Comment by majick777** [comment]
@larryl79  Sorry I'm not sure I'm quite following your description here. You are just adding an empty override, and Hosts are being assigned to it?

**Comment by larryl79** [comment]
No, sorry for my misunderstood. :)

1. add override.
![image](https://user-images.githubusercontent.com/24578424/88533086-931c4380-cffd-11ea-9c58-9377b1fe1c5d.png)

2. how can add here an exist show with hosts/producers?!

only what I can do just enter a name and description, but no hosts/producers can be added/selected. So the idea is add a selectable list to this page with exist shows, when (I) click on the exist show, on this page all details (show name, hosts, producers, lang, etc) will be filled out with that show.

for example I'm a host with a show Larry's Partytime which used to be on sat night. but there's an empty space for tonight, so I can add an override for my show easily with a click, instead of edit an exist show.

**Comment by majick777** [comment]
@larryl79 I think the easiest thing for you to do right now would be to add another Shift to the Show for the desired timeslot (and disable the other Show's overridden shift temporarily.) 
I will need to consider how and what would be pulled from an existing Show, and even possibly whether they could be linked or synced. But probably just copied to begin with (so Override adjustments can be made.)

**Comment by larryl79** [comment]
@majick777  I just gave a feature idea  :) we can chat considerations if u like.

**Comment by majick777** [comment]
This is probably a good follow-on thing to do from #301. But until that is in place, it wouldn't quite make sense yet.

**Comment by majick777** [comment]
@larryl79 @tonyzeoli Have combined this issue with #301 to come up with Schedule Overrides that can now be linked to an existing Show. Individual field overrides can be toggled from the Override edit screen so that any combination of data can be used from the Show or Override. :-) 

Included in development version for next release.
