### ISSUE TITLE
Now Playing Widget List Items Enhancement

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#25]
**Is your feature request related to a problem? Please describe.**

The Now PLaying Widget lists the Artist, Title, Album, Label and Playlist in one long row. And, there are no headers in the widget for Artist, Title, Album, or Label.

**Describe the solution you'd like**

When the Now Playing widget is set in a sidebar, the Artist, Song, Album, and Label headings should be printed on the screen as a LIST, like this:

Song Title: {print song here}
Artist Name: {print artist name here}
Album Name: {print album name here}
Label Name: {print label name here}
View Playlist {link}

**Describe alternatives you've considered**

In the future, we can add a thumbnail.

**Additional context**

**Comment by majick777** [comment]
Fixed along with #30 for next release.

**Comment by majick777** [comment]
"In the future, we can add a thumbnail."
A Thumbnail for the Playlist? Easy to do but do you think it would be used? Can't hurt I suppose.

**Comment by tonyzeoli** [comment]
Per "thumbnail" for playlist. Maybe too ambitious at the moment. Probably not necessary as the playlist is added to a Show page and there is no Featured Image option in the Playlist edit view. Let's leave this one off for now. I didn't think it through enough but now realize it's not justified. Thanks for your feedback.
