### ISSUE TITLE
Viewing: Sunday displayed in responsive mode when Day 6 is selected

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#250]
**Describe the bug**
This has occurred since the update and I am running Version 2.3.3.1.
As you can see from the attached video file, when in responsive view (and consequently mobile devices) if you have the Sunday (or it could just be Day 6 depending on the start day of your week), just below the day tabs a DIV appears with the text 'Viewing: Sunday'.   This does not happen on any other day selected.

**To Reproduce**
1. Go to Day 6 of your schedule in tabbed view (in my case this is Sunday)
2. Make the screen size smaller, or view on mobile device. Sometimes you might need to scroll down and then back up again for it to show.

**Expected behavior**
This would not appear.

**Screenshots**
See attached video.

**Additional context**
I have hidden it as a temporary measure myself using the below CSS

```
#master-schedule-tabs-selected-6 {
	display: none !important;
}
```
[Screen Recording 2020-07-27 at 19.00.53.mov.zip](https://github.com/netmix/radio-station/files/4983722/Screen.Recording.2020-07-27.at.19.00.53.mov.zip)

**Comment by astevens93** [comment]
Hello again. Sorry please ignore me. I had a look at the demo site and I realise why you have done this now, it’s because by default you may scroll across to access another day so it shows the day you are viewing.

Got it.  It is because my tabbed view is styled different to the norm.

I will close, but good for anyone else interested. Just hide with CSS!

![1114D515-D78A-4B5F-9F4C-95CDDA139E90](https://user-images.githubusercontent.com/67294458/88576906-16f62000-d03e-11ea-9c9d-6aa7fe41deb4.jpeg)

**Comment by majick777** [comment]
@astevens93 Yes you are correct, this was done to resolve #229
