### ISSUE TITLE
[Plugin Content] word mistype in php file

### ISSUE THREAD

**Issue by larryl79** [netmix/radio-station#252]
**Describe the bug**
radio-station/trunk/includes/post-types-admin.php  line 2265

echo ' ' . esc_html( __( "You can then assign them to a relevent Post Category for display on your site also.", 'radio-station' ) );

todo:
change "relevent" word to "relevant"

Remark: I don't translate it until not changed.

**Comment by tonyzeoli** [comment]
@larryl79 Thanks for this. @majick777 is from Australia and may not spell words in U.S. English. Please let us know if you find some other content spelling issues.

**Comment by larryl79** [comment]
/radio-station/trunk/includes/post-types-admin.php  Line 1016

$error = __( 'Failed. Relogin in try again.', 'radio-station' );

may this should be (???) :
$error = __( 'Failed. Relogin in %s Try again.', 'radio-station' );

**Comment by tonyzeoli** [comment]
Fixed for next Milestone: 2.3.3.2

**Comment by larryl79** [comment]
> @larryl79 Thanks for this. @majick777 is from Australia and may not spell words in U.S. English. Please let us know if you find some other content spelling issues.

I spelling UK english LAMO

**Comment by larryl79** [comment]
PLease keep this issue open until I finishing with all translations in dev trunk. I don't want make new issues if I find another like this. At this moment I've done 336 from 570 in dev trunk.
