### ISSUE TITLE
[Master Schedule] When show spans midnight the red border only appears from 12 am until and not prior

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#255]
**Describe the bug**

I set a shot to span midnight - 11 pm to 4 am. The red border appears from 12 midnight to 4 am, but not from 11 pm to 12 midnight.

**To Reproduce**
1. Go to RadioStationDemo.com
2. View Show Starting at 11 pm on Sunday to 4 am on Monday (same for Tuesday)
3. Red border only appears for the box after 12 midnight

**Expected behavior**

The red border should span the entire time.

**Screenshots**

<img width="1552" alt="Screen Shot 2020-08-03 at 2 37 28 AM" src="https://user-images.githubusercontent.com/4053819/89153368-b6318080-d532-11ea-9eef-7bcc1ea738e1.png">
<img width="1552" alt="Screen Shot 2020-08-03 at 2 37 25 AM" src="https://user-images.githubusercontent.com/4053819/89153377-b9c50780-d532-11ea-8a13-b722fba4166c.png">

**Comment by majick777** [comment]
@tonyzeoli I've modified the schedule shortcode templates (table/tabbed/list) to include a new class for shifts that are split overnight, and then updated the Show highlighting javascript to apply the `nowplaying` class to those shifts when they match overnight, the effect being that the current Show is highlighted regardless of whether it is split overnight or not. :-)
