### ISSUE TITLE
[Data API] Broadcast endpoint lists next show the same as the current show

### ISSUE THREAD

**Issue by greenday2087** [netmix/radio-station#256]
I'm new to this plugin, which by the way is fantastic!

I think I may have found a bug... when I run http://localhost/wp-json/radio/broadcast/ it lists the same show under current (correct) and next (incorrect).

It is also missing some additional information in both areas such as avatar URL (which is appearing fine in the shows endpoint).

Many thanks
Stephen

**Comment by tonyzeoli** [comment]
@greenday2087 Is this related to the API?

@majick777 Can you field this issue, please? Thanks!

**Comment by majick777** [comment]
@greenday2087 Thanks for the report. Can you recheck with the latest version (2.3.3.3) as this included fixes for the Current and Upcoming Shows calculation.

**Comment by greenday2087** [comment]
@majick777 thank you this is now working as expected. keep up the great work!

**Comment by greenday2087** [comment]
@majick777 apologies, it _was_ working when i replied, but since it went past 16:00 it is now behaving in the same way as originally reported and listing the same show for now/next. i've attached an image but if you catch this message in the next 3 hours whilst this show is on you may see the error live if you go to https://prideradio.co.uk/new-site/wp-json/radio/broadcast/

You can see the shifts I've setup for this show here http://localhost/wp-json/radio/shows/?show=drivetime-with-dave-walls

![pride-json](https://user-images.githubusercontent.com/69258704/90031576-4b601200-dcb5-11ea-8770-9a72558ed3fc.PNG)

**Comment by majick777** [comment]
@greenday2087 I've added some code to recalculate the next Show if it is the same as the current Show. (Included in latest hotfix.) Hopefully this will fix the issue, but let us know if it doesn't.
