### ISSUE TITLE
"Thanks for Updating" Notice Not Closing

### ISSUE THREAD

**Issue by danielodeyemi** [netmix/radio-station#258]
**Describe the bug**
The "Thanks for Updating" on the administrator panel in the admin area cannot be closed. Clicking the "dismiss this notice" (x) button does nothing .

**To Reproduce**
1. Go to 'site.com/wp-admin'
2. Click on 'Dismiss this notice (x) button on the Update Notice'
3. Error: Nothing happens, the notice still stays there at the top of every administrator page

**Expected behavior**
The Thanks for Updating Notice should be dismissed from the administrator dashboard and pages.

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10
 - Browser Brave Browser
 - Version 1.11.104 Chromium: 84.0.4147.105 (Official Build) (64-bit)

**Comment by tonyzeoli** [comment]
Have you tried a different browser? I’ve never even heard of the Brave browser, but we’ll look at it and see if we can replicate the issue.

**Comment by danielodeyemi** [comment]
No I have not tried a different browser.
Never heard of Brave browser? Wow, you can maybe check it out at https://brave.com 
It is a privacy centered browser, very wonderful browsing experience I must say.
Thanks

**Comment by Ajames0807** [comment]
Hello - i'm too having this issue. Cannot close the message after updating.

I have tried in both Chrome and Firefox, on the main admin user access and a secondary user access. I have tried all the usual stuff, clear cache, internet files/cookies etc etc but nothing is working to let me remove the message. 

Thanks

**Comment by Ajames0807** [comment]
This might help... the error shows in the console on chrome...

![err](https://user-images.githubusercontent.com/67065843/89765377-1b1a4700-daee-11ea-9dbf-e26b35181ef8.PNG)

**Comment by majick777** [comment]
@danielodeyemi @Ajames0807 Turns out not to be an error in the code, but rather that the readme.txt got slightly corrupted in the last merge, preventing the data from being parsed correctly. I've pushed a hotfix to master branch if anyone wants to replace the readme.txt file from there so they can dismiss the notice, otherwise it is fixed for next release anyway.

**Comment by tonyzeoli** [comment]
This is now pushed, but there is no new release version number - Download a copy of 2.3.2.2 and just move the updated readme.txt to your plugin folder or take the development version of the readme.txt file and move it to your plugin folder via FTP or SFTP.

**Comment by Ajames0807** [comment]
That's done the trick! Thanks again for the fix

**Comment by danielodeyemi** [comment]
Okay then. Thanks a lot.
