### ISSUE TITLE
[Show Pagination] Filter Previous and Next Show links according to Schedule

### ISSUE THREAD

**Issue by KerryB1** [netmix/radio-station#259]
Radio Station 2.3.3.3
Wordpress 5.4.2

Potential issue with Previous Show and Next Show links at bottom of a Show page.
Selecting one of these links does not take  you back or forward within the schedule but selects a  show at different time/date.  The link always goes to the same previous/next show ,  so does not appear to be a random selection.

1-  Select the main schedule
2-  Select a Show and display show contents
3- Select Next Show link  and a show later in the schedule is displayed, not the next show
4 -  If the Previous Show is selected,  a different show is displayed, not the previous one in the main schedule

**Comment by majick777** [comment]
@Kerry81 This could be a tricky thing to address, as the plugin itself is not creating these Next and Previous post links. Assuming your theme uses the inbuilt WordPress `next_post_link()` and `previous_post_link()` functions then it's possible we could add a filter to those functions. 

The reason for the current behaviour without the filter is that it would be based on the Show publication date rather than the actual calculated Schedule times.

**Comment by majick777** [comment]
@kerry81 To elaborate further on the "tricky" part... If the Show has one Shift, that is easy, but if a Show has multiple shifts, how is one to know which is the "Next" or "Previous" Shift from just the Show page? As that is not always arrived at from the Schedule. 

The current Schedule would need to be checked and the "closest" Shift for that Show used to find the previous or next Show... If there is any page caching, that may not provide accurate navigation as it would cache the page with a link to an old Shift and the next and previous links would no longer be accurate.

**Comment by KerryB1** [comment]
Hi  Thanks for the reply.

 

Now I have some background I can work around the issue.

 

As an aside, the PlugIn is a good product  and gives us all we currently need for our station  ( a voluntary one that broadcasts to Hospitals around Cardiff in the UK).   Keep up the good work.

 

Kerry

**Comment by tonyzeoli** [comment]
@KerryB1 

Thank you so much for your positive comment about the plugin.

Would you be able to take a minute to review the plugin here: https://wordpress.org/support/plugin/radio-station/reviews/

**Comment by tonyzeoli** [comment]
@majick777 Can you let me know what you want to do with this one? Is this something we'll be moving into development with a filter issued? If so, scheduled for this month's end of month release 2.3.4 (tentative version number and date which can change based on what we're working on)?

**Comment by majick777** [comment]
@tonyzeoli I started writing some code for this, but it's not really a priority issue. It may or may not make it into the next release depending on other priorities. I think we keep it open for now, and I'll get to it sooner or later.

**Comment by majick777** [comment]
@KerryB1 I've finally got back to this as there was other work to do on related post links. The next and previous show links will now display for multiple shifts by attempting to find the next shift in the schedule for the Show and then linking to the adjacent Shows. This may still become inaccurate if cached, but I don't see a real way around that, I think this is sufficient for a solution.

Changes have been included in the latest develop branch for release. Feel free to test them out and report back if there is anything further here, I am closing this as done.
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing
