### ISSUE TITLE
2.2.2. Commit blocked by pre-commit hook error in authors.php

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#26]
**Describe the bug**

SVN reports the following error in the author.php file:

Parse error: syntax error, unexpected '<', expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF) in radio-station/trunk/templates/author.php on line 22
Errors parsing radio-station/trunk/templates/author.php
***********************************

**To Reproduce**
1. Commit update
2. Returns pre-commit hook error as stated

**Expected behavior**

Should cleanly commit through SVN to WordPress plugin repo with no error.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Unclosed PHP tag. Oops. Fix pushed and merged, should be good to go now.
