### ISSUE TITLE
[Overrides| Auto remove past show overrides

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#260]
**Is your feature request related to a problem? Please describe.**

astephevens93 s asking if we can do something around managing historical / past show overrides, because you can all of a sudden have a deep list of overrides that are in the past and unnecessary to view on the Show schedule admin.

**Describe the solution you'd like**

Maybe for the past overrides, we can auto hide them and at the top of the list of show times entries, we can have a toggle between Show Current and Show All. The default is to show the current Sun - Sat list and any historical override is hidden unless you Show All.

**Describe alternatives you've considered**

No specific alternatives.

**Additional context**

See the original post here on the support forum: See this post: https://wordpress.org/support/topic/auto-delete-past-schedule-overrides/

**Comment by majick777** [comment]
@tonyzeoli Seems my reply on the Support Forum thread didn't post.

I was basically making the suggestion there that we could add another dropdown filter to the Admin Override list for past and future Overrides (there is already one for months.) This way all past overrides could be selected and deleted using the existing admin interface.

**Comment by astevens93** [comment]
Thanks both. That sounds like a good addition, and I know would help make it easier for users who are making lots of overrides. 

Ideally the 'default' view would be future overrides, and like @tonyzeoli mentioned, you can toggle to view past or future.

**Comment by majick777** [comment]
@astevens93 Seem to have it working fine so far. Thought I might add an extra selection option for "Today" as well though.

Best practice for the default behaviour for lists like this is to have all filters off - so in this case that would be showing both past and future overrides. However, I understand you would like a different default, so I'll just put a filter on that value. :-)

**Comment by majick777** [comment]
@astevens93 The Override filter dropdown is now in place for Past, Today and Future Overrides, added to version 2.3.3.5 for release.
