### ISSUE TITLE
[Post List] Bulk Edit Action to set Related Show(s)

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#262]
**Is your feature request related to a problem? Please describe.**

After adding Radio Station to a station's website, the show owner may have to go back and relate posts to shows. This can be onerous if their a hundreds of posts that need to be assigned. If we can add the ability to bulk edit posts and assign them to related shows, that would be helpful under the bulk editor.

**Describe the solution you'd like**

Add a Related Shows drop down to the Bulk Edit view. Once the user selects a number of posts then selects "Edit" and "Apply", then display the Related Shows drop down in the Bulk Edit view, so that multiple shows can be assigned in one action to a Show Page Posts List.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by majick777** [comment]
@tonyzeoli Feel free to test this out on the demo site along with the Quick Edit field.

**Comment by tonyzeoli** [comment]
@majick777 Sure thing! Will do. Thanks for this. Should make it so much easier to edit stuff!
