### ISSUE TITLE
[Post List] Add Related Shows dropdown selector to Quick Edit

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#263]
**Is your feature request related to a problem? Please describe.**

A show producer should be able to open the Quick Edit view in the Posts Lists area and assign a post to a Related Show.

**Describe the solution you'd like**

Add Related Shows w/ dropdown to Quick Edit view on the Posts Lists screen. A user can click, "Quick Edit" and assign a post to a Related Show without having to edit the page itself. This will save time and help producers do their jobs.

**Describe alternatives you've considered**

N/A

**Additional context**

We want to give Show Producers multiple methods of relating a Post to a Show and make it easier for them to do the work.

**Comment by majick777** [comment]
@tonyzeoli Not the easiest to work with the Quick Edit menu, but got there in the end.

**Comment by majick777** [comment]
@tonyzeoli Oh and it should be noted that along with this I have made the Related Shows selection a multiple select so that it a Post can be assigned as related to multiple Shows, and modified the Show Posts Archive shortcode to work with multiple values.

**Comment by tonyzeoli** [comment]
@majick777 You're awesome! Thanks! I'll check it out.
