### ISSUE TITLE
Any Idea what this is - (new User)

### ISSUE THREAD

**Issue by RadioLichfield** [netmix/radio-station#264]
Any idea what this error is and why?

Notice: Undefined variable: data_format in /var/www/wp-content/plugins/radio-station/templates/single-show-content.php on line 465

We are a new user to this plugin and find it buggy? or we are doing something wrong ??

**Comment by tonyzeoli** [comment]
Can you post the link to the page you’re having an issue with?

**Comment by tonyzeoli** [comment]
@majick777 have you seen this error yet?

**Comment by tonyzeoli** [comment]
@RadioLichfield By the way, finding a bug doesn’t necessarily mean the plugin is “buggy.” We appreciate the notification and will look into it, but this error is not appearing as of now on our demo site.

**Comment by majick777** [comment]
@RadioLichField Thanks for the report. Yes looks like there is an old variable assignment to the `data-format` attribute. 

This attribute was added for a future feature and so is not used by the plugin yet, so will not affect the plugin running as intended in any way. 

I've added a fix for the next version. If you come across any more bugs please report them as separate issues.
