### ISSUE TITLE
Add filter for adding text string above latest show player

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#265]
**Is your feature request related to a problem? Please describe.**

A ticket came in on the support forum to ask for a feature to add text above the player to say something like, "Latest Show." But someone could use the player for a variety of reasons. We discussed adding a text field, but that would take too much time right now. So, we'll add a filter and the user can add the filter themselves.

**Describe the solution you'd like**

Add filter to add up to 120 characters of text above the player that sits in the left sidebar, when someone adds a link to an mp3.

**Describe alternatives you've considered**

We considered a text field, but that would add a layer of complexity we're not able to support at this time.

**Additional context**

N/A

**Comment by majick777** [comment]
Added filter `radio_station_show_player_label` to filter the label above the Show Player (default blank.)

Similarly, filters have been added for the following labels on the Show Page:
"Show Info": `radio_station_show_info_label`
"Produced by": `radio_station_show_producers_label`
"Hosted by": `radio_station_show_hosts_label`
"Genres": `radio_station_show_genres_label`
"Languages": `radio_station_show_languages_label`

Also added title attribute filters for all the icons on the Show page.

Will be included from development version 2.3.3.4

**Comment by majick777** [comment]
@tonyzeoli Can't seem to find the related Support forum ticket for this to update it, perhaps you can find it via your forum email notifications.
