### ISSUE TITLE
No Featured Image no matter what I try

### ISSUE THREAD

**Issue by Hotrodradio** [netmix/radio-station#268]
Hello all,

We use the radio station addon measures great fun. Only what we also try we don't get to see the Featured Image, we do get the avatar of 150x150.

This is the link and the code we use. Is there something wrong in the code?

https://hotrodradio.nl/show/de-dwaze-maandag-show/

[master-schedule view="tabs" time="24" show_djs ="1" show_image ="1" display_show_time ="1" show_link ="1"]

Regards,

HotrodRadio
![show](https://user-images.githubusercontent.com/63542085/93756229-0492ff80-fc05-11ea-8957-f7e3cfdd1c5d.jpg)
![settings](https://user-images.githubusercontent.com/63542085/93756235-06f55980-fc05-11ea-8e17-71c7c75a390c.jpg)
![settings2](https://user-images.githubusercontent.com/63542085/93756239-08bf1d00-fc05-11ea-9bd4-0bb94f7c01b9.jpg)

**Comment by Hotrodradio** [comment]
Problem is solved :-)

**Comment by tonyzeoli** [comment]
So sorry to not get back to you in a timely manner. Glad you resolved the issue. Let us know if you need anything else.
