### ISSUE TITLE
[Schedule] Tabbed view does not show all days on mobile

### ISSUE THREAD

**Issue by RimantasMurza** [netmix/radio-station#269]
When the timetable is viewed from a mobile device, only two tabs are visible and navigation arrows take to the first/last two tabs only. For example, when opening it on thursday, it displays the thursday tab correctly, however if you want to view what's up on wednesday, press the arrow to the left and you get taken to monday/tuesday view. Try the arrow on the right - taken to saturday/sunday view and then stuck between these two options - monday/tuesday or saturday/sunday with no way to see any other days.
![image](https://user-images.githubusercontent.com/71840129/94172188-db8b9c80-fe9a-11ea-8253-4ac3b6b0904a.png)
![image](https://user-images.githubusercontent.com/71840129/94172210-e2b2aa80-fe9a-11ea-8d66-bbf32a136ad8.png)

**Comment by tonyzeoli** [comment]
@majick777 Can you field this issue from this user, please? Thanks.

**Comment by tonyzeoli** [comment]
@majick777 I can confirm Wednesday is missing from the tabbed view for some reason on radiostationdemo.com

**Comment by tonyzeoli** [comment]
@RimantasMurza It looks like Wednesday may certainly be missing form the tab view in my testing of radiostationdemo.com. I've asked @majick777 to come through and take a look at this. Usually, we can issue a patch and you can download the development version before we release a new version. So, stay tuned and we'll get to it and see what we can find out. Thanks for reporting.

**Comment by RimantasMurza** [comment]
@tonyzeoli Cheers, looking forward to a fix!

**Comment by majick777** [comment]
@RimantasMurza Thanks for the report, I have added a fix to 2.3.3.5 ready for release. 
@tonyzeoli i have updated the Table script to match the new functionality of the Tab scripting as well.
