### ISSUE TITLE
display_date attribute in tabbed schedule shortcode not displaying correct date

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#270]
**Describe the bug**
Using https://netmix.com/radio-station/docs/Shortcodes/ as a reference, I have included display_date="1" in my shortcode to form:

[master-schedule view="tabs" show_link="0" show_desc="1" display_date="1"] in Version 2.3.3.3
or [master-schedule view="tabs" show_link="0" show_desc="1" start_day="today" display_date="1"] in Version 2.3.3.5

But it doesn't seem to output the correct dates for the days in the tabbed schedule.  For reference the day these screengrabs were taken were Wednesday 30th Sept.

Version 2.3.3.3
![image](https://user-images.githubusercontent.com/67294458/94660199-4acf1980-02fd-11eb-95ca-be71895e8707.png)

Version 2.3.3.5 (with the start day = today)
![image](https://user-images.githubusercontent.com/67294458/94660329-705c2300-02fd-11eb-8e1d-9191a7503c97.png)

**To Reproduce**
1. Add display_date="1" to your shortcode for displaying tabbed schedule
2. See error as described above.

**Expected behavior**
Each respective day would have its date shown.

**Screenshots**
See above within description.

**Additional context**
I am using custom CSS so it looks different to the radiostationdemo site.

**Comment by majick777** [comment]
@astevens93 This attribute accepts a date format rather than just a `1`, so you would use `j` for the value to display just the date, or `jS` for `1st, 2nd etc..` I will add a line to catch a `1` value to default to `jS` ... but for now you can just use `display_date="jS"`

**Comment by astevens93** [comment]
Perfect thank you.  It is my fault, I mis-read the documentation!  I have it working nicely now.
