### ISSUE TITLE
[After Update Notice] 2.3.3.1 Update Notice not dismissing

### ISSUE THREAD

**Issue by perezjos** [netmix/radio-station#273]
Hello

the Update Notice never disappear even if I press the close button
Can you help ?
Thanks

![image](https://user-images.githubusercontent.com/1007206/95671298-bbc1db80-0bf1-11eb-8d5e-de36058d00b7.png)

**Comment by tonyzeoli** [comment]
We'll take a look. Thanks for reporting this. We're just about to release an update so if this is an issue, we'll get a fix out for it.

**Comment by tonyzeoli** [comment]
@majick777 can you loop around on this?

**Comment by majick777** [comment]
@perezjos Can you let us know which version you have installed so we can test this? Also whether you have any javascript errors in your console, before and after clicking the dismissal button.

**Comment by perezjos** [comment]
Hi the version should be on the screenshot and no no error
message. Am I the only one with that problem ?
thanks
José

**Comment by majick777** [comment]
@perezjos I ask because that isn't the latest version, so updating could resolve it. I do recall the readme.txt formatting got screwed up temporarily in a merge commit in that release. (If you look at your readme.txt and it has >>> HEAD somewhere in the Upgrade Notice that is the cause.)
There is another report of this on WordPress support forum I have referred them here also.

**Comment by retiredgamer** [comment]
Hey guys!
I'm the one who posted to the Wordpress support forum. Sorry for taking so long to post here, been out of office. I am attaching a screenshot of my installation. I am running the latest version.
![radiostationerror](https://user-images.githubusercontent.com/73490928/97204110-ae752700-1783-11eb-8214-5ef7c50c5d2a.jpg)

**Comment by retiredgamer** [comment]
This issue was fixed for me in the latest release. Thanks!

Steve

**Comment by astevens93** [comment]
Just to add to this, I am also on Main Release Version 2.3.3.5 and I still get the notice.

Below is a video of said action, that does not clear (notices 5). Running Wordpress Version 5.5.3.
It does not affect functionality but worth flagging on this thread running along the same theme.

![Screen Recording 2020-11-02 at 17 14 31](https://user-images.githubusercontent.com/67294458/97898054-3ed8dc00-1d2f-11eb-8d89-3a63a62b8635.gif)

**Comment by tonyzeoli** [comment]
Thanks, will have to re-open and check this.

**Comment by majick777** [comment]
I'm going to close this old issue as unlikely anyone is using 2.3.3.1 any more and it doesn't seem to have re-emerged in future versions.
