### ISSUE TITLE
[Overrides/Schedule VIew] Mismatch date calculation with different day_start attribute

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#274]
Transferred from:
https://wordpress.org/support/topic/when-does-week-start/#post-13536858

When the `day_start` attribute is used to provide a different day in the Master Schedule view, the dates used do not match the Override dates used in the Schedule calculation. This results in Overrides not being displayed later in the week.

**Comment by majick777** [comment]
Have just added a hotfix for this issue for inclusion in 2.3.3.5

**Comment by astevens93** [comment]
Super, works in the latest hotfix in dev version 2.3.3.5.
Will watch out for master release update whenever it gets pushed.

Thanks again.
