### ISSUE TITLE
Schedule Override not showing up in Show/DJ On-Air

### ISSUE THREAD

**Issue by miklsnews** [netmix/radio-station#28]
I just did the most recent update for "Radio Station" and was hopping it would correct the schedule override issue (it did to a point now you can setup a show override) but it doesn't show up in the Show/DJ On-Air widget

**Comment by tonyzeoli** [comment]
Okay, thanks for letting us know. We'll look into this this week and provide a fix in the next update.

**Comment by majick777** [comment]
@miklsnews Have not been able to reproduce this issue yet. Override seems to take over fine in the widget. There was a bug with failing 00 minute value saving (Issue #29 which has been fixed for next release) ... can you confirm whether this was the cause of your issue also or not?

**Comment by miklsnews** [comment]
@majick777 your correct it was issue #29 and looking forward to the next bug fix in the next release ty

**Comment by majick777** [comment]
@miklsnews great! latest release has been pushed to Github but may not be on SVN until tomorrow so feel free to get it from here.

**Comment by tonyzeoli** [comment]
I'm inadvertently without my laptop charger today. Traveling on South Carolina. Will be back at my desk in North Carolina Tuesday night EST and will push this after testing.
