### ISSUE TITLE
[Freemius] Update Freemius library to 2.4.1

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#280]
**Is your developer task related to a problem or a requirement? Please describe.**

One or more plugins you have commit access to have been flagged as using an out-of-date version of the Freemius library. This library has been recently updated with security patches and it is crucial that you update your plugin(s) by the end of 2020 to use its latest version (currently v2.4.1, or later).

**Describe the solution you'd like**

Update freemius.

**Comment by majick777** [comment]
Updated Freemius library to 2.4.1 in development version.
