### ISSUE TITLE
[Show Posts] Links to related show no longer work

### ISSUE THREAD

**Issue by gusaus** [netmix/radio-station#282]
**Describe the bug**
I've updated all plugins to the latest release and the links to related show no longer work. 

For instance, assigning this post to show 2 - 

<img width="1273" alt="Edit Post ‹ OpenProducer — WordPress 2020-11-19 12-09-58" src="https://user-images.githubusercontent.com/113996/99719204-e14bcb80-2a60-11eb-9c2b-019ef771d1cc.png">

This link does not reference the show - 
![Aliquet etiam rutrum viverra tincidunt habitant vestibulum sed placerat lacinia nibh – OpenProducer 2020-11-19 12-16-59](https://user-images.githubusercontent.com/113996/99719517-3daeeb00-2a61-11eb-8e11-b998c460562c.png)

see - https://test-openproducer-platform.pantheonsite.io/music/aliquet-etiam-rutrum-viverra-tincidunt-habitant-vestibulum-sed-placerat-lacinia-nibh/#show-posts

Posts that have not been updated still work, but they break if the post is updated - 
https://test-openproducer-platform.pantheonsite.io/music/a-ligula-nascetur-neque-blandit-sed-sem/

**Expected behavior**
Posts that have not been updated or re-assigned still work as expected (until they are updated) -
https://test-openproducer-platform.pantheonsite.io/music/a-collection-of-podcasts-embedded-with-jetpack-podcast-player-block/
<img width="1245" alt="A collection of podcasts embedded with Jetpack Podcast Player Block – OpenProducer 2020-11-19 14-18-35" src="https://user-images.githubusercontent.com/113996/99731084-3f34df00-2a72-11eb-9036-1ac5be2309b0.png">

**Additional context**
This might have to do with Newspack or some of the plugins that are listed here - 
https://github.com/OpenProducer/openproducer-platform/wiki/Platform#newspack

This is a followup to https://github.com/OpenProducer/openproducer-platform/issues/9#issuecomment-730617242

**Comment by gusaus** [comment]
I did a fresh install with only Radio Station plugin + the Make theme. Still get the same broken link when assigning a post to a show. Not sure if this warning has anything to do with the issue?

<img width="1142" alt="And yet another test post – Radio Station plugin 2020-11-19 16-28-35" src="https://user-images.githubusercontent.com/113996/99740694-5086e700-2a84-11eb-91ae-7c8cff14ffa8.png">

**Comment by tonyzeoli** [comment]
@gusaus I just tested on radiostationdemo.com.

1. Updated a post, saved, and appears on Show 3s page
2. Changed the target show to Show 2
3. Checked the post and it now falls under the target show of Show 2 and the link to the post works.

So, I'm not sure what your issue is. It could be something to do with additional post type plugin you might have installed. Not sure thought.

I'm going to leave Test Post 3 assigned to Show 2 on the demo site after it was updated with the last line at the bottom and you can see it's working. And, I'm using the Make Theme for this site, so I would rule that out.

**Comment by gusaus** [comment]
So I deleted all the plugins aside from Radio Station and did another clean install. 

1. created a couple shows - https://radio-openproducer-platform.pantheonsite.io/shows/
2. created a couple posts and associated each with a show - https://radio-openproducer-platform.pantheonsite.io/category/posts/

The links for each are still not working as referenced in https://github.com/netmix/radio-station/issues/282#issuecomment-730722927

So this message that appears is unrelated?
Warning: trim() expects parameter 1 to be string, array given in /code/wp-includes/class-wp-meta-query.php on line 695

**Comment by gusaus** [comment]
@tonyzeoli Seems like you're experiencing a similar issue on radiostationdemo.com

http://radiostationdemo.com/show-3-test-post/ is not linking to show 3 - actually reads 'All Posts for Show Hello world!' and links to http://radiostationdemo.com/hello-world/#show-posts, and not http://radiostationdemo.com/show/show-2/

**Comment by tonyzeoli** [comment]
I know it's not, because like I said, it's linking to Show 2 temporarily so
you can see that I was able to update and then relink to another show.

**Comment by gusaus** [comment]
I meant to say show 2 - test the link on http://radiostationdemo.com/show-3-test-post/

<img width="1274" alt="Show 3 Test Post – Radio Station Plugin Demo Site 2020-11-19 20-06-24" src="https://user-images.githubusercontent.com/113996/99756863-ed587d00-2aa2-11eb-8cfe-e1b8707c3f11.png">

**Comment by majick777** [comment]
@gusaud @toneyzeoli Seems like an unhandled consequence of allowing a Post to be related to multiple Shows... I will have to update it so it lists all the Shows it is related to and change the text accordingly.

**Comment by gusaus** [comment]
Thanks @majick777 - So you were able to verify the error also occurs when associating a post to just one show (as opposed to reassigning from one to another) or just updating an existing post?

**Comment by majick777** [comment]
@gusaus I didn't really test that before making the changes, but all seems working now. This has been added to the develop branch for inclusion in next release. Feel free to test it out and report if there is any further strangeness. 
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by gusaus** [comment]
@majick777 I'm testing develop and the link(s) to related show work when assigning or reassigning a post. If you 'unassign' a post, the "More Post for Show" followed by a link to the post still exists. Might be an edge case...
<img width="1206" alt="A ligula nascetur neque blandit sed sem – OpenProducer 2020-11-24 11-32-27" src="https://user-images.githubusercontent.com/113996/100142563-f356b100-2e48-11eb-9a5c-f74cd1204626.png">

**Comment by majick777** [comment]
@gusaus Good pickup! Yes there was something allowing a zero value to save, which was then getting the current post. I have added code to develop branch prevent that in future and ignore it if present.
