### ISSUE TITLE
Related shows - show random stuff and doesn't link

### ISSUE THREAD

**Issue by anigwei** [netmix/radio-station#286]
Hi,

I have a show set called "Peluts". Its permalink is: https://www.iscle359fm.cat/?show=peluts

On this permalink, it shows correctly related posts.

This is the related post: https://www.iscle359fm.cat/?p=180

But on the opposite direction, the post doesn't show a correct related show information. It shows random stuff and an invalid URL:

It shows: ← "All Entrades for Show Benvinguts" (Show "Benvinguts" doesn't exists) and its URL is incorrect and brings to 404.

Thanks!

**Comment by tonyzeoli** [comment]
@anigwei we had a report of an error on this function from another user outside of Github and I believe this is resolved in the latest development version that we are about to release. 

Please see the instructions on how to download and test with the development version here: https://netmix.com/radio-station/docs/faq/ to see if that solves your issue. I'll keep this open until we hear back.

**Comment by anigwei** [comment]
@tonyzeoli thanks.

I tried development version: Now it works fine!

I will leave it as it is now (development). When it passes to stable, will I get further updates (via wordpress itself) or I should switch back to stable in that moment?

Thanks,

**Comment by tonyzeoli** [comment]
You should be able to just upgrade when we push the new release. The notification will appear as usual in the plugin dashboard.

**Comment by anigwei** [comment]
Thanks @tonyzeoli .

So we can close issue.

Regards!
