### ISSUE TITLE
[Translation] Catalan version of plugin needs updating

### ISSUE THREAD

**Issue by anigwei** [netmix/radio-station#287]
Hi,

I've just realized that plugin is available in Catalan language. (I surely would helped in its translation as I always do but it's already done :).

Having my Wordpress entirely in Catalan, plugin appears in english.

So frontend public strings appears in english: https://www.iscle359fm.cat/?show=peluts#show-posts

(Show times, About the show, etc).

On languages folder, there is a radio-station-ca.mo and .po files. In languages.json it is correctly defined: {"language":"ca","english_name":"Catalan","native_name":"Catal\u00e0"}

Where I should look at?

Thanks,

**Comment by tonyzeoli** [comment]
it may be that those terms don't even have a translation yet. Here's the Catalan language entry on the translation page at WordPress.org: https://translate.wordpress.org/locale/ca/default/wp-plugins/radio-station/

You'll see that there are 533 untranslated strings. For example, Show does not have a translation. So, I would start there and contribute, if you can, to the translation file which will improve for you and for all that need an update for that language.

If you can help with that, when PRO is released, I'll send you a coupon code to download for free for one year. Should be released next year in late January.

**Comment by anigwei** [comment]
Thanks @tonyzeoli you are right... sorry.

 Translated (73) • Untranslated (503) 

There is still work to do. Of course I'll contribute.

Regards.

**Comment by tonyzeoli** [comment]
@anigwei Thank you with gratitude for your contribution. Please let me know when it's completed and we'll add the files. I'll push them in a future release. I can hold til Monday of next week the version 2.3.3.6 until the .mo and .po files are included. I'll reopen this ticket, so please return to this ticket and add the po and mo files and I'll include them.

**Comment by tonyzeoli** [comment]
Looks like this ticket is dormant and the requestor may have already completed the translation on their own. Closing.
