### ISSUE TITLE
[Schedule Table View] Display only Rows With Shows

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#289]
**Is your feature request related to a problem? Please describe.**
A user on the WordPress support forums asked if we can display rows that only have shows. 

**Describe the solution you'd like**
For example, if they only air shows from 6 pm to 12 midnight, then 1 am to 5 pm do not display on the master calendar. Or, if they have shows from 1 to 2 pm and 9 to 12 pm, then only those rows display.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by majick777** [comment]
@tonyzeoli I think this request is going outside scope of what we can provide in support. As mentioned to the user they can hide specific hour rows as desired on the Schedule Table View already via CSS... (or just use the Tab View where there are no empty rows.) Attempting to do this automatically is going to be very difficult and cause a potential mess so I don't think it would be a reliable display.

**Comment by tonyzeoli** [comment]
Closing this. No longer necessary.
