### ISSUE TITLE
Schedule Override does not retain :00 minutes in start and end times (v 2.2.2)

### ISSUE THREAD

**Issue by montereyjeff** [netmix/radio-station#29]
**Describe the bug**
Schedule Override does not retain minutes entered as 00. Minutes entered as 01 and 02 are retained.

**To Reproduce**
1. Go to Schedule Override and either add a new one or update an existing one
2. For the times, enter any hour, 00 minutes, am.
3. Click Publish/Update

**Expected behavior**
Many programs begin/end on the hour, so 00 minutes are important.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
v 2.2.2

**Comment by majick777** [comment]
@montereyjeff Good pickup. Found the issue in newly added value save sanitization. Added to next release.
