### ISSUE TITLE
[Schedule Overrides] Starting or ending at 12noon causing output of shows they are meant to override

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#290]
I am using Developer Version 2.3.3.6, I also noticed this in Developer (hotfix) Version 2.3.3.5.

**Describe the bug**
When adding in a schedule override for shows that start or finish at 12pm (12noon), there is a conflict that is not thrown in the wp-admin, but instead results in a strange behaviour in output.  I can't really explain what is happening here, but i will try and do my best via pictures.

**To Reproduce**
This is user reported to me, and I have tested it and re-created the issue like this.
1. On a day schedule, set a schedule override to start at any time but end at 12pm.

![image](https://user-images.githubusercontent.com/67294458/101330835-00bd6380-386b-11eb-9ed0-00d8f341b31f.png)

2. Then set another schedule override to start at 12pm.

![image](https://user-images.githubusercontent.com/67294458/101330869-0dda5280-386b-11eb-89f6-c357d5b21d82.png)

3. You will notice in the output that the show that was meant to be overridden in the between the overrides still displays.

<img width="689" alt="Screenshot 2020-12-07 at 09 01 59" src="https://user-images.githubusercontent.com/67294458/101330999-3e21f100-386b-11eb-954f-01e00b80a769.png">

4. You can then try to create more overrides with that start directly after the conflicting ones starting at 12, and they do not display.  You can see this resulting behaviour in further screenshots below.

The issue seems related to the 12pm setting.

**Expected behavior**
As there is no conflict here with the overrides themselves, and no errors thrown out, this should display correctly on output as normal.

**Screenshots**
Here are more examples (created by the end user).
In this example you can see the same thing as above happening but also you have the additional issue where the show over-ride 2-6pm (Saturday Sport) does not even display. Presumably because of the bug between 12noon start show, the Retro Show.

<img width="1272" alt="Screenshot 2020-12-07 at 08 39 12" src="https://user-images.githubusercontent.com/67294458/101331113-6b6e9f00-386b-11eb-98f3-0a8af7f38691.png">
<img width="555" alt="Screenshot 2020-12-07 at 08 39 33" src="https://user-images.githubusercontent.com/67294458/101331119-6e698f80-386b-11eb-9a38-aa96824cbfc3.png">

**Desktop (please complete the following information):**
Trialled on Windows Firefox, Edge, and Mac OS X Safari, Firefox and Chrome.

**Smartphone (please complete the following information):**
Appears the same on smartphone devices.

**Additional context**
I hope i've explained myself well enough here, i've included the override wp-admin shots too.
If there are any white blobs, that is snow from a snow effect on the site. I have disabled to try and see if that is a conflict but it is not.

**Comment by tonyzeoli** [comment]
@majick777 if you can pick this one up and investigate. Thanks for reporting, @astevens93.

**Comment by majick777** [comment]
@astephens93 This is very strange... No luck reproducing this locally so far. I've put in an entire Show and Override schedule for Saturday matching the one in the screenshot, and everything displayed as expected with the Overrides in the correct times, and the Shows being overridden are not displayed. 

If you can provide me with a link where this is happening I may be able to investigate using the schedule debug mode, there may be enough information there to see what is/isn't happening... I recognize this may not be easy since you've modified it as you want the Schedule to be displayed properly in the meantime, but if you could activate the conflicting Show shifts and Overrides temporarily and then go to `/wp-json/radio/schedule/?rs-debug=1` you can copy and paste that here and then deactivate them again.

**Comment by astevens93** [comment]
Hi @majick777 thanks for testing and coming back to me. Very strange you cannot replicate.
Attached is a debug file
[debug_schedule_111220.txt](https://github.com/netmix/radio-station/files/5679134/debug_schedule_111220.txt)

I've enabled the schedule overrides for you and you can see it live here - https://www.hcrfm.co.uk/on-air/schedule/ for Saturday 12th December (but of course this will be tomorrow!)

If you wanted to poke about in the wp-admin I have your email from previous conversations so I can ping that over and keep conversations public here, but credentials private.

![image](https://user-images.githubusercontent.com/67294458/101904306-8c0d6080-3bad-11eb-971c-6a4449f28b2a.png)

**Comment by majick777** [comment]
@astephens93 Thanks for the debug info, it has lead me to what was happening here... 

First, at some point I had added some code for efficiency to remove the overrides as they were being added - this prevented them from being applied to more than one shift that they overlapped! So I overdid that one and I have removed that now.

And second, I have ordered the schedule overrides by time for each day before being applied to ensure that when applied more than once they affect shifts in the correct order. 

Added to develop branch for 2.3.3.7 release.

**Comment by astevens93** [comment]
Hi @majick777 I appreciate you looking into this and finding the solution. However, I've just installed and activated Version 2.3.3.7 as requested, and set up new schedule overrides matching my previous ones for this coming Saturday 19th December and I still get the same output on the front-end of the website.

https://www.hcrfm.co.uk/on-air/schedule/

Debug file attached.
[debug-schedule-171220.txt](https://github.com/netmix/radio-station/files/5707732/debug-schedule-171220.txt)

Is there anything I'm missing?  Have I installed the correct dev version where this was fixed?

Thanks in advance.

**Comment by majick777** [comment]
@astevens93 Yes I can see that didn't quite do that trick. Strange that it worked for me... I will have to have another go at it...

**Comment by majick777** [comment]
@astevens93 Okay, I think I have it this time, without going into too much detail, because of the nested loop here of Shows -> Overrides -> Shifts, the updated Shifts due to overrides being applied were only being set to the final Shows variable in the loop and the Shifts one also. 

In effect, that meant only one Overrides affecting a Show was being applied, and multiple ones ignored. So Shift were being trimmed but the remainder not being removed by a second Override affecting it.

**Comment by tonyzeoli** [comment]
@majick777 Thanks for resolving. Good working that out. I'm sure it's a bit complex.

**Comment by majick777** [comment]
@tonyzeoli Definitely frazzled my brain a bit trying to work out what was wrong with the logic conditions, it took a bit of delving in and testing to find out they weren't the problem after all, lol.

**Comment by astevens93** [comment]
Amazing thank you so much @majick777 !  It now works perfectly.  Good work as always, thanks for persevering.  This would have been a hard one to spot, so appreciate it.

**Comment by astevens93** [comment]
Hi @majick777 @tonyzeoli looks like the problem might be back, but affecting the 12am shift times.  I know my previous issue example was 12pm, so I can only assume the issue is still there but just for 12am shifts.

See below screen grabs of the show schedule overrides where we are overriding a show shift that ends at 12am.

Thur 24th is the concern here - https://www.hcrfm.co.uk/on-air/schedule/

Debug file attached.
[schedule_debug_211220.txt](https://github.com/netmix/radio-station/files/5723627/schedule_debug_211220.txt)

Screengrabs of the shift schedule below.

<img width="1245" alt="Screenshot 2020-12-21 at 09 55 00" src="https://user-images.githubusercontent.com/67294458/102764433-09d22880-4373-11eb-88a3-282bfca6a1f6.png">
<img width="704" alt="Screenshot 2020-12-21 at 09 55 16" src="https://user-images.githubusercontent.com/67294458/102764459-13f42700-4373-11eb-8ac2-b43680d9c6e9.png">

**Comment by tonyzeoli** [comment]
@astevens93 Okay, I'm sure Tony Hayes will take a look shortly. Thanks for letting us know.

**Comment by tonyzeoli** [comment]
@majick777 I've added this to 2.3.3.8 instead of 2.3.4, given it's a bug and will need to be released prior to a more major version.

**Comment by majick777** [comment]
@astevens93 Sorry for the delay on this one, I have made some tweaks to the code which seemed to fix the issue in my testing, can you try the latest version and see if it solves the problem and report back (with a new debug info if not.) We'd like to have this fixed for the 2.3.3.8 release.

**Comment by astevens93** [comment]
Thanks @majick777 - I've downloaded the latest and done some tests.

You can see here I have set these 2 overrides (as random shows)

![image](https://user-images.githubusercontent.com/67294458/107648802-a4b0fa00-6c74-11eb-85b3-2c55d3c94dc7.png)

The output is this

![image](https://user-images.githubusercontent.com/67294458/107648824-ac709e80-6c74-11eb-822e-08dea7e3289c.png)

Where the earlier show appears in the list after the later show.

The debug file for this scenario is here
[debug-1.txt](https://github.com/netmix/radio-station/files/5966093/debug-1.txt)

**there was also another issue i found - on the same subject** where if I did a test from 9am through to 11.30pm 

![image](https://user-images.githubusercontent.com/67294458/107649131-0cffdb80-6c75-11eb-8cf7-e02d8db05616.png)

It would again position them in the list in the wrong order, but also ignore a particular show that was already an over-ride (in this example you can see)

![image](https://user-images.githubusercontent.com/67294458/107648962-db871000-6c74-11eb-9a76-4b5d683520cc.png)

The debug file for this particular issue is here: 
[debug-2.txt](https://github.com/netmix/radio-station/files/5966083/debug-2.txt)

**So from what i can gather**
The overrides are now now functioning as they should, but the listing of them is in reverse (i.e the earlier override is coming later in the list)

But when you add in a third over-ride that another override spans, then it still outputs.  I think I referenced this issue here in #312 and is probably solved with a logic check.

**Comment by majick777** [comment]
@astevens93 Okay, let's try that again... I have just moved the code block that adds the override to before the sorting is done, and that seems to have fixed this for me (conflict checker aside.) Again, test develop branch, hopefully that sorts this one out..?

**Comment by astevens93** [comment]
Thanks @majick777 this has fixed it for me too!    I can close this issue now it's fixed in the latest development branch.  Nice one!
