### ISSUE TITLE
Warning: Invalid argument supplied for foreach() in on line 1874

### ISSUE THREAD

**Issue by cbeattie89** [netmix/radio-station#292]
Hi everybody. I'm getting this error at the top of all my posts which aren't tagged with a related show, just below the title:

Warning: Invalid argument supplied for foreach() in wp-content/plugins/radio-station/radio-station.php on line 1874

Looking at the code, this line appears to be a new addition to 2.3.3.6. that removes possible zero values by unsetting the $related_show variable. Unfortunately, that's about the extent of my PHP knowledge.

I've rolled back to 2.3.3.5 for now and everything seems to be working again, but just wanted to give the heads up in case anyone else had this problem.

**Comment by tonyzeoli** [comment]
@cbeattie89 Thanks for the report. I just tried to view our test post that is not related to a show on our radiostationdemo.com site and can't replicate the error. See: https://radiostationdemo.com/show-post-test/

We'll look into it though.

**Comment by cbeattie89** [comment]
Thanks for looking into it. Let me try to get some more debug info for you over the weekend. Everyone was panicking today, so we didn't have much time to look deeply into the configuration before we rolled back.

**Comment by majick777** [comment]
@cbeattie89 Thanks for the report, yes this fix needed an extra check before the `foreach` loop.
Added to develop branch for 2.3.3.7 release.

If you want to keep WordPress debug mode on but don't want to see debug errors on your live site, I suggest you change your `wp-config.php` to reflect that. eg:
`define('WP_DEBUG', true); define('WP_DEBUG_DISPLAY', false);`
