### ISSUE TITLE
[Conflict Checker] Single Show conflicts with itself

### ISSUE THREAD

**Issue by RimantasMurza** [netmix/radio-station#295]
Good day, folks,
trying out the plugin, still haven't migrated to it and I am baffled by the notification, that my shifts are conflicting. I now have one show added. When I add a shift for it, it goes red and says it conflicts with _this show!_. It definitely is the only show in the system and there is only one shift. Am I missing something?
![image](https://user-images.githubusercontent.com/71840129/102021877-a866f400-3d8b-11eb-9e9f-24fc51a401e7.png)

![image](https://user-images.githubusercontent.com/71840129/102021881-b7e63d00-3d8b-11eb-97ae-b7c919bd8f1d.png)

**Comment by RimantasMurza** [comment]
I have tried removing the shift, updating the show - still the same.

**Comment by tonyzeoli** [comment]
@RimantasMurza youre the first to report this. What version number of the plugin are you using?

**Comment by RimantasMurza** [comment]
Good day Tony,
I am using the newest, v2.3.3.6 one. I have just tried to delete the show, remove it from the trash section and add a completely new one, same time, just to test it out - same result! 

![image](https://user-images.githubusercontent.com/71840129/102360851-37a61e80-3fbb-11eb-8208-b9b072991cdc.png)

**Comment by tonyzeoli** [comment]
Okay, thanks for this. Can you clear your website cookie and cache and try
again? We're taking a look at this shortly and appreciate your patience.

**Comment by tonyzeoli** [comment]
i just set up a clean install on a dev server and installed 2.3.3.6 with WP 5.6 and PHP 7.4 with no shows added and no other plugins active. I added a show, published, and set a time and had no issue with what you describe as happening

I suggest you check the version of WordPress and make sure you're on the latest version, 5.6. Make sure you're running the latest version of PHP (7.4) and that you have no other plugins turned on.

![Screen Shot 2020-12-16 at 3 03 37 PM](https://user-images.githubusercontent.com/4053819/102400920-87cbb380-3fb0-11eb-9e8b-aeb85bfabf9e.png)

**Comment by majick777** [comment]
@RimantasMurza This could be due to the fact that the shift checker checks against the last shift in the weekly schedule as that can span between this week and the next week. Some code was recently added to prevent a shift from checking against itself (#281) but something may be slipping still through the logic there.

If you can provide us with your timezone and start of week settings from the plugin and/or WordPress, it may help in reproducing this issue locally and finding a solution.

**Comment by majick777** [comment]
@RimantasMurza As we haven't heard back from you and were unable to reproduce the issue on a fresh install, I am going to close this issue. If you are still experiencing the issue please provide the information requested so that we can reopen and attempt to reproduce it.
