### ISSUE TITLE
PHP error in server Log

### ISSUE THREAD

**Issue by Hotrodradio** [netmix/radio-station#296]
**Describe the bug**

[Wed Dec 16 00:24:09.476748 2020] [proxy_fcgi:error] [pid 32165:tid 139900990568192] [client 2001:1c00:1412:be00:d16f:f15d:60b7:141e:58105] AH01071: Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in /home/hotrod/domains/hotrodradio.nl/public_html/wp-content/plugins/radio-station/radio-station.php on line 1874PHP

**Expected behavior**
There is no visible error in the website

**Screenshots**
![Knipsel](https://user-images.githubusercontent.com/63542085/102334530-0e6f9900-3f8f-11eb-9c1d-7ec2ce22dc75.PNG)

I don't know if this affects our bandwith, but it has already doubled.

Regards HotrodRadio

**Comment by tonyzeoli** [comment]
@Hotrodradio Okay, thanks for reporting this. We'll get on this asap. @majick777 will take a look shortly.

**Comment by majick777** [comment]
Duplicate issue to #282, this has been fixed in develop version for pending 2.3.3.7 release. 

If you wish to install the development version earlier and not see these errors: 
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing
