### ISSUE TITLE
[API] Add Show description to the API

### ISSUE THREAD

**Issue by anigwei** [netmix/radio-station#299]
Hi!

I created a small app (for Android) for our station. Only shows rss feeds from webpage, mp3 streaming and current and next show thanks to radio-station great API!

But I'm missing a "show_description" item, so people can have quickly more information about the current or future show. Would be a great feature.

Best regards,

**Comment by tonyzeoli** [comment]
I just checked the API and you're correct, it seems as if we left out the show description. We'll take a look and see if we can add in the coming weeks.

**Comment by anigwei** [comment]
that's nice @tonyzeoli.
 
Cheers.

**Comment by tonyzeoli** [comment]
@majick777 we got this requesrt to add the show description to the API.

**Comment by majick777** [comment]
@anigwei Good suggestion. The reason it wasn't added in the first place was to keep the amount of data smaller for generic requests. I'd like to keep that to be the case, however, what I can do is add it to the Shows endpoint where a Show ID (or number of shows) is specified in the request querystring. eg.

https://radiostationdemo.com/wp-json/radio/shows/?show=1
https://radiostationdemo.com/wp-json/radio/shows/?show=1,2,3

This means the data is available on demand, but would require a possibly separate API call to retrieve the Desctription/Excerpt. 

Note if you want to add further Show data to all endpoints yourself, you can use the filter `radio_station_shows_data` (see function `radio_station_get_shows_data` in `data-feeds.php`)

Added to development version for 2.3.3.8 release.
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing
