### ISSUE TITLE
Fix Playlist Entries Custom Field extends beyond the post editor

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#3]
The playlist creator extends beyond the post editor body and impacts the sidebar. Needs to be reworked so that it doesn't affect the sidebar.

**Comment by majick777** [comment]
Resolved for Show metabox but still pending for Playlist tracks metabox.

**Comment by tonyzeoli** [comment]
Okay, thanks. Following.

**Comment by majick777** [comment]
Ok I fixed this for now by splitting each row into to and added this to latest release. Closing this one, we can revisit with minor display improvements in the future.
