### ISSUE TITLE
[Schedule Overrides] Full day overrides not working as expected

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#300]
**Describe the bug**
When I add a new schedule override for a particular hour it shows up at the end of the schedule rather than in the correct location based on the time (This is also an issue when looking at the coming up shortcode

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Schedule Overrides'
2. Add the Schedule overide
3. Go to the Schedule

**Expected behavior**
I would expect the show overide to show up in the correct location

**Screenshots**
![image](https://user-images.githubusercontent.com/77554122/104823969-12b8fb80-5846-11eb-807d-c104583726c7.png)
![image](https://user-images.githubusercontent.com/77554122/104823998-472cb780-5846-11eb-9097-c9ef45ad1aa0.png)

**Desktop (please complete the following information):**
 - OS: [All]
 - Browser [All]
 - Version [2.3.3.7]

**Smartphone (please complete the following information):**
 - Device: [All]
 - OS: [All]
 - Browser [All]
 - Version [2.3.3.7]

**Comment by astevens93** [comment]
Hi @kairandles - I have a similar issue open with #290 and it is being worked on by, linking it as reference for you to see.

**Comment by kairandles** [comment]
Ah sorry, I couldn't see it reported anywhere! Thanks for the quick response to this!

**Comment by kairandles** [comment]
Hey @astevens93 is this your website? https://www.hcrfm.co.uk/on-air/schedule/?
Would I be able to ask a couple of questions about how you setup the schedule on it?

**Comment by kairandles** [comment]
UPDATE TO THE ISSUE - This only seems to occur when there is a show set for the whole day, when just interrupting shows it shows up fine in the schedule

**Comment by majick777** [comment]
@kairandles Thanks for finding this, I actually never thought to test full day Overrides. I will check it out.

**Comment by majick777** [comment]
As noted in #302, this issue is for multiple days not just whole single days.

**Comment by majick777** [comment]
@kairandles @tonyzeoli Found the issue, which was when an Override had the same start/end time (eg. 12:00 am), the code was not changing the end time (adding 24 hours in seconds.) This points to similar throughout the codebase when checking shift/override times, which has also been updated.
