### ISSUE TITLE
[Schedule Overrides] Add Show fields to match Show post type

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#301]
**Is your developer task related to a problem or a requirement? Please describe.**
I'm always frustrated when I can't add a user as a host on a schedule overide

**Describe the solution you'd like**
I would like the same options as when adding a new show in terms of adding the show email, phone and DJ / Host and Show Producer(s)

**Describe alternatives you've considered**
I am currently just adding 'with [DJ Name] in the title box however having the DJ / Hosts etc options look way better both in the schedule and the now playing widgets 

**Additional context**
This is the option box that I would like available to the schedule overrides
![image](https://user-images.githubusercontent.com/77554122/104824092-e8b40900-5846-11eb-9cf4-6af9d1397474.png)
Rather than just the override schedule
![image](https://user-images.githubusercontent.com/77554122/104824112-16994d80-5847-11eb-8160-deefef0c79d8.png)

**Comment by majick777** [comment]
@kairandles Yeah I agree, Shows and Overrides have been a bit divergent in usage in the past, but over time they have been coming back closer to doing a very similar thing, so it would be nice to have these fields matching on this front.

**Comment by tonyzeoli** [comment]
@majick777 Does this seem like sometihng we can put off until after PRO launches and then we can come back to it?

**Comment by majick777** [comment]
@kairandles Have combined this issue with #249 to come up with Schedule Overrides that can now be linked to an existing Show. Individual field overrides can be toggled from the Override edit screen so that any combination of data can be used from the Show or Override. :-) 

Included in development version for next release.
