### ISSUE TITLE
Adding the ability to change the permalink directory on shows and overrides etc

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#303]
**Is your developer task related to a problem or a requirement? Please describe.**
Adding the ability to change the permalink directory on shows and overrides etc

**Describe the solution you'd like**
Adding the ability to change the permalink directory on shows and overrides etc I ideally would have the shows changed to '/regular-shows/' and '/one-off-shows/'

**Describe alternatives you've considered**
Digging into the code however I think it's set that way in multiple places so I wasn't able to change the permalinks

**Additional context**
![image](https://user-images.githubusercontent.com/77554122/104824255-07ff6600-5848-11eb-8edc-883ead215ed0.png)
![image](https://user-images.githubusercontent.com/77554122/104824263-1483be80-5848-11eb-9952-1354b5436993.png)

**Comment by majick777** [comment]
@kairandles You will need to filter the post types as they are being registered in order to do this, eg:

    add_filter( 'radio_station_post_type_show', 'custom_show_rewrite_slug' );
    function custom_show_rewrite_slug( $post_type ) {
        $post_type['rewrite']['slug'] = 'regular-shows';
        return $post_type;
    }

and similar for Overrides using the `radio_station_post_type_override` filter. Then save your Permalinks for the Settings -> Permalinks admin page to flush the rewrite rules.
