### ISSUE TITLE
[Plugin Settings] Add a default email address similar to the default phone number

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#304]
**Is your developer task related to a problem or a requirement? Please describe.**
The ability to add a default email address similar to the default phone number

**Describe the solution you'd like**
The ability to add a default email address similar to the default phone number

**Describe alternatives you've considered**
I currently am adding the email to each of the shows individually but would be good to see the default option added!

**Additional context**
![image](https://user-images.githubusercontent.com/77554122/104824417-709b1280-5849-11eb-934b-344d7d097ff8.png)

**Comment by majick777** [comment]
@kairandles Thanks for the suggestion, this is an easy one. 
Added to development version for 2.3.3.8 release.

**Comment by kairandles** [comment]
@majick777 great thanks!
