### ISSUE TITLE
[Tabbed Schedule] Date Selector

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#309]
**Is your feature request related to a problem? Please describe.**
A simple date selector added to view the week's schedules ahead

**Describe the solution you'd like**
Adding the date selector to the top right tabs

**Describe alternatives you've considered**
Not viewing into the future more than 6 days

**Additional context**
![image](https://user-images.githubusercontent.com/77554122/104967486-63159200-59db-11eb-89b4-e9b0a3d60fe9.png)
![image](https://user-images.githubusercontent.com/77554122/104967500-6ad53680-59db-11eb-9db8-7f5e9de24eeb.png)

**Comment by tonyzeoli** [comment]
@kairandles This will be in PRO, so I'm going to close this here, because it's not going to be added to the free version. We have a PRO repo that's hidden from the public, which you can't see, but trust me - it's there.

**Comment by majick777** [comment]
@kairandles Just to be clearer on this, we will have a Calendar View in the Pro version of the plugin. Over time we have been updating the code so it can now handle generating a schedule for a particular date (this was trickier than you would imagine.)

So an in-between solution would be to have an arrow to load the next week on Table/Tab view (and consequently, previous week also)... and this would bring us a step closer to the Calendar View. What do you think @tonyzeoli? I think this could make sense...

**Comment by kairandles** [comment]
Ahhh this would be amazing if it could be implemented soon!! Only note with it that I'm sure you will think of is the ability to jump back to 'today' as well as forward (and back if your already a week ahead)

**Comment by tonyzeoli** [comment]
@majick777 I would say that if adding that feature took any time away from just building it the way we want it, to wait until we have it completed in full. @kairandles is going to start broadcasting in December, so I would think we have some time to resolve his needs and build the tool we want and not have the interim step. With all the other things we have on our plate, it may make sense to just build it the right way and not insert some step if that take up an inordinate amount of time and away from other priorities. I think everyone is going to want this in PRO, so it makes sense to just do it right the first time. What do you think?
