### ISSUE TITLE
[Directory] Station Listing does not display if Genres are not selected

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#311]
**Describe the bug**

When loading the Netmix Directory on the Netmix home page, HCRFM.co.uk is not displaying in the directory. It does display when you add the string to the URL to see the sticky footer player. Alex Stephens seems to think it has something to do with not adding genres.

**To Reproduce**
1. Go to Netmix.com and view the directory as intended
2. Add the string and view the directory again with the string appended and you'll then see Huntington Community Radio appear, but maybe only after refresh one time.

**Expected behavior**

Not sure if this is intended or not, but thinking that even if the station does not choose a genre, maybe it should display? It would be hard to filter station's by genre then if they don't list themselves and selecting a genre would then filter out a station with no genres anyway, so it may never be found. Maybe there's some sort of warning that if they do add themselves to the directory and don't add genres, then there's a notification that tells them their station listing is not complete. How that happens, I'm not sure and we should discuss.

**Screenshots**

**Desktop (please complete the following information):**
 - mac OS
 - Chrome
 - Version: 88.0.4324.96

**Additional context**

Get with Alex Stephens on this if possible. Thanks.

**Comment by astevens93** [comment]
Thanks for adding @tonyzeoli 

To help explain I've added this short screen recording.

You can see here on initial load of netmix.com, it is only showing stations with a genre on their shows. You then have to expand the Genre selector, click All Genres, and then it displays all stations regardless of genres selected.

I probably need to get around to adding genres to the shows on our site!

https://user-images.githubusercontent.com/67294458/105525844-82613780-5cd9-11eb-846c-20b88f5c280a.mov

**Comment by majick777** [comment]
@astevens93 You are quite right, I noticed the same thing last week. There was a bug in the Genre selection where is was not handling the case of not having Genres correctly. I have fixed this (and a few other things) in the next Directory version (which is a running beta) ... by adding a "No Genre" pseudo-term which is selected by default, so that all the Stations show initially. I will push the updated version live in the next day or so.

**Comment by majick777** [comment]
@astevens93 @tonyzeoli Okay I pushed the next version of the Directory so this should be fixed along with a bunch of other things. Feel free to check it out and open any new issues you find with it. Seems to all be working well from my testing but there is always chance for error,  and especially browser display conflicts.
