### ISSUE TITLE
Set readme stable tag to version number

### ISSUE THREAD

**Issue by michaeltorbert** [netmix/radio-station#314]
**Is your developer task related to a problem or a requirement? Please describe.**
The readme stable tag is currently trunk, but needs to be the latest stable version, corresponding to a directory in tags/ on wordpress.org. 
By using trunk, this also breaks wp.org translations. 
This should be updated each time.

**Describe the solution you'd like**
For instance, it should currently be 2.3.3.7.

**Additional context**
https://developer.wordpress.org/plugins/wordpress-org/how-your-readme-txt-works/#readmeheader-information

**Comment by tonyzeoli** [comment]
@majick777 can you work with @michaeltorbert on this, please? Thanks.

Michael saw why our translations weren't working properly and is able to issue a fix.

**Comment by tonyzeoli** [comment]
@tonyzeoli I merged this with developer myself. Yippee! This should make our translations work correctly. Thanks to @michaeltorbert for catching this.
