### ISSUE TITLE
[Widgets / Shortcodes] Add Custom 'Listen Live' Play Button to Now live Widget

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#317]
**Is your feature request related to a problem? Please describe.**
The addition of a customizable play button, (So having just a simple play symbol and custom text all the way up to uploading a custom image) I would want though the ability to make where it links to completely custom with HTML and I would need to to open my player in a popup window, onto the show that is currently live to indicate to the user an easy way to hear the show that is currently on air

**Describe the solution you'd like**
Adding the filter ability to Widgets / Shortcodes

**Describe alternatives you've considered**
Adding this CSS:

.master-schedule-tabs-panel .master-schedule-tabs-show.nowplaying div.show-info:after {
content: "On Air Now";
position: relative;
display: block;
background: #b23538;
color: #fff;
font-weight: bold;
margin-top: 10px;
margin-bottom: 10px;
width: fit-content;
width: -moz-fit-content; /* for Mozilla Firefox Compatibility */
padding: 5px 10px 5px 10px;
border-radius: 5px;
}

However, I can't add a URL to this as it's css

**Additional context**

Can the filter you created in #306 be added to Widgets / Shortcodes please!

**Comment by majick777** [comment]
Resolved in #306
