### ISSUE TITLE
[Current show on air widget]  Show avatar displayed in low resolution

### ISSUE THREAD

**Issue by GuzmanPRO** [netmix/radio-station#318]
> Bug description

I have a problem with the resolution of the avatar of my shows with the widget: Current show on air.
_View Pic. ->_

 <img src="https://ministerioarcadesalvacion.org/mas/wp-content/uploads/2021/02/Current-show-on-air-widget.jpg" alt="Current show on air widget">

With the current show on air widget the show avatar is in a perfect size but the image look blur or low resolution.
Go to: https://ministerioarcadesalvacion.org/radio/
I have tried to find a way to make the shows avatar look perfect but I have not succeeded. 

While, I have noticed that on the show page, the size and resolution are perfect.
Go to: https://ministerioarcadesalvacion.org/show/musica-seleccionada/

 <img src="https://ministerioarcadesalvacion.org/mas/wp-content/uploads/2021/02/show-page.jpg" alt="Show Page">

Please: HELP!

**Desktop
 - OS: WIN 10
 - Browser: Chrome
 - Version [88.0.4324.182]

**Additional Info:
Show Avatar resolution _500x500_

Current show on air widget setup:
 <img src="https://ministerioarcadesalvacion.org/mas/wp-content/uploads/2021/02/Screen-Shot-2021-02-22-at-4.23.31-PM.png" alt="Current show on air widget setup">

**Comment by majick777** [comment]
@GuzmanPRO The avatar default is set to the WordPress `thumbnail` size for this... Currently if you want to change this you would need to use the  `radio_station_current_show_avatar` filter. I have made a note to add an additional attribute/filter so the size can be changed more directly.
