### ISSUE TITLE
[Current Show Widget] Multiple Hosts Seperator

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#319]
**Describe the bug**
No Separator On the current show widget for multiple Hosts

**To Reproduce**
1. Add 2 or more hosts 
2. See Widget Output

**Expected behavior**
with Host 1, Host 2 and Host 3
or with Host 1 and Host 2

**Screenshots**
![image](https://user-images.githubusercontent.com/77554122/108830966-98586580-75c1-11eb-9c33-24905029a599.png)

**Additional context**

**Comment by majick777** [comment]
@kairandles Good pickup, yes there was a problem with the host count from recent changes. Added fix to develop for inclusion in next release.

**Comment by kairandles** [comment]
Thanks @majick777 :)
