### ISSUE TITLE
[Deploy] 2.3.3.8 Release

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#321]
**Is your developer task related to a problem or a requirement? Please describe.**

Deploy 2.3.3.8 release.

Check readme.txt
Check readme.md
Check stable version number and change to 2.3.3.8
Merge all changes to Master
Download Master
Remove 2.3.3.7 from repo
Add 2.3.3.8 to repo and include trunk version for past downloads section

**Describe the solution you'd like**

Deploy version 2.3.3.8

**Comment by majick777** [comment]
Just to note, there's no reason to remove 2.3.3.7, in fact we should keep all tagged versions in the repository 
(though looks like you meant remove it from the trunk directory before uploading 2.3.3.8 in which case nevermind, lol)
Checked the SVN, looks to be all good. :-D
