### ISSUE TITLE
Add post to show does not save selection or publish to show

### ISSUE THREAD

**Issue by kb808** [netmix/radio-station#323]
**Describe the bug**
When relating a post to a show, the section does not save and not applied.

**To Reproduce**
1. Edit post
2. select desired show under 'Related to Show'
3. save 
4. Selection is cleared after Save

**Expected behavior**
Posts added to Show used to display all previous shows under this section, since update all this has cleared. 

**Screenshots**
![image](https://user-images.githubusercontent.com/79828768/109461799-cbfe2880-7ab6-11eb-9507-30e67b3fa9c1.png)

**Comment by tonyzeoli** [comment]
Hi @kb808 

I just tested this on our demo site with 2.3.3.8, which is the latest version. I was able to publish a post to a show and it appeared under the Posts feature on the Show page. I cannot replicate your issue.

First, you may want to clear your browser cache and dump any host caching you have first.

Can you please disable all plugins except Radio Station and try that first. Also, switch your theme to a WordPress standard theme and try, as well.

You may have a plugin conflict of some sort.

**Comment by majick777** [comment]
@kb808 While it seems to be saving fine, I did notice on the edit post reload that the saved selection was not displayed... I have made a minor fix to the code in the development version - which seems to have fixed the issue.
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing
