### ISSUE TITLE
master schedule

### ISSUE THREAD

**Issue by Tienuz** [netmix/radio-station#329]
**view = legacy**
When i use the [master-schedule view="legacy"] the names of the days are all sunday.

**Comment by majick777** [comment]
@Tienuz Thanks for reporting. As it happens this issue has already been fixed for the next release and is included in the development version:
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by Tienuz** [comment]
Thankx for you're answer. You have created a great plugin. Love it. Can't wait for the pro version. 


Best regards, 

Martijn. 

Sent from MailDroid

-----Original Message-----
