### ISSUE TITLE
Change 1,000 users to 2,000+ users in dashboard notification

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#332]
**Is your developer task related to a problem or a requirement? Please describe.**

In the dashboard notification for asking for Patreon support, the text persists at 1,000 users when we're now at 2,000+ users.

**Describe the solution you'd like**

Update text to 2,000+

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by majick777** [comment]
So here is the message draft copy with the *added line*...

```
Help support us to make improvements, modifications and introduce new features!
With over a thousand radio station users thanks to the original plugin author Nikki Blight
since June 2019 Radio Station plugin development has been actively taken over by Netmix.
*And due to our continued update efforts, we now have over two thousand active stations!*
We invite you to **Become a Radio Station Patreon Supporter** to make it better for everyone
```

Open to other wording improvements...

**Comment by tonyzeoli** [comment]
Cool!


[image: photo]
Tony Zeoli
Founder, Digital Strategy Works LLC
O  (828) 412-0990  <(828) 412-0990> M  (917) 705-4700  <(917)
705-4700> E  ***@***.***
***@***.***>
W  https://digitalstrategyworks.com
Whatsapp 9177054700
Skype tonyzeoli
Clubhouse @tonyzeoli
<http://www.facebook.com/digitalstrategyworks>
<http://www.twitter.com/dswks>
<http://www.linkedin.com/company/digital-strategy-works>
<http://plus.google.com/digitalstrategyworks>
<http://slideshare.com/tonyzeoli> <http://about.me/tonyzeoli>
<http://angel.co/tonyzeoli>
[image: App Social Buttons Image]
<https://facebook.com/digitalstrategyworks>   [image: App Social Buttons
Image] <http://dswks>   [image: App Social Buttons Image]
<https://linkedin.com/in/+tonyzeoli>   [image: App Social Buttons Image]
<https://www.youtube.com/+digitalstrategyworks>
Schedule a Call [image: arrow] <https://calendly.com/tonyzeoli>
.
