### ISSUE TITLE
[Shows Admin] ArgumentCountError thrown

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#337]
**Describe the bug**

When click on Shows in the Radio Station admin, this error appears: 

ArgumentCountError thrown
Too few arguments to function radio_station_master_schedule_loader_js(), 0 passed in /nas/content/live/netmixpro/wp-content/plugins/radio-station-pro/includes/pro-schedule-editor.php on line 211 and exactly 1 expected

**To Reproduce**
1. Go to WordPress Dashboard Admin
2. Click on Shows under Radio Station panel
3. View error

**Expected behavior**

Can access all shows.

**Screenshots**

n/a

**Desktop (please complete the following information):**
 - OS: Mac 0S 10.5.7
 - Browser Chrome for Mac
 - Version Latest for Mac

**Smartphone (please complete the following information):**

**Additional context**

N/A

**Comment by majick777** [comment]
@tonyzeoli Good pickup, yes the shortcode attributes variable was supposed to be passed here. Fixed.
