### ISSUE TITLE
Text in tabbed view

### ISSUE THREAD

**Issue by SasiaDagnoli** [netmix/radio-station#340]
I have a problem figuring out, how i get my show description to be shown when i am in the tabbed view. Just like a short about the show, before reading more about it. 
Hope this makes sense

Thanks!

**Comment by majick777** [comment]
@SasiaDagnoli Yes to do this:
1. Untick Automatic Display on the Schedule Page in the Plugin Settings Page.
2. In the the Schedule page content use the shortcode `[master-schedule view="tabs" show_desc="1"]`

A full list of other possible shortcode attributes is available here:
https://netmix.com/radio-station/docs/Shortcodes

**Comment by SasiaDagnoli** [comment]
Thanks! But i am not sure which file you are talking about? What is the name of the file?
@majick777

**Comment by majick777** [comment]
@SasiaDagnoli I'm not referring to a file here. In the Radio Station plugin settings turn off the automatic display of the tabbed page... Then edit the Page on which you are displaying the Schedule and paste in the shortcode content.
