### ISSUE TITLE
[Show Pages] Possible to remove Show Pages and Permanent Links?

### ISSUE THREAD

**Issue by SasiaDagnoli** [netmix/radio-station#341]
I was wondering if it's possible to change/customize the permanent link? Or remove it - so there is no single show view?

**Comment by kairandles** [comment]
Hey, I had this open on #303 @majick777 put the code needed to add to the functions.php file on your website to change the slug so for example /shows/ to /live-shows/ etc

Additionally if you wanted no single show pages you could simply remove the titles from being linked to the show page or you can use a variable redirect such as yourdomain.com/shows/* to redirect to your or another page? 

Hopefully this helps you out and please feel free to jump in @tonyzeoli if I have missed any options for this?

**Comment by majick777** [comment]
@SasiaDagnoli 

You could use the filter `radio_station_post_type_show` to modify the Shows post type and make it not public. You'd probably want to turn off the rewrite and archive for it also... eg.

```
add_filter( 'radio_station_post_type_show', 'custom_shows_post_type' );
function custom_shows_post_type( $post_type ) {
    $post_type['public'] = false;
    $post_type['rewrite'] = false;
    $post_type['has_archive'] = false;
    return $post_type;
}
```

You'd then need to resave your permalinks from WP Admin -> Settings -> Permalinks
And you'd probably want to make sure `show_links="0"` is added to your shortcode attributes and "Link to Shows" is unselected in widgets, to prevent unexpected behaviour. Still, you may experience some unexpected behaviour doing this anyway, as `get_permalink ( $show_id );` will return false. But that may (or again, may not be) fine.

**Comment by majick777** [comment]
@SasiaDagnoli Sorry I missed the first part of your question, if you want to change the permalink base you would change the `rewrite` value via the filter mentioned instead. eg. 

```
add_filter( 'radio_station_post_type_show', 'custom_shows_post_type' );
function custom_shows_post_type( $post_type ) {
    $post_type['rewrite']['slug'] = 'programs';
    return $post_type;
}
```
