### ISSUE TITLE
Updates + Switched Theme / Widget Partially Working 

### ISSUE THREAD

**Issue by CarolineRuttermin** [netmix/radio-station#348]
Hi, 
I'm hoping to correct an issue from the Radio Station plugin on my Wordpress site. The "Current Spins" is not functioning, although "now playing" and "upcoming shows" are working fine. 

We just finished a website overhaul, including a new theme (currently using on Miniva) and several Wordpress and plugin updates on the site. 

I'm not sure how to correct this! 
Thanks!
CR

**Comment by tonyzeoli** [comment]
Can you share the link to your site please? And, to one of the playlists you're trying to generate. This is the first we're hearing of an issue with playlisting, so we'll look into it. But our lead dev is traveling for the weekend, so it may not be until Monday EST that he investigates the issue.

**Comment by CarolineRuttermin** [comment]
yep! 
ValleyFreeRadio.org 
I'm not sure what you mean about the playlists. The "current spins" usually generates the song that is currently being aired. We also use Spinitron, if that helps?
CR

**Comment by tonyzeoli** [comment]
It looks to me like you're using Spinitron's scheduling system on this page: https://valleyfreeradio.org/schedule/

That is not the Radio Station plugin scheduling system, which you can see on our demo site here: https://radiostationdemo.com

We do not interface with Spinitron, so we cannot pull your current song and display it in a widget. It looks to me like you're using our widgets but not our scheduling system.

Our Playlist feature is currently manual and is not automated. You would have to enter the data manually into the Playlist feature and then set the widget in the sidebar for the currently playing song. It's not automated.

We are working on ways to automate the playlisting in our PRO version, which is coming out soon. One thing we hope to do is to take the song list from shoutcast or icecast and create playlists. Or, we hope to work with open source playout systems like Azuracast or LibreTime to send track information into our playlisting system automatically.

But for now, it's all a manual process.

Tony

**Comment by CarolineRuttermin** [comment]
Thank you for the feedback! I'm going to keep digging. It helps to
eliminate that possibility.

Thanks again,
CR

Reiki for personal and spiritual growth

Oncology Reiki
Reiki classes, Nursing CNEs
Energy Matters Radio

www.ReikiNorthampton.com
508.612.9809

**Comment by tonyzeoli** [comment]
No problem.

I would contact Spinitron or whatever player you're using that is inserted on the listen page. In our forthcoming PRO version, we are going to have a persistent footer player that the user can see immediately. That way, you won't have to direct someone to a Listen page. The few steps for the user to listen, the better.
