### ISSUE TITLE
[Role Permissions] Show hosts can view all shows but cannot edit their own

### ISSUE THREAD

**Issue by neosonic2** [netmix/radio-station#353]
**Describe the bug**
After adding all of the current shows on our station, we are now in the process of adding user accounts for our DJs and show producers so they can sign in and customize the page for their specific show. While testing this functionality, I created a fake DJ account, assigned it the role of "DJ" (I can't remember if this is what the original name of the show host role was or if I just renamed that role to "DJ" using the role editor plugin I have installed) and added it to the list of "show hosts" for one of the shows on the site.

According to the [published documentation on user roles provided by the plugin](https://netmix.com/radio-station/docs/Roles/), anyone given the role of show host should only be able to view and edit the show or shows for which they are marked as a host, but after logging into WordPress with my fake DJ account and clicking on Shows in the admin sidebar, I see every show on the site, even those of which I am not the host, but I am also not able to edit the show of which I am the host. In fact there are no edit links anywhere on the shows list page.

**To Reproduce**
1. Sign into WordPress and create a new user with the show host role.
2. Create a new show and assign the newly-created user as a host of the show. Then create one or more other shows that do not have the user as hosts.
3. Sign out of WordPress (or open an incognito/private browser window) and then sign in as the user that was just created.
4. Click Shows in the administration sidebar.
5. 5. Notice the complete list of shows is displayed, rather than only displaying the show to which the user is assigned as the host, and notice there is no way to edit the show of which the user is the host.

**Expected behavior**
If I am signed into WordPress as the host of one or more shows, and I go to the show list, then as an optimal user experience (and an uncomplicated one for less technically-inclined users) I should only see the show or shows to which I have been assigned as the host, and should be able to click on the show or shows to edit them.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.5 Beta (build 20G5033c)
 - Browser: Safari 14.1.2

**Additional context**
We are running WordPress version 5.7.2 and Radio Station version 2.3.3.8 on a CentOS 7 server powered by Nginx 1.19.0 and PHP-FPM 7.4.20.

**Comment by majick777** [comment]
@neosonic2 Apologies, this one seems to have slipped through the cracks entirely. You are correct on the intended behaviour and last time this was tested all was working as expected. I will makes sure to test this again from scratch as you outline to see if I can reproduce the problem.

**Comment by neosonic2** [comment]
Good morning, I just wanted to check in for any updates on this issue? One of our DJs is trying to edit a show I assigned them to as the host but they are unable to do so; they can only view all shows in the admin but cannot edit any of them, even though they have the show host role (and the edit_shows capability granted to them). If I grant them the edit_other_shows capability, then t hey can edit every show on the site, including their own; but with only the edit_shows capability, they can’t edit any shows, even their own.

Has a solution to this issue been made available? We are now running version 2.4.0.3 of this plugin.

**Comment by tonyzeoli** [comment]
@neosonic2 I personally got stuck myself on this issue just yesterday and I've set a ticket in our PRO repo for this there, as well. 

Tony's in Australia so it's his overnight now, whereas I'm on Eastern time. I'll get with him to ask him about this later tonight around 9 pm Eastern and see if there's progress on this issue.

**Comment by neosonic2** [comment]
Thanks for your prompt response about this. I look forward to hearing what he says and please do let me know if you need any other details from me regarding this issue.

**Comment by tonyzeoli** [comment]
I think we should be good now that I've had the issue myself and am equally as frustrated as you, LOL. I've also found an issue on the reverse where the admin user can't edit Episodes, I believe. So, there's some work to be done there. I was trying to produce a demonstration video and ran into it, so I'm pretty well covered in that regard, but will let you know when we issue a fix.

**Comment by majick777** [comment]
@neosonic2 Sorry for the delay on this. The Pro launch has meant less time for solving issues, even one as important as this.
Having got back into it, for a few days ago, I have been working to understand and test WordPress's meta-capabilities better, so I can fix multiple potential issues like this for both free and Pro (known and unknown), rather than just keep trying to fix them one by one without seeing the big picture. 

I think I have my head around the capabilities now and will add the fixes to both versions shortly. I just need to do further work to test them on all the different post types and taxonomies in Pro, but it's a much simpler case in Free, so I've pushed this fix to the develop branch for testing and inclusion in the next release.
https://radiostation.pro/docs/faq/#how-do-i-install-the-latest-development-version-for-testing
