### ISSUE TITLE
[Overrides] Development upgrade reverts overrides to 1st Jan 1970

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#354]
Reported by @astevens93 in #342
"when I upgraded to v2.3.3.9 from v2.3.3.8 it also broke all of my schedule overrides and defaulted the year to 1st Jan 1970."

**Comment by majick777** [comment]
I have yet to be able to reproducer this. I tried to reproduce this by installing 2.3.3.8, creating an Override and then updating to 2.3.3.9 development version.) 

@astevens93 Perhaps you can retest by doing the same with the latest development version (there have been some changes but I'd not be certain if they'd affect/solve this issue)? I'd much prefer we had a good resolution to this one before release, it'd be good if users existing override times are not reset with the improvement of adding multiple override times!

**Comment by astevens93** [comment]
Hi @majick777 to confirm I have downloaded the latest development version and retested using the same steps, this is all fine and working as it should be now. Thank you.  I will close with comment.
