### ISSUE TITLE
[Visitor Showtimes] Empty brackets display when time conversion feature is disabled.

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#360]
Reported here: https://wordpress.org/support/topic/issue-after-latest-update-5/

When the visitor showtime conversion and display is disabled in the Plugin Settings, the surrounding brackets for user showtimes are still displayed regardless, and thus show empty brackets, which is an unsightly out-of-place addition on the page.

**Comment by tonyzeoli** [comment]
Is this something we need to fix as ASAP to wait until 3.4.0?

**Comment by majick777** [comment]
@tonyzeoli I can include the fix in the next release easily, but I don't think its urgent, as it's only going to affect users who turn the feature off,  and it's on by default. And also can be resolved for those users by a single line of CSS.

**Comment by majick777** [comment]
@tonyzeoli On second look, as I went to fix this, it turns out this was not a bug at all. The CSS is there already to not display the user time (including brackets) initially until the javascript kicks in and does the showtime conversion. However, the specific user site reporting had Assets Cleanup on it which cached the old stylesheet - which did not have the new style.
