### ISSUE TITLE
[ WordPress.org FAQ ] Add FAQ entry about dynamic refresh widgets

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#362]
**Is your developer task related to a problem or a requirement? Please describe.**

Under the FAQ entry for what widgets are available, we should add a FAQ entry about whether FREE widgets are dynamic. We've got a user request for auto refresh widgets to our contact form, so we should have an answer to this in the FAQ we can point to.

**Describe the solution you'd like**

Do widgets refresh dynamically?

No, widgets in the fREE version of Radio Station will not dynamically refresh. The page must be refreshed to view any changes. Dynamic refreshing has been added to our PRO version widgets, which are no available. Go to https://radiostation.pro to learn more about dynamically refreshing widgets and to purchase teh PRO version.

**Describe alternatives you've considered**

N/A

**Additional context**

none

**Comment by majick777** [comment]
Okay, I added a FAQ question and answer for this.
