### ISSUE TITLE
[Tabbed Schedule] Upon load, tab panel reverts to start of week not current day.

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#363]
Report: https://wordpress.org/support/topic/current-show-not-updating/
Example URL: https://hotrodradio.nl/hotrodradio-programma/

The current day shows tab panel is displayed to begin with, BUT upon full pageload the javascript is somehow reverting it to showing the start of the week panel instead.

**Comment by majick777** [comment]
Another example: https://www.madcitysportszone.com/on-air/
Reported in: https://wordpress.org/support/topic/tabbed-view-not-tabbing/

**Comment by alvaro-barros** [comment]
@majick777 hope your doing well... any ideas when you may have a fix?

**Comment by majick777** [comment]
@alvaro-barros Bit of madness working on the Pro launch, so this fix was delayed...
Turns out was just an initialization variable out of place causing the tabs to revert to default (first tab.)
Have just added it to the develop branch for the next version, you can install it this way:
https://netmix.com/radio-station/docs/FAQ/#how-do-i-install-the-latest-development-version-for-testing

**Comment by majick777** [comment]
As reported by user, this fix has gone missing in 2.4.0.2 ...
Really don't know how this happened, this change is in the referenced commit for 2.4.0.1

**Comment by majick777** [comment]
Have re-added the fix now to the develop branch for inclusion in next release. Closing again.
