### ISSUE TITLE
[Radio Clock Widget] Improve Layout Display lines and spacing

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#365]
**Describe the bug**

The layout of the widget is a bit messy when in one column. You've got the country zone out to the right and not underneath. And, the time zone switcher drop downs are misaligned when selecting the first and the second appears.

**To Reproduce**
1. Go to 'the widgets page on Radio Station Demo
2. Check the Racio Clock widget
3. See the misaligned content
4. Click on the timezone swicher
5. See the misaligned drop downs

**Expected behavior**

We just need a bit better UI work here to make it a little clearner.

**Screenshots**

<img width="346" alt="Screen Shot 2021-07-15 at 5 56 03 PM" src="https://user-images.githubusercontent.com/4053819/125863448-2f68e1ae-1c96-4bf3-9e26-a63cfb8fcb8e.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Fixed the line breaks (in Free), and the Timezone Switcher spacing (in Pro)
