### ISSUE TITLE
2.4.0.1 Deployment Files Do Not Contain New Version, Stable Release, Tested version numbers

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#366]
**Describe the bug**

Accepted the changes to my local repo. Copied files over and deployed via SVN. Version number on WordPress did not change. Investigated and noticed that nothing had been updated in the Read Me file, the radiostation.php file and the md file.

**To Reproduce**
1. Go to readme.md, readme.txt, radiostation.php
2. Open in Editor
3. View version numbers have not changed

**Expected behavior**

Expected new version numbers to be present.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Now, my desktop version is out of sync, as well.

**Comment by majick777** [comment]
The updated readme seems to have gone missing in this release, we can skip to 2.4.0.2 with new fixes anyway.
