### ISSUE TITLE
[ Mailchimp ] Update Welcome Email to general mailing list

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#368]
**Is your developer task related to a problem or a requirement? Please describe.**

The general email that goes out as a welcome message has not been updated in some time. Add additional messaging about how to get started with Radio Station, mention Radio Station PRO is available, reference support channels, and just a general welcome message. Also mention how to get your station listed in the directory.

**Describe the solution you'd like**

Update text per above mentioned copy.

**Describe alternatives you've considered**

**Additional context**

**Comment by tonyzeoli** [comment]
This is updated and completed.

**Comment by majick777** [comment]
@tonyzeoli Can we add the email copy to one of the marketing documents for future review?
