### ISSUE TITLE
[Settings Page] Save current tab on settings save not working

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#372]
**Describe the bug**

When I click the "SAVE" button under the Settings panel for any page, the system returns the user back to General, even if they were saving any other tab.

**To Reproduce**
1. Go to Settings > Pages
2. Change a Page setting
3. Click Save
4. View that General becomes the default panel again

**Expected behavior**

If click on Save under any tab, the system should not default back to General. It should stay on the tab that was last saved.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Intended functionality as described. Fixed plugin panel to include settings tab saving. Included in develop branch for 2.4.0.3 release.
