### ISSUE TITLE
[Tabbed Schedule] Moving forward and back in the weeks

### ISSUE THREAD

**Issue by kairandles** [netmix/radio-station#374]
**Describe the bug**
Not sure if this is actually a bug but here goes lol. There is a button on the demos that allows you to move over to the next (and previous week's schedule. I don't have this anywhere on my schedule

**Expected behaviour**
It Shows up.

**Screenshots**
![image](https://user-images.githubusercontent.com/77554122/130320463-0c69bd84-5caa-4b4c-a39d-b7dd6dcebd5f.png)
![image](https://user-images.githubusercontent.com/77554122/130320472-8429d289-6ca2-4699-9eca-a13ad7942219.png)

**Comment by majick777** [comment]
@kairandles Currently this feature is included in the Pro version (which is installed on the Demo site, hence you see it there) - as it was added in conjunction with the Calendar view. We will need to discuss further whether this will or won't be included in the Free version in the future.

**Comment by kairandles** [comment]
Ah, I see. No worries. From what I assumed this is still part of the 'Tabbed View' so would be included in the free version but not things like the calendar view! 
Could I be kept in the loop about this if possible?!
