### ISSUE TITLE
[ Master Calendar ] Legacy Div View causing fatal error

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#377]
**Describe the bug**

The legacy Div view has a fatal error.

**To Reproduce**
1. Go demo.radiostation.pro
2. Click on Master Schedule > Legacy Div view
3. View fatal error

**Expected behavior**

Website page loads correctly.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Error was a conflict with Pro schedule editor module, with the number of arguments in the show time filter mismatching. Fixed in develop version of both Free and Pro and pushed to Demo site.
