### ISSUE TITLE
[ Master Calendar ] Legacy Table View causes fatal error

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#378]
**Describe the bug**

When click on the tab, [Legacy} Table view, page load causes fatal error.

**To Reproduce**
1. Go [Legacy] Table view tab on Master Schedule drop down
2. Click on tab
3. Page load causes fatal error

**Expected behavior**

Page loads and displays view without fatal error.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Error was a conflict with Pro schedule editor module, with the number of arguments in the show time filter mismatching. Fixed in develop version of both Free and Pro and pushed to Demo site.
