### ISSUE TITLE
[ Google AdSense ] Center home page banner

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#379]
**Describe the bug**

I tried to center the home page banner, but it's not taking the inline style setting. I also tried playing with it in the make container, but couldn't get it right.

**To Reproduce**
1. Go to netmix.com home page
2. View the banner below the header
3. View it's shifted right

**Expected behavior**

Should be centered.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

The banner code is in a weidgetized HTML container under the Widets section. I've converted a Make column to a widget area.

**Comment by majick777** [comment]
I've centred the existing banner and put it under the Directory listings. There is no way we want it "above the fold" on Netmix, it really detracts from the overall look and feel, branding and user experience there. I also think we'd do much better to place these ads on internal pages than on the home page, as thsoe will get more organic traffic. 

That said, as the Directory grows with more listings (ie. when we get to actually doing the promo for it) - at that point we may want to think about auto-spacing a different size (smaller) ad throughout the listings instead, and offering premium users ad-free as part of their subscription. 

Here's some alternative ad sizes for reference: https://support.google.com/google-ads/answer/7031480
What size we choose will probably depending on how the directory view evolves, so it may be a bit premature to choose yet.
