### ISSUE TITLE
Logged in user sees correct show data, logged out user sees incorrect data

### ISSUE THREAD

**Issue by astevens93** [netmix/radio-station#382]
**Describe the bug**
It's been reported to me that logged in users to wp-admin see the correct schedule data, but logged out users see the wrong data.

Screenshots below - 
Logged out user - 25th Sept 11.23am - shows the show from Friday 25th Sept 8am - 11am on show widget and the Friday shows on schedule page (although blank)

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/67294458/134768140-55e94a12-bd3d-4875-b274-01c923b196b6.png">

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/67294458/134768153-94176e06-c908-4bdb-98c8-a79d7b60b4de.png">

Logged in user 25th Sept 11.23am - shows the correct show and schedule data

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/67294458/134768175-0b05e202-679b-4a18-be67-16755501fc2e.png">

**Expected behavior**
Both users see same data

**Additional context**
Radio Station pro v2.4.1.5
Radio station Version 2.4.0.3

**Comment by majick777** [comment]
@astevens93 Can I check you have AJAX loading of the widgets enabled in your Settings? 
Logged out users can be served cached pages (on any number of levels from server to platform) so the AJAX widget loading is used to "cachebust" this possibility. 
Logged in users typically bypass caching, which to me indicates this is likely to be the problem.

**Comment by astevens93** [comment]
@majick777 yes both AJAX loading and dynamic loading is enabled. It seems to be working as expected at the moment, but I want to check in on Saturday to see if I get the same, in case there is an issue with the Friday/Saturday (not sure why there would be, but just to check all eventuality)

**Comment by astevens93** [comment]
Hi both, I can't seem to replicate it this week and I've got the latest version installed - will see if it occurs again, no idea why it happened the first time.

We are using Icecast for the stream though I am just checking with the guy I need to regarding if Metadata is embedded in the stream or not as i can't seem to get it available in the player settings
