### ISSUE TITLE
PHP Error (filemtime(): stat failed) re-introduced with 2.2.4 

### ISSUE THREAD

**Issue by thisisshuffle** [netmix/radio-station#39]
The Php errors that existed initially and were resolved as part of 2.2.3 have re-appeared with the update to 2.2.4.

They again appear within both the on-air now and next widgets.

see example :
![radio-stat-capture224](https://user-images.githubusercontent.com/53148877/62478591-5da29880-b7a3-11e9-82bb-769b8bdd0f74.JPG)

**Comment by majick777** [comment]
I renamed the djonair.css to widgets.css for 2.2.4 so it will be used as a common file for all the existing widgets as the CSS was so minimal... but it looks like the new file has not made it up on to WordPress SVN from the Github release:
https://raw.githubusercontent.com/netmix/radio-station/master/css/widgets.css
If you save that file in /wp-content/plugins/radio-station/css/widgets.css the file will be found as it is supposed to.

@tonyzeoli Can you fix this? Remember to delete all the files from your local SVN /trunk directory, paste in all the new ones and then "SVN Add" the /trunk directory to ensure both that any removed files disappear and any new ones are committed. Not a step to be missed, it's a bit of a tedious process I know, but got to follow all the steps each time.
