### ISSUE TITLE
[ Schedule ] Displays Oct 31 two days in a row

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#391]
**Describe the bug**

A user in the free support forum states that Oct 31 displays on two consecutive days. I've confirmed at this URL https://www.uckfieldfm.co.uk/on-air/schedule/

**To Reproduce**
1. Go to https://www.uckfieldfm.co.uk/on-air/schedule/
2. Navigate to Oct 31
3. See Sunday and Monday are both the 31st.

**Expected behavior**

Monday should be November 1st.

**Screenshots**

![image](https://user-images.githubusercontent.com/4053819/138986623-010cb674-b676-4479-ab23-1a91e49e2a38.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
@mj187 @kairandles @astevens93 Great, closing this out. Included in 2.4.0.4 release which will be out shortly.
