### ISSUE TITLE
[Short codes] Show descriptions dissapear in show-archives shortcode

### ISSUE THREAD

**Issue by indierodo** [netmix/radio-station#393]
**Describe the bug**
When using the show archives shortcode, the description of shows does not appear

**To Reproduce**
1. Use the show-archives shortcode.

**Expected behavior**
The description of shows appear

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13654429/143505198-1c877d47-e472-433a-a5ff-e8d01b76d870.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 92

**Additional context**
I used the WP-Sweep plugin.

**Comment by tonyzeoli** [comment]
@indierodo Thanks for reporting and issuing the pull request. We'll get to it shortly to merge the fix into the develop version for testing and then future deployment in the next version.

**Comment by tonyzeoli** [comment]
@majick777 If we can get on this asap and pick up the pull request by @indierodo, I would appreciate it. Thanks, T.

**Comment by majick777** [comment]
Default changed from 0 to 'list' in shortcode. Added to develop branch for 2.4.0.6 release.
