### ISSUE TITLE
[PHP Error] Undefined variable $debugshifts

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#395]
**Describe the bug**

Warning: Undefined variable $debugshifts in /homepages/26/d152688268/htdocs/radiochristmas2021/wp-content/plugins/radio-station/includes/support-functions.php on line 1471

**To Reproduce**

View error on schedule page: [](https://radiochristmas.co.uk/radio/schedule/)
View error on override page(s): [](https://radiochristmas.co.uk/override/non-stop-xmas/) (multiple errors)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Added to develop branch for 2.4.0.6 release
