### ISSUE TITLE
Add Netmix MailChimp Email Signup to Help Page

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#40]
**Is your feature request related to a problem? Please describe.**
We need email newsletter signup registration with MailChimp on the Help Page. Since there is no General Settings Dashboard yet, we don't have a place to put an email newsletter signup tool. Probably good to add it to the top of the HELP page.
Don't think it's necessary to add as a notification at this time.

**Describe the solution you'd like**

On top of the HELP page, add:

"Subscribe to our newsletter to get features and updates announcements by email."

**Describe alternatives you've considered**

N/A

**Additional context**

Here's the form code:

<link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://netmix.us8.list-manage.com/subscribe/post?u=c53a6feec82d81974edd00a95&amp;id=7130454f20" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">Subscribe</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c53a6feec82d81974edd00a95_7130454f20" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

**Comment by majick777** [comment]
Okay this one is done too.
