### ISSUE TITLE
[ Posts ] Related Shows meta box duplicated in the Quick Edit view

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#400]
**Describe the bug**

Related Shows meta box duplicated in the Quick Edit view 

**To Reproduce**
1. Go to any Post under Posts
2. Click on Quick Edit
3. View the duplicate meta boxes

**Expected behavior**

Only one meta box should display,.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
Added fix to develop branch for 2.4.0.6 release.
