### ISSUE TITLE
Schedule override displays Show Time in 12-hour as 24-hour for PM times only

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#41]
**Describe the bug**

When Schedule Override is enabled on a Show, if set to 12-hour time:

1. Displays correct 12-hour time for AM hours
2. Displays incorrect 24-hour time for PM hours

See the user reported error here: https://wordpress.org/support/topic/title-position-and-override-time-format/#post-11820813

**To Reproduce**
1. Add Schedule Override on for Show
2. View Show / DJ On Air or Upcoming Show DJ On Air widgets
3. Check Schedule Override is set to 24-hours but displays incorrectly as 24-hours for only PM hours.

**Expected behavior**

All Schedule Overrides should display either 12-hour or 24-hour, depending on the setting.

**Screenshots**

Not available..

**Comment by majick777** [comment]
Have added a fix for this to convert the 24 schedule override time back to 12 hour for display in this widget if the show hour is more than 12. Added to next release.
