### ISSUE TITLE
Freemius SDK being appended to all files on update 2.4.0.6

### ISSUE THREAD

**Issue by xpurichan** [netmix/radio-station#413]
**Describe the bug**
Freemius SDK is being appended to unnecessary files since the plugin's 2.4.0.6 update. This is causing a multitude of issues including breaking Jetpack's connection.

This issue was discovered due to a broken Jetpack issue.

**To Reproduce**
1. Install and connect [[Jetpack](https://jetpack.com/)] to your WordPress website
2. Visit `https://DOMAIN.COM/xmlrpc.php?for=jetpack` and you should receive the following successful response: `XML-RPC server accepts POST requests only.`
   * You can also verify the connection is working in the Jetpack Debugger: https://jptools.wordpress.com/debug/
4. Install and enable `radio-station` version 2.4.0.6
   * The Jetpack connection will now be broken, which can be confirmed in the Debug tool: https://jptools.wordpress.com/debug/
6. Revisit `https://DOMAIN.COM/xmlrpc.php?for=jetpack` and you'll see the Freemius SDK content loading:
![Screen Shot 2022-03-07 at 3 35 30 PM](https://user-images.githubusercontent.com/33190975/157113726-07b385d5-0381-4e10-88be-ac92c19e9647.jpg)

**Comment by kairandles** [comment]
Hey! Thanks for reporting as well. I have the same issue and it's also affecting *ALL* API endpoints on WordPress. I reached out to the amazing @majick777 this morning. I assume he will reply here also about progress on this.
For note I've rolled back to a backup taken around 30 mins before the update happend so am unaffected currently.

**Comment by katiebethbrown** [comment]
Looks like it's these two echo statements:

- https://github.com/netmix/radio-station/blob/019018336f68d8a621ac20aad8712bd79226c01d/loader.php#L1356

- https://github.com/netmix/radio-station/blob/6d090aac1c81a4c7cbfbc50552ebc633a1d9b8d8/loader.php#L1468

If I comment them out the HTML is no longer appended to every page and Jetpack connectivity returns.

**Comment by tonyzeoli** [comment]
@xpurichan @katiebethbrown @kairandles 

Thanks for reporting these issues. I'm forwarding this ticket to Freemius folks and waiting for @majick777 to get back online. Some folks are experiencing issues, but I am not experiencing these issues on our demo site. I'm not sure why some people are and some people aren't. We'll get on this asap and issue a fix as fast as we can. We're getting user feedback in the support forums, as well, on this issue.

**Comment by kairandles** [comment]
Hey @tonyzeoli, just so you know these issues are occuring on your demo site. Please see your broadcast API endpoint. 
https://demo.radiostation.pro/wp-json/radio/broadcast

The <span> html code is the code that shouldn't be at the top!

**Comment by tonyzeoli** [comment]
Okay, thanks. I hadn't looked at that myself.

**Comment by tonyzeoli** [comment]
@xpurichan @katiebethbrown @kairandles 

Did any of you clear caches? Vova from Freemius said this: if you released the patched version less than 24 hr ago, then it’s most likely cached data.

That may be true or it may be unrelated, but just asking the question.

**Comment by kairandles** [comment]
Hey, both incognito & guest window tabs were used during our immediate bug testing when checking the endpoints. We also had all of our 50 odd screens in the building all displaying nothing because of that error (and they all use individual 'browsers' and fully flush and clear cache each time a new page is loaded)

**Comment by majick777** [comment]
It's my bad, it's a debug output that hasn't been commented out again. Fixing it now...

**Comment by tonyzeoli** [comment]
Okay, I've shared this ticket with Vova, so I'm awaiting a response from
him.

**Comment by majick777** [comment]
Thanks all for the quick reporting! This issue has been fixed and pushed to bugfix release 2.4.0.7 here on Github for download, and will be pushed to the WordPress repository shortly.

**Comment by tonyzeoli** [comment]
@majick777 @xpurichan @katiebethbrown @kairandles 2.4.0.7 is now available for download from [](https://wordpress.org/plugins/radio-station)

**Comment by kairandles** [comment]
Thanks @tonyzeoli & @majick777 for your prompt response to this!

**Comment by tonyzeoli** [comment]
@majick777 @xpurichan @katiebethbrown @kairandles 

All, you may notice an upgrade notification in FREE 2.4.0.7 to PRO 2.4.2.7. The way we've set up the plugin with Freemius distribution is not normally how Freemius does it, so Tony Hayes had to create a filter to resolve Freemius to think FREE is PRO, so please DO NOT click on the upgrade link until we release a patch in 2.4.0.8 coming soon.

**Comment by majick777** [comment]
Just to clear that up, IF you have Pro installed, you may see a link to update free version 2.4.0.6 or 2.4.0.7 to 2.4.1.7...
I have been working on fixing this in Pro 2.4.1.8 (not Free 2.4.0.8) which will bre released once we solve this reliably.
This also means the easiest way to update to 2.4.0.7 is to disable Pro temporarily, update Free then re-enable Pro.

**Comment by majick777** [comment]
@tonyzeoli Yes that is usually the case. It is however complicated by the fact that the plugin update data is cached by WordPress as a transient. So it is still possible that it will show the incorrect information from the cache. I am adding some extra code to the activation/deactivation hooks in Pro to clear the cached update data. 

Hopefully what this will all mean once anyone updates to Pro 2.4.1.8, the correct update data/links for Free will be available and no longer be overridden by Pro. I have this working more reliably now, just need to do some more checking for any other related issues.
