### ISSUE TITLE
[Team] Producer Featured Image

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#414]
**Describe the bug**

The Host and Producer list under Team are being pulled from Featured Image.

**To Reproduce**
1. Go to a Show
2. Click on Team
3. View Producer Thumbnail
4. Should be same size as Host Thumbnail 

**Expected behavior**

Producer Thumbnail Featured Image should be the same size as Host Thumbnail Featured Image

**Screenshots**

<img width="983" alt="Screen Shot 2022-03-08 at 6 16 00 AM" src="https://user-images.githubusercontent.com/4053819/157229006-290fd18c-23fa-4c87-98d7-cbd301415303.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by majick777** [comment]
This was fixed a while back but forgot to close this out.
