### ISSUE TITLE
[Shows] Remove Add New Show from Dashboard Menu

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#426]
**Is your developer task related to a problem or a requirement? Please describe.**

The Dashboard List has Add New for only the Shows. We should make it consistent.

**Describe the solution you'd like**

Remove "Add New" from the Dashboard List.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by majick777** [comment]
@tonyzeoli Okay have done this one.
