### ISSUE TITLE
[ Player ] Background color picker should pop over content

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#427]
**Describe the bug**

The Background color picker for the player shifts the text instead of popping over the content.

**To Reproduce**
1. Go to Settings > Player
2. Click on the Background color picker
4. View tooltip text shift to the right

**Expected behavior**
Color picker should load over the content and text should not shift.

**Screenshots**

https://www.loom.com/share/1db1eb82147747929ce1b4155553b339

**Comment by majick777** [comment]
@tonyzeoli Okay, have added this suggested fix to the plugin settings panel.
