### ISSUE TITLE
Fatal Error Line 57 radiostation.php

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#43]
**Describe the bug**

Users are reporting a fatal error in 2.2.6. Here is the error message:

Warning: require(/www/webroot/test.cci/html/wp-content/plugins/radio-station/includes/post-types.php): failed to open stream: No such file or directory in /www/webroot/test.cci/html/wp-content/plugins/radio-station/radio-station.php on line 57

Fatal error: require(): Failed opening required ‘/www/webroot/test.cci/html/wp-content/plugins/radio-station/includes/post-types.php’ (include_path=’.:/usr/share/pear:/usr/share/php’) in /www/webroot/test.cci/html/wp-content/plugins/radio-station/radio-station.php on line 57

**Comment by miklsnews** [comment]
same issue here is there a way to return to the later version until this is fixed

**Comment by majick777** [comment]
Looks like the latest version was not committed to SVN properly. You can download and install the Github version while this is being fixed.

@tonyzeoli need to do the step by step instructions sent or filename changes will not be picked up by SVN as they are handled as delete of old files and add of new. so make sure to delete all of trunk contents and paste in all of new before SVN add. 
can always check result at:
https://plugins.svn.wordpress.org/radio-station/trunk
Can we get on top of this process asap so updates do not fail like this.

**Comment by tonyzeoli** [comment]
@majick777 I've deleted everything from trunk and copied in everything from my Git desktop folder and it won't take any new changes, because it says there's nothing to change. So, I'm still getting the download from the plugin page with the old widget files. Versions shows me that the widget files have been deleted, but the widget files still seem to be in the download folder and the class files didn't push.
<img width="1301" alt="Screen Shot 2019-08-23 at 7 40 52 PM" src="https://user-images.githubusercontent.com/4053819/63629087-0b080f80-c5de-11e9-94b7-6f9c0787915d.png">

**Comment by tonyzeoli** [comment]
It's all good. I figure it out. 👍
