### ISSUE TITLE
This Plugin Does NOT work

### ISSUE THREAD

**Issue by sunsethostco** [netmix/radio-station#437]
It wont save or publish. It does nothing but twirl and twirl and twirl and it it never saves or publishes

![eeeee](https://user-images.githubusercontent.com/93102511/213012153-575f6253-04f6-4607-a61e-72849d51f6d5.JPG)
![eeeeee](https://user-images.githubusercontent.com/93102511/213012155-af229d30-85fc-444b-89f8-3042659c6caf.JPG)
![dddd](https://user-images.githubusercontent.com/93102511/213012156-efa28483-6451-43fd-9b2d-7ddfa7b14177.JPG)

**Comment by sunsethostco** [comment]
Its actually a joke. I took out the content in the description and i get this error or message. And,  when I leave and click out. Nothing ever shows up in schedule. This thing is a piece of shit waste of time. lol. I am deleting it.

![22222](https://user-images.githubusercontent.com/93102511/213013350-30db3701-8a7e-4787-8ed4-3740e3b44934.JPG)
![eeeee](https://user-images.githubusercontent.com/93102511/213013352-04ac574f-1c15-4b31-94ce-5009a5cac04d.JPG)

**Comment by tonyzeoli** [comment]
No one else bu you have reported any save or publish errors. Maybe, just
maybe, it's something in your configuration that is the problem. If you
were actually patient and worked with us to help you, we could ascertain
the issue and figure it out. The plugin works fine on thousands of sites,
so you may want to check your own configuration by disabling other plugins
or figuring out if something on your host side with php. Calling our plugin
a "joke" doesn't elicit a positive reaction from us and will not get you
very far. Most people who report issues aren't impatient and don't use
language as you have here in this forum. I'm currently on a flight
returning from the funeral of someone I've known for 45 years and this
message with this impatient attitude is the last thing I wanted to see
today. This isn't rocket science. We can help you if you are kind,
considerate, and patient. If you can't chill out and wait for a reply, then
yes, find another solution. We can't help you.
