### ISSUE TITLE
Coming Up widget shows times in 24-hour format when set for 12-hour

### ISSUE THREAD

**Issue by montereyjeff** [netmix/radio-station#44]
**Describe the bug**
In the Coming Up widget, the scheduled time shows in 24-hour format when the widget is set to 12-hour. Now On Air widget works fine.

**Expected behavior**
Display times in selected format.

**Screenshots**
![image](https://user-images.githubusercontent.com/53131566/63644029-33524580-c694-11e9-86cf-ebf7692f275d.png)

![image](https://user-images.githubusercontent.com/53131566/63644040-7f9d8580-c694-11e9-906f-0c4ac3ebead6.png)

**Comment by tonyzeoli** [comment]
Thanks, @montereyjeff Sorry we didn't catch this. Will do so on the next go round. Moved this into @majick777 bugs to look at. He's got some things going on this weekend. He'll probably take a look early in the week.

**Comment by montereyjeff** [comment]
No worries. I’ve been distracted by other things lately (my station engineer passed away unexpectedly) so just getting back around to paying more attention to the website.

**Comment by majick777** [comment]
The conditional test for 12 hour format option was not being cast integer in the Upcoming widget like it is in the other widget. This has been fixed for next release.
