### ISSUE TITLE
Error on presenter age -  Non numeric value encountered

### ISSUE THREAD

**Issue by KerryB1** [netmix/radio-station#447]
**Describe the bug**
A number of presenter pages reporting the following text

 
![Radio Station error](https://user-images.githubusercontent.com/68817551/229313728-6e53a2c0-abac-4558-b5c0-74f1b815962c.JPG)

**Comment by majick777** [comment]
@KerryB1 Thanks for your patience we were working on getting the release out.
This is one we fixed in 2.5.0, but you can get 2.5.2 here on Github as it has a further bugfix.
Can you confirm that these issues are resolved for you after installing that?

**Comment by tonyzeoli** [comment]
Closing this issue. Open another issue if the problem perists.

**Comment by tonyzeoli** [comment]
Closed.

**Comment by tonyzeoli** [comment]
Close
