### ISSUE TITLE
Error Installing Plugin on Local WP Development Site

### ISSUE THREAD

**Issue by mnyon-grandkru** [netmix/radio-station#448]
**Describe the bug**

**To Reproduce**
1. Go to WordPress admin
2. Click on Install
3. Select "Radio Station Pro"

```
Fatal error: Uncaught Error: Undefined constant "SECURE_AUTH_KEY" in C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-content\plugins\radio-station\freemius\includes\class-freemius.php:4061 Stack trace: #0 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-content\plugins\radio-station\freemius\includes\class-freemius.php(3912): Freemius->get_anonymous_id(NULL) #1 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-content\plugins\radio-station\freemius\includes\class-freemius.php(3964): Freemius->ping() #2 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-content\plugins\radio-station\freemius\includes\class-freemius.php(4818): Freemius->has_api_connectivity() #3 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-content\plugins\radio-station\freemius\start.php(522): Freemius->dynamic_init(Array) #4 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-content\plugins\radio-station\loader.php(1478): fs_dynamic_init(Array) #5 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-includes\class-wp-hook.php(308): radio_station_loader->load_freemius('') #6 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-includes\class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array) #7 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #8 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-settings.php(486): do_action('plugins_loaded') #9 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-config.php(93): require_once('C:\\Users\\scori\\...') #10 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-load.php(50): require_once('C:\\Users\\scori\\...') #11 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-admin\admin.php(34): require_once('C:\\Users\\scori\\...') #12 C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-admin\index.php(10): require_once('C:\\Users\\scori\\...') #13 {main} thrown in C:\Users\scori\Local Sites\forever-true-school-radio\app\public\wp-content\plugins\radio-station\freemius\includes\class-freemius.php on line 4061
```
**Expected behavior**
Radio Station Plugin installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5750239/229906768-de20c3a2-1724-4db4-98a5-ce25da948522.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] FireFox Developer Edition

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tonyzeoli** [comment]
@mnyon-grandkru Does the plugin sucessfully complete installation? Also, are you running php 8 locally?

**Comment by tonyzeoli** [comment]
@mnyon-grandkru one more thing on this. this is tied to our Freemius partner who distributes RS PRO. Anything with Freemius appearing is that service, so we'll check with Freemius on this.

**Comment by mnyon-grandkru** [comment]
No @tonyzeoli , the plugin wasn't installed completely.

**Comment by mnyon-grandkru** [comment]
I'm not running PHP on my system. Local says that the versions of PHP on their distrubutions are 5.6, 7.3 and 7.4. I'm assuming as I've installed this this week that I'm using the latest, but will double check

**Comment by tonyzeoli** [comment]
You might want to try php 8. 7.4 is pretty old by now.

**Comment by mnyon-grandkru** [comment]
Check the phpinfo on the other communication channel. It has php 8.19 listed

**Comment by mnyon-grandkru** [comment]
I've removed the plugin locally. Will try updating it from zip to see if that makes a difference.

**Comment by mnyon-grandkru** [comment]
![image](https://user-images.githubusercontent.com/5750239/229943186-0ee0e996-62d1-489d-9b56-f00437ff4327.png)

**Comment by tonyzeoli** [comment]
@mnyon-grandkru Okay, let's see what Tony says about this and I'll ping Freemius support.

**Comment by mnyon-grandkru** [comment]
I've removed the plugin in the meantime and have none installed. Are there plugins you'd normally have accompany radio station, @tonyzeoli ? Maybe that would help.

**Comment by tonyzeoli** [comment]
No, Radio Station (free) has a package from Freemius added to it in order
to upgrade to PRO. In that code, Freemius also helps us track installations
of the free plugin, so that we can ascertain who is using free and would be
eligible to upgrade to PRO. It also adds the entire Freemius account
management system to Free with an upgrade call to action, so it's a pretty
important step in the plugin to get users from Free to PRO. I'm sending
them a support request today about this issue and referencing the Github
ticket. I'll report back when I know more.

We've never actually seen this in the wild - it's the first report of this
issue, so we'll walk through it to resolution.

**Comment by tonyzeoli** [comment]
@mnyon-grandkru Freemius responded that you are missing your SALT keys in your WordPress wp-config.php file, which are necessary for secure authorization. Add those and should be resolved. This is more WordPress config issues than it has to do with RS or Freemius. If you're missing those keys, then Freemius is going to throw that error. They are adding something in the new version of the SDK to notify about this issue, but we haven't yet released the latest version with that update.
