### ISSUE TITLE
How to change the text of the program header

### ISSUE THREAD

**Issue by rubendc11** [netmix/radio-station#450]
Hi, 

I would like to know how to change the text of the header of the programs (About the Programa).

Thanks.

**Comment by majick777** [comment]
You can use the filter `radio_station_show_description_label` as found in `/templates/single-show-content.php` eg. 

```
add_filter( 'radio_station_show_description_label', 'my_custom_show_label', 10, 2 );
function my_custom_show_label( $label, $post_id ) {
    $label = 'New Label';
    return $label;
}
```
