### ISSUE TITLE
Help with a few problems with WP and Radio Station

### ISSUE THREAD

**Issue by thorssig** [netmix/radio-station#455]
Hi,
I'm new to WP and am starting to try to incorporate Radio Station to a website that already has a whooping 53 Plugins installed.

I'm having problems making the Floating Streamer Widget thinner, and possibly with custom buttons, but it only seems to allow me to reduce it to around 90 pixels. There seems to be something in the div block with class="rp-type-single" stopping it from reducing any further.
![bla](https://github.com/netmix/radio-station/assets/133007747/4e213aef-d11a-43e2-961c-0442468ebb7d)

When I try to mess with css setting belonging to the Radio Station plugin by going into "Appearence, Customise" I get the following error.
![WordPress Error - Appearance,Cuztomize](https://github.com/netmix/radio-station/assets/133007747/44c44bf7-a65f-4dad-ad8f-89e0e3b851c6)

A similar things happens when I try to go into "Live editor" at the top bar. 
![WordPress Error - Live Editor](https://github.com/netmix/radio-station/assets/133007747/711424a6-5003-4fdc-8775-c2d358b97141)

As I say I'm rather green when it comes to WP and Radio Station. I have tried to update all Plugins and don't know what else to do.
I am using Win 10 Pro with Google Chrome 112.

Regards,
Thorsteinn Sigurdsson (thorssig@utvarpsaga.is)

**Comment by majick777** [comment]
Hi @thorssig Thanks for reporting this.
I've tracked down and fixed both these bugs now and released hotfix versions for them: Free 2.5.2 and Pro 2.6.1
Free 2.5.2 is available on Github already and will be on the WP repo shortly, and Pro 2.6.1 is available via plugin updates or via the Freemius dashboard.
Let us know if you have any further issues.

As for the height of the player widget, `rs-type-single` doesn't have a height set on it. If you want a smaller height you could set it explicitly on the subdivs `rp-station-info`, `rp-interface` and `rp-show-info`. eg:
`.radio-container .rp-station-info, .radio-container .rp-interface, .radio-container .rp-show-info {height: 64px;}`

**Comment by thorssig** [comment]
Sorry, but I'm only able to update my Plugin to Version 2.6.0 Pro. How do I update to 2.6.1?
I have WP 6.2.

**Comment by majick777** [comment]
@thorssig 2.6.1 was deployed and should be available via the Update link on the plugin page. 
Are you saying it is not showing the Update link or that when you click it it doesn't update to 2.6.1?
You can also download it by logging in to your Freemius account: https://users.freemius.com/login

**Comment by thorssig** [comment]
Yes, it does not show in "Dashboard, Updates". I've tried updating all that's available but it still does not show there.
In "Plugins, Istalled" the free shows 2.5.2 and Pro shows 2.6.0 there are no option on updating and "Enable auto-update" does now show. I assume it's on auto-update.

**Comment by thorssig** [comment]
... sorry, I finally managed to find the download on freemius and managed to update to 2.6.1. :/

**Comment by majick777** [comment]
@thorssig Okay great did that resolve your original issue?

**Comment by thorssig** [comment]
YES! :)

**Comment by majick777** [comment]
@thorssig Groovy. I'll close this one out then, open a new issue if there is something else.
