### ISSUE TITLE
Fatal Plugin Error

### ISSUE THREAD

**Issue by charitablehumans** [netmix/radio-station#457]
**Describe the bug**
Error Details
=============
An error of type E_ERROR was caused in line 419 of the file /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-content/plugins/radio-station-pro/includes/rsp-player.php. Error message: Uncaught Error: Using $this when not in object context in /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-content/plugins/radio-station-pro/includes/rsp-player.php:419
Stack trace:
#0 /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-includes/class-wp-hook.php(308): radio_station_pro_player_widget_fields()
#1 /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#2 /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-content/plugins/radio-station/widgets/class-radio-player-widget.php(247): apply_filters()
#3 /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-includes/class-wp-widget.php(535): Radio_Player_Widget->form()
#4 /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-admin/includes/widgets.php(274): WP_Widget->form_callback()
#5 /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-includes/class-wp-customize-widgets.php(1148): wp_widget_control()
#6 /home/991195.cloudwaysapps.com/bwfkhrpwmt/public_html/wp-includes/

**To Reproduce**
1. Go to 'Customizer.'

**Expected behavior**
WordPress Theme Customizer Settings

**Screenshots**

**Additional context**

**Comment by majick777** [comment]
Hi @charitablehumansThanks for reporting this.
I've tracked down and fixed both this bug now as well as one with free, and released hotfix versions for them: Free 2.5.2 and Pro 2.6.1
Free 2.5.2 is available on Github already and will be on the WP repo shortly, and Pro 2.6.1 is available via plugin updates or via the Freemius dashboard.
Let us know if you have any further issues.
