### ISSUE TITLE
Display Schedule Overrides in Master Schedule

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#46]
Seems like an obvious oversight, but I don't see in the code that this is being done and will need to test this further.

**Comment by majick777** [comment]
Further recommendation coming from this, to make it easier using overrides, the user could be given the option to pick which existing Show(s) / Shift(s) to override rather than just setting an arbitrary time.

**Comment by tonyzeoli** [comment]
I have to look at this further and report back.


[image: photo]
Tony Zeoli
Founder, Digital Strategy Works LLC
O  (828) 412-0990  <(828) 412-0990> M  (917) 705-4700  <(917)
705-4700> E  az@digitalstrategyworks.com
<az@digitalstrategyworks.com>
W  https://digitalstrategyworks.com
Whatsapp 9177054700
Skype tonyzeoli
<http://www.facebook.com/digitalstrategyworks>
<http://www.twitter.com/dswks>
<http://www.linkedin.com/company/digital-strategy-works>
<http://plus.google.com/digitalstrategyworks>
<http://slideshare.com/tonyzeoli> <http://about.me/tonyzeoli>
<http://angel.co/tonyzeoli>
<https://calendly.com/tonyzeoli> Schedule a 30-minute Meeting
<https://calendly.com/tonyzeoli>
<https://digitalstrategyworks.com/clearly-better-days-cbd-oil-ecommerce-site-enhancements/2019/10/07/2841/>
Latest
post: Clearly Better Days CBD Oil Ecommerce Site Enhancements
<https://digitalstrategyworks.com/clearly-better-days-cbd-oil-ecommerce-site-enhancements/2019/10/07/2841/>


<https://gsuite.google.com/landing/partners/referral/trial.html?utm_source=sign-up&utm_medium=referralbutton1&utm_campaign=apps-referral-program&utm_content=https://goo.gl/BG4yH8>
<https://facebook.com/digitalstrategyworks>   <http://dswks>
<https://linkedin.com/in/+tonyzeoli>
<https://www.youtube.com/+digitalstrategyworks>

**Comment by tonyzeoli** [comment]
@majick777 Can you speak to whether you've looked into this. I believe WPVMFM.org is trying to use Show Overrides and it's not working correctly. I'll test this myself tonight, but just wanted to see if you came up with anything here.

**Comment by majick777** [comment]
@tonyzeoli Yes looking into it now.

**Comment by majick777** [comment]
Okay that was not an Override problem but still need to resolve this one ASAP.

**Comment by majick777** [comment]
So this led me to basically rewrite the entire Schedule calculation data model to be more robust, so that it can be used throughout the plugin not just in the Master Schedule view. Which is good because it needed to be done for other reasons, this was just a good starting point. 

The new Schedule calculation, gets all show shifts, orders them by dates, checks for shift conflicts (which are then diplayed via an Admin Notice) and finally applies the Overrides. 

This data is then used in a revamped Master Schedule shortcode View ("table") which uses the same table classes, and will take over from the current one ("default") in the next version (2.3.0) but the old one will still be available for backwards compatibility (thought it doesn't honour overrides.)

Further to this, the other views (list/div/tabs) will need to be modified to use the new data schedule model also.

**Comment by majick777** [comment]
Updated the List and Tabs Schedule Views to use the new Schedule calculations. 
The Div view remains unchanged so far as it uses a "rollover" calculation like the Legacy table view. Might leave that one for another time as don't want to break it but don't want to spend too much time on it either.

**Comment by tonyzeoli** [comment]
okay, sounds good....sounds like that was a big deal.

**Comment by majick777** [comment]
The ones I did were pretty easy, it's just the logic in the Div and Legacy Table views is based on the old data structure with a rollover calculation for div/row spans to the next hour. While neither honour the schedule overrides, the table one still works fine, and now have had a quick look at the Div one and it is not looking pretty, so maybe will get back to updating it anyway as anything would be an improvement on how it looks now.

**Comment by majick777** [comment]
Decided to not overhaul the Legacy table and Div views for 2.3.0, so users can transition to the new Views in their own time. They have received some minor updates to match with the other changes, but still use the old schedule calculation which does not honour overrides.

**Comment by tonyzeoli** [comment]
That sounds like a smart decision. We do have a lot of legacy users - probably 50%. But, it's better to push those legacy users and force them to upgrade to the new views. We'll make sure to note this in the update blog post, I'm sure.

**Comment by majick777** [comment]
The default View has changed to the new table view since it uses the new schedule calculations and thu fixes a lot. The legacy table view is still available, but only if specified with `view="legacy"`... will probably similarly redo the Div view in future and split into legacy Div and new Div.
