### ISSUE TITLE
[Automatic Pages] Add an Episode Archive automatic page option

### ISSUE THREAD

**Issue by EastOne57** [netmix/radio-station#466]
I would like to have a shortcode to display list of eg. the latest $N episodes by any show?
Currently only one show can be shown.

Also for show posts?

Show Posts Archive Shortcode
[show-posts-archive] (or [show-post-archive]

Or a widget wher one can set options such as show title; excerpt, date etc.
Much like the ususal 'recent posts' WP widget.
MTA!
East1

**Comment by majick777** [comment]
@EastOne57 Have you tried the `[episodes-archive]` shortcode for this? You can use the _perpage_ attribute to limit to _N_ number of episodes. 
https://radiostation.pro/docs/shortcodes/#pro-episodes-archive-shortcode

I just checked and seems like we haven't set up the automatic page option for this archive just yet. So I'm going to repurpose that ticket for doing that.

**Comment by tonyzeoli** [comment]
@majick777 Have we created the Episode Archive page yet?

**Comment by majick777** [comment]
@tonyzeoli 
Okay as this was a fairly quick one, I've added it into the Pro beta... 
and updated the demo site to include it. :-) 
(I'll remove the milestone here though as it's for Pro not Free.)

**Comment by majick777** [comment]
The shortcode already existed as `[episode-archive]` all this new option does is run that shortcode automatically as content for the selected page.

**Comment by tonyzeoli** [comment]
Right l, got it. Thanks!
