### ISSUE TITLE
Tu sitio no incluye compatibilidad con el bloque «radio-station/schedule». Puedes dejar intacto este bloque o quitarlo del todo

### ISSUE THREAD

**Issue by lucreciafer** [netmix/radio-station#467]
**Describe the bug**
I am using the last version or Wordpress and the plugin is ok in the actualization but when I want use in Gütenber, the block who contein it say: Tu sitio no incluye compatibilidad con el bloque «radio-station/schedule». Puedes dejar intacto este bloque o quitarlo del todo. intext:"Plugin: Radio Station by netmix® - Manage and play your Show Schedule in WordPress!"

**Screenshots**
![image](https://github.com/netmix/radio-station/assets/65544927/2740c081-b0f0-49da-8130-9befcf799382)
**Desktop (please complete the following information):**
 - Windows and UBUNTU
 - Browser  chrome

**Comment by majick777** [comment]
@lucreciafer Could you open your Developer Console and click on Console and let us know if there are any javascript errors there. It will help us to determine whether there is a conflict with another plugin.

**Comment by tonyzeoli** [comment]
@majick777 Adding you to this ticket, as well as the ticket owner and myself.

**Comment by tonyzeoli** [comment]
I'm going to mark this resolved as Radio Station PRO now supports Gutenberg blocks and there has been no response from the OP.

**Comment by tonyzeoli** [comment]
Closing this ticket.

**Comment by majick777** [comment]
@lucreciafer This kind of error happens in Gutenberg where the block has been added to the page, but either the plugin has been deactivated, or some javascript error is preventing the block's javascript from successfully running, leading Gutenberg to believe the block is "no longer supported." 
As mentioned, if you see any errors in the Console tab of your browser developer console and can copy them here, it would let us know what the issue might be, and we can re-open the ticket to look at it.
