### ISSUE TITLE
[Data API] next_show is false when calling the API endpoint "broadcast"

### ISSUE THREAD

**Issue by dacarter** [netmix/radio-station#470]
**Describe the bug**
When calling the REST API for the ```/broadcast``` endpoint, the "next_show" property is sometimes false regardless of the schedule. In some instances this appears to be populated, seemingly at random, but the majority of the time it is set to "false".

**To Reproduce**
Add a show with a schedule of 22:00 - 00:00 on any given day (i.e. Sunday)
Add another shift to that show of 00:00 - 06:00 on the following day (i.e. Monday)
Set system time to 23:00 and call the /broadcast api

**Expected behavior**
The "current_show" property to be populated with the information of the current show
The "next_show" property to be populated with the information of the next show rather than false.

**Data & Screenshots**
```{
   "broadcast":{
      "current_show":{
         "ID":6985,
         "day":"Sunday",
         "date":"2023-09-10",
         "start":"22:00",
         "end":"00:00",
         "encore":false,
         "split":false,
         "override":false,
         "id":"XOhRemXX",
         "show":{
            "id":6985,
            "name":"Sunday Chill",
            "slug":"sunday-chill",
            "url":"<REDACTED>",
            "latest":"",
            "website":"",
            "hosts":[
               {
                  "name":"<REDACTED>",
                  "url":"<REDACTED>"
               }
            ],
            "producers":[
               
            ],
            "genres":[
               
            ],
            "languages":[
               
            ],
            "avatar_url":"",
            "avatar_id":"",
            "image_url":"",
            "image_id":"",
            "route":"<REDACTED>",
            "feed":"<REDACTED>"
         }
      },
      "next_show":false,
      "current_playlist":false
   },
   "timezone":"Europe\/London",
   "stream_url":"",
   "stream_format":"aac",
   "fallback_url":"",
   "fallback_format":"ogg",
   "station_url":"",
   "schedule_url":"",
   "language":"en_GB",
   "timestamp":"1694385314",
   "date_time":"2023-09-10 23:35:14",
   "updated":"1694384323",
   "success":true,
   "endpoints":{
      "station":"<REDACTED>",
      "broadcast":"<REDACTED>",
      "schedule":"<REDACTED>",
      "shows":"<REDACTED>",
      "genres":"<REDACTED>",
      "languages":"<REDACTED>"
   }
}
```

![image](https://github.com/netmix/radio-station/assets/2293093/b400c671-4b95-456a-97ee-ba3cc24c456b)

**Comment by majick777** [comment]
@dacarter Thanks for reporting, apologies for the delay.
I've added a fix for this for the next upcoming release, in the meantime you can verify the fix by installing and testing the development version.
https://radiostation.pro/docs/FAQ/#development-versions
