### ISSUE TITLE
[Demo] Player and teleporter not working correctly after WordPress update

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#475]
**Describe the bug**

Both the player and the transition plugin are not working correctly on the demo site both before and after the latest WordPress update. I am seeing this weird issue with other sites where WordPress announces an update and then things break before the update is taken. I don't understand why that happens. But before I updated WordPress for the demo site the player was not functioning correctly. After the update it disappeared altogether.

**To Reproduce**

Go the demo site and try to load the home page.

See the transition script fade the home page to black but still show the text of the page and the player is missing.

**Expected behavior**

Normal behavior.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tonyzeoli** [comment]
@majick777 I tried to uninstall the beta 2.6.4.2 (which is not yet in Freemius) to 2.6.4.1 and the player and teleporter are still breaking.

**Comment by majick777** [comment]
@tonyzeoli Confirmed it was a bug in the development version of free that I was testing on the demo site that was preventing the player stylesheet from loading. Fixed there now.
