### ISSUE TITLE
Commit Failed php error in class-dj-upcoming-widget.php

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#48]
**Describe the bug**
Commit failed (details follow):
Commit blocked by pre-commit hook (exit code 1) with output:

***********************************
PHP error in: radio-station/trunk/includes/class-dj-upcoming-widget.php:

Parse error: syntax error, unexpected '<<' (T_SL) in radio-station/trunk/includes/class-dj-upcoming-widget.php on line 152
Errors parsing radio-station/trunk/includes/class-dj-upcoming-widget.php
***********************************

**Comment by majick777** [comment]
Somehow the merge from my forked repository conflicted and added all the file diffs into the files. So I re-pulled, fixed the diff sections in those files and re-pushed. Hopefully should be all good now.
