### ISSUE TITLE
[ Read Me } Add Patchstack Vulnerability Statement

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#487]
Add the PatchStack Vulnerability text to the ReadMe:

To publish your mVDP, update the readme.txt (example) disclaimer displayed in the FAQ section on the plugin’s description on wordpress.org. or security.md disclaimer on GitHub (example). You may copy-paste from the e-mail or make sure to swap out example data. Remember to push the update to your plugin so the new security.md or readme.txt file will go into effect. Once done, e-mail us at triage@patchstack.com for the VDP to be made public. == Frequently Asked Questions == = Where do I report security bugs found in this plugin? = Please report security bugs found in the source code of the Radio Station plugin through the [Patchstack Vulnerability Disclosure  Program](YOUR_MVDP_URL_HERE). The Patchstack team will assist you with verification, CVE assignment, and notify the developers of this plugin. # Security Policy ## Reporting Security Bugs Please report security bugs found in the Radio Station plugin's source code through the [Patchstack Vulnerability Disclosure Program](YOUR_MVDP_URL_HERE). The Patchstack team will assist you with verification, CVE assignment, and notify the developers of this plugin.

**Comment by tonyzeoli** [comment]
We don't have a URL yet from the vulnerability program...not sure how to get one. Working on it.

**Comment by tonyzeoli** [comment]
@majick777 I have added the PatchStack FAQ to the read.me and the read.txt files, but did not add a mention to the next version notes. Please make sure to add that we included the FAQ statement in the notes on the next release.

**Comment by majick777** [comment]
Okay, added the mention to the readme.txt
