### ISSUE TITLE
Shows page

### ISSUE THREAD

**Issue by brucy34** [netmix/radio-station#488]
What if i don't want to display the show page but show a different page instead when user click on the show

**Comment by tonyzeoli** [comment]
@brucy34 Our Github page is for bug reports. In the future, please use our Free support forum for your support requests if they are not specifically bugs. Thanks.

We don't have a way to do that as it defeats the purpose of the plugin altogether. If we gave everyone the right to decide where to direct a link to display a Show page of their choosing, then why even build the plugin? A Show is connected to its corresponding page and that's how we have it set. You could hire a developer and build a custom function to do this or you could use a Redirection plugin that redirected a Show page to another page that you set. The second option would be the best, fastest, and cheapest option. I'll close this ticket as resolved.
