### ISSUE TITLE
upcoming-shows don’t show up 

### ISSUE THREAD

**Issue by mOreNha90** [netmix/radio-station#492]
**Describe the bug**
upcoming-shows don’t show up 

**To Reproduce**
www.radioasisonline.com

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tonyzeoli** [comment]
@mOreNha90 I reviewed your website but do not see where you added the Upcoming Shows widget. You can see the Upcoming Shows widget on our demo page here: https://demo.radiostation.pro/widgets/. The widget is standard with the free version and dynamic with Radio Station PRO. Please let us know which version of Radio Station PRO you are using and your WordPress version, as well as your version of PHP.

**Comment by tonyzeoli** [comment]
@mOreNha90 this is posted here: https://wordpress.org/support/topic/upcoming-shows-dont-show-up/. I'm closing this Git issue in favor of handling it in the WordPress Support forum.
