### ISSUE TITLE
Can't edit pages in wp-admin and Jetpack won't load

### ISSUE THREAD

**Issue by kboglp** [netmix/radio-station#493]
Help! I can no longer edit pages in wp-admin mode, and something happened to my Jetpack...I deleted and re-installed to no avail. I am a web newbie.

**Comment by majick777** [comment]
@kboglp We need more to be able to help ypu here. Try deactivating Radio Station from your plugins page to check that it is causing the issue. If so, open your Developer console in your browser (Google how) then click the Console tab and report any errors from that.

**Comment by kboglp** [comment]
Thanks majick...I think I figured out why Jetpack is messed up and I can get in a backdoor to edit my front page. I deactivated Radio Station and no changes. I have an issue with my widgets not working so it is probably a WordPress issue...thanks again!

**Comment by tonyzeoli** [comment]
Closing this issue.
