### ISSUE TITLE
Schedule is calling Google API with non-secure address "HTTP" rather than "HTTPS"

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#5]
/includes/master_schedule.php is calling Google API with a non-secure address “HTTP” rather than “HTTPS”. And due to the fact that this is within a function (line 12), plugins such as “Really Simple SSL” will not touch it causing it to remain insecure. It’s an easy enough thing to fix on my part, but when an update occurs, it’s right back to giving users a browser warning when using a secure URL on the site.

**Comment by majick777** [comment]
This one was fixed in 2.2.0 by checking protocol with `is_ssl()`, so closing.
