### ISSUE TITLE
Parse Error on Line 609

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#50]
**Describe the bug**

Commit reporting a new error:

Parse error: syntax error, unexpected '===' (T_IS_IDENTICAL), expecting end of file in radio-station/tags/2.2.7/radio-station.php on line 609
Errors parsing radio-station/tags/2.2.7/radio-station.php
***********************************

**Comment by majick777** [comment]
Ack, another leftover from the merge fail, thought I got them all. Pushed another fix.
