### ISSUE TITLE
Ability to disable link to from Calendar to Show Page

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#52]
**Is your feature request related to a problem? Please describe.**

After talking to my station that I volunteer for, I realized that some stations have programming that does not require a Show page. They may want to add the Show, add it's time to air, but not host any content on the Show page.

**Describe the solution you'd like**
We should find a way to allow the admin to disable the link on the master schedule or in widgets to a Show page, but it will be up to the admin to no index the page using some SEO plugin. If there's a way to hide the Show page for that entry, then we could even hide it from view too.

**Describe alternatives you've considered**
I haven't considered any alternatives at this time, other than to instruct the admin to no index a page where a link to the show is not added to the master schedule..

**Additional context**
I don't have any other context or screenshots for this feature. I would assume there is some meta box that instructs the user to disable the show link from the master schedule.

**Comment by majick777** [comment]
We can give them the option to not create a page for a Show on the Show edit screen metabox? How would we word this to be clear and not confusing?

I think this would be better than any de-indexing after the fact, but we might want to just redirect existing hits on those URLs to the Show Archive page just in case. 

So then, if they tick the box for not wanting a Show page, then we can check for that in the Master Schedule and other Widgets/Shortcodes and not link to it from those either.

**Comment by tonyzeoli** [comment]
@majick777 Well, they may want to reintroduce the show page at a later date, so creating the page and de-indexing it is probably the way we want to go. I would just give a warning in the meta box to tell the user that they should use their preferred SEO plugin to de-index the page. Given that I work with All In One SEO, I would recommend to download All In One SEO Pack and then "no-index" the page with that plugin. We can leave it up to the user to decide if they wanto to do that.

In terms of the checkbox term, let's say it's this: "Disable Show Page Link from Master Schedule"

We can add a Tooltip that says, "Checking this box disables the link to the Show Page from the Master Calendar and all Widgets. You would select this option if you do not want the user to visit a Show Page on the site. Uncheck the box to enable the link to the Show Page."

We can also add a second checkbox to add URL to an external show page.

"Check this box to add a URL to an external webpage for this show."

**Comment by tonyzeoli** [comment]
I think we talked about just leaving this as it is for now, because if the we disable the Show page, the user is still going to try to use the blog or the playlists and then they want have anywhere to display them AND if we hide the Show page based on whether it has content or not, the user isn't going to know that and is going to be confused. So, we'll shelve this because no one is asking for i and it could introduce more issues than it's worth.

**Comment by majick777** [comment]
Agreed. Since this is "missing content" in a sense, it would be something for the user to add to the Show so there is some kind of information displayed. Perhaps we could add a column in the admin view for management purposes just to indicate if there is a show description content or not? That would be an easy enough this to do.

**Comment by tonyzeoli** [comment]
If the column is active in the Show list view, then adding any content in
that column would push the next entry in the list down the list. Maybe if
it were the first 50 characters with an ellipsis I would say, sure.

What I think is more important it adding some type of notification on the
Show page edit screen that the Body content is for Show Description. And,
to add content to your Show page, please use Posts and assign a Post to the
Show Page. That needs to be clearer, I think.
