### ISSUE TITLE
Ability to disable Show Page features in a settings panel

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#54]
**Is your feature request related to a problem? Please describe.**
There's been a request to be able to disable the following from a show page:

1. Playlists - If the user never has a playlist, we should let them disable playlists.
2. Hosted By - If the user never registeres a DJ as a host, we should let them disable Hosted By
3. Genre - If the user does not want to display a genre, we should let them disable Genre

**Describe the solution you'd like**
In a Settings panel, we should allow the user to toggle options.

**Describe alternatives you've considered**
The user could hide with CSS, but they should be able to turn off natively if needed.

**Additional context**
No other context at this time.

**Comment by majick777** [comment]
@tonyzeoli  I've been working on making the display of all these (and others) conditional in the new show content filter, so they won't display if there is no value assigned to them. Rather than add separate toggle settings for what displays on the single Show page, I've added filters so anything can be removed or changed as desired, but I don't think many people will want to bother - mostly if something is not wanted to be displayed the user just won't enter that field data. So I'll close this for now but if you think there is a setting that is really important in this way feel free to re-open.

**Comment by tonyzeoli** [comment]
Hmmm...I'm thinking this through. The admin may then add a show and not put content into the Show page. They may click Publish. When they go out to the calendar, the show won't be linked and they'll probably wonder why. Let's think about how we can tell them they must add Show content for the page to be linked from the Calendar (and the widgets too). How can we let them know to add content to make the Show page link active? They won't know this unless we tell them. Something like, "If you do not add content to this page, the link to the page from the Show calendar will not be active."

I'd much prefer a checkbox - "Disable link to Show Page from Calendar)"

But let's keep the discussion open and talk about the pros / cons of each method. What do you think?

**Comment by tonyzeoli** [comment]
I'm going to reopen for now until a final decision is made.

**Comment by tonyzeoli** [comment]
Actually, I'm sorry. After thinking about this, the Show DJ / Host would be able to add a Playlist and Posts too, and they wouldn't appear on a page. There are dependencies that I didn't think of before and it's probably just best to render the page and disregard my request completely. That's the first time I asked for something that I didn't think all the way through. They can no index the page if they want with an SEO plugin. And, if they don't add content, so be it. But to hide the Show means to hide the ability to add a Playlist to that show and the ability to publish Posts to that show. As I learn more about this plugin, it makes me think of all the possible options and I probably overshot my bounds here. So, let's remove any restrictions because of those dependencies that I did not consider. That's my mistake. I'll own that.
