### ISSUE TITLE
JetPack Related Posts splits Show Description from Show Schedule and Playlists

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#58]
**Describe the bug**
In my research on sites using Radio Station, I'm seeing that when someone installs the Related Posts plugin from JetPack, it sits between the Show description and the schedule and playlists feature. We need to figure out how to ensure this doesn't happen.

**To Reproduce**
Install JetPack and enabled Related Posts
View Show Page

**Expected behavior**
Related Posts should always be at the bottom of the Post, so that means we may have to rethink how Show Schedule and Show Playlists are featured.

**Screenshots**
![screenshot-kbog org-2019 09 17-08_35_11](https://user-images.githubusercontent.com/4053819/65042407-cb0b2280-d926-11e9-980b-4435c09fb44a.png)

**Desktop (please complete the following information):**
Any browser.

**Smartphone (please complete the following information):**
Any Smartphone

**Additional context**
We may need to rethink the plugin and move Schedule and Playlists into Widgets or Blocks and keep the Show Description standard.

**Comment by tonyzeoli** [comment]
Here is a link to the example site: https://kbog.org/show/chill-sweet-sleep/

I've seen this happen on other sites, as well.

**Comment by tonyzeoli** [comment]
@trystant and @majick777 ,  maybe you guys can communicate on this one and propose a solution. We can then all discuss?

**Comment by majick777** [comment]
JetPack Related Posts is hooking into `the_content` filter and adding the Related Posts at the end of the post content. A lot of plugins do this, as it's one of the only theme-agnostic ways of adding content to the page. The show template is calling `the_content()` and then adding the Schedule, Playlists and Blog Posts after that... 

If we want those to be better placed, we can remove them from the Show template and add them to `the_content` filter instead, so that they appear after the show content and still allow other plugins such as JetPack to add to the content further with a later priority.

**Comment by tonyzeoli** [comment]
@majick777 Yes, we want any plugin adding stuff at the end of the post content to have it be the last thing added as it's going to disrupt our plugin's content. So, we should definitely follow the path you're outlined and add them to `the_content`

This would also most likely fix the issue in Divi or any builder that pulls just the post body content and not the Genre, DJ, Playlists, etc...

I also think, with some care, we modify the template so that the Genre and DJ are placed under the Show Description in the post body and not out there to the right. This will change everyone's site, but from what I looked at through the publicWWW site, most sites don't do any custom styling or anything to the template. They just add the plugin and lt it fly.

So, that would open another issue and reference this issue.

What I'd love for you to do is get @trystant involved with you on this one, so he can get his hands dirty. As the lead dev, you can assign him to take a piece of this and walk him through the process of proper coding to make this change and then QA his changes. I'd like to start getting him and @jmarx involved. I spoke to Jeff and he's going to code review you and Mark's work to help out and just have a second set of eyes on this. He may jump in from time to time to code up as well. So, now we've got a team of three who can contribute and help you out, but I'll leave it up to you to define the tasks for them, review their work, and help them immerse themselves in the project.

Both Mark and Jeff are extremely qualified developers and along with yourself, you'll have a great team to lead. But, like you, they are all immersed in other paid work, so we'll just work through any timing issues and be patient as everyone gets free time to contribute. NO PRESSURE HERE, LOL.

**Comment by tonyzeoli** [comment]
@majick777 I'd like to actually attack this one first, since it's an issue *possibly* affecting anyone using a page builder. If you need to see how this reacts on WPVM's new website, let me know and I'll show you in Divi. But if you use the instructions to make a template file and apply it to Divi, then only the Show description displays and it leaves out the genre, DJ, playlists, etc... If somehow we can ensure that when working with Divi we can display everything into the Divi page, that would be great.

**Comment by majick777** [comment]
Have finished the new content filter to replace the split show template, but needs testing before including in next release. I think we should bump to 2.3.0 when we do this and put in the Upgrade Notice and do a blog post as you suggested. 

I think perhaps we could also detect if there is a child theme template exists and add a dismissable announcement linking to the blog post if it does, but not bother the user with it if there isn't one.

I'm also thinking we should do the same with the Playlist template, and remove the automatic activation of the archive templates, all for reasons of the plugin becoming theme-agnostic.

**Comment by tonyzeoli** [comment]
All sounds good. I'll follow your lead here.

**Comment by tonyzeoli** [comment]
@majick777 I just thought of something. We shouldn't even display related posts on the Show page, because the page is not a post. Related posts should only display on Posts and not Pages. Now that I think of it, we should just filter it out altogether, as there's no reason it should be on the Show page in the first place.

**Comment by tonyzeoli** [comment]
Shoot...I just checked WPVM's site and Related Posts pulls recommendations from the Shows CPT, so I guess we'll have to keep it because some stations may want to cross promote similar shows and that's a good way to do it.

**Comment by majick777** [comment]
Yes this is something that would be handled in JetPacks's Related Post (or other Related Post) settings, allowing the user to select which custom post types show the Related Posts, so we shouldn't be attempting to change the behavious of other plugins. 

The placement is being handled in #72 now so I will close this one.

**Comment by tonyzeoli** [comment]
Gracias, mi amigo!
