### ISSUE TITLE
Add Setting selector for Default Grid or List (Tab) view

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#62]
**Is your feature request related to a problem? Please describe.**
If the user is a novice and does not understand shortcode or does not review the FAQ to implement shortcode for the LIST view (Tabs), then add a selector on the *future* plugin Settings page to select GRID or LIST view. There should be icons next to the radio buttons that display what a grid or a list is to the user.

**Describe the solution you'd like**
In future Settings panel, add option to select Grid or List. Default should be Grid. Maybe we could detect if the user is using the List shortcode somehow and either warn them in the update that the Default grid view will be enabled and they have to switch back or think up some better way to ensure we don't break a site if we push this change. My reasoning is that I want to make it as easy for a radio station as possible to switch between grid or list without having to implement two different shortcodes. There should be one master shortcode and grid/list is an option and not a separate shortcode.

**Describe alternatives you've considered**
I haven't considered any alternative.

**Additional context**
When we implement the Grid/List switcher for the End User (reader), they are switching to the opposite of the Default selected by the admin.

**Comment by majick777** [comment]
Along with a selectable dropdown of which page to show the Master Schedule on automatically, I've adding this as the only other setting to the new plugin admin page settings for next release (2.3.0) so the user can select which view they want to automatically display on that page (Grid=Table/List/Divs/Tabbed)
