### ISSUE TITLE
Translations of months/weekdays do not display

### ISSUE THREAD

**Issue by MikeNGarrett** [netmix/radio-station#63]
**Describe the bug**
Anywhere that uses `radio_station_translate_weekday()` is calling `$wp_locale->get_weekday_abbrev()` with a number when a string is expected. This causes these translations to fail. 

**To Reproduce**
I noticed this at the top of the master schedule shortcode. 

**Expected behavior**
A row for the days of the week should displaying at the top of the master schedule.

WordPress 5.2.3. Plugin version 2.2.7

**Additional context**

Notice: Undefined offset: 0 in /wp-includes/class-wp-locale.php on line 287
Notice: Undefined offset: 1 in /wp-includes/class-wp-locale.php on line 287
Notice: Undefined offset: 2 in /wp-includes/class-wp-locale.php on line 287
Notice: Undefined offset: 3 in /wp-includes/class-wp-locale.php on line 287
Notice: Undefined offset: 4 in /wp-includes/class-wp-locale.php on line 287
Notice: Undefined offset: 5 in /wp-includes/class-wp-locale.php on line 287
Notice: Undefined offset: 6 in /wp-includes/class-wp-locale.php on line 287

**Comment by majick777** [comment]
@MikeNGarrett Thanks for picking this one up, merged your pull request into the 2.2.8 release.
