### ISSUE TITLE
Grant DJs Edit Rights in Settings

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#66]
**Is your feature request related to a problem? Please describe.**
DJs cannot edit shows, playlists, or show overrides.

**Describe the solution you'd like**
In Settings, the admin can grant a DJ edit rights to their Show. A DJ cannot add a show, but they can edit their show description.

What they can do:
- can Edit Show Description
- can Edit Featured Image
- can Add/Edit Playlist
- can edit Email Address
- can edit Website Link

- cannot schedule show override (admin only)
- cannot shedule show times (admin only)

**Describe alternatives you've considered**
The current alternative is the user must add the Members plugin by Justin Tadlock and then activate edit ability to allow editors to edit Shows.

**Additional context**
Now that I've investigated this further, Nikki Blight did ensure that the DJ could not edit a Show unless the Members plugin was added. Thie purpose of this is for the Admin only to create Show pages and edit those pages, so that the Show DJ cannot impact a Show page with additional content the Admin has not approved. By adding this setting to the Settings page, we want to grant the role of DJ the permission to edit Shows, but it should be granted by role than allow/disallow by user in the Settings.

So, the Admin user opens the Settings panel and sees a list of DJs. They can select one or many DJs and grant them Show Edit rights.

For DJs who do not have Edit rights on their assigned Shows, we should display in the Shows panel when they are logged, and only against their Show entry in the list of all Show entries, something like, "Only an Administrator can edit this show. Please contact your site administrator to request editorial rights for your user profile.

**Comment by majick777** [comment]
Ack misread all that at first. To clear this up, DJs do have Show edit capability (including scheduled shift times) but not Show publish or Override publish/edit capability...  I agree we could add a plugin admin option to allow DJs to publish Shows and/or publish/edit Overrides.

**Comment by tonyzeoli** [comment]
I had said in my post originating this issue:

- _cannot_ schedule show override (admin only)

- _cannot_ shedule show times (admin only)

And they shouldn't be able to publish shows either. I think leaving that to the admin is a wise choice.

**Comment by tonyzeoli** [comment]
I'm going to close this because DJs can already edit show pages natively. I thought this was tied to Members, but it's not. I don't think we need to address this any longer. A DJ can Edit their Show page fine with the way this is working now.

**Comment by majick777** [comment]
I don't see anything preventing a DJ adding or modifying Show shifts. If a DJ can edit a Show because they are assigned to it, they can edit anything including the shifts. If this is undesirable we should re-open this issue and discuss adding that as a separate capability and a default setting for it, but I'm not sure it's a big deal at this point, maybe we can add a permissions settings tab to the Pro version at a future time for things like this.
