### ISSUE TITLE
[Edit Shows] Add Duplicate Show Shift Button

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#70]
**Is your feature request related to a problem? Please describe.**
When adding Shifts, the Show Host or Admin must click on Add Shift 5 to 7 times and then set the same times to any Show when the Show repeats daily at the same time. This is tedious when trying to create your Master Schedule.

**Describe the solution you'd like**
The Show Host or Admin should be able to click "Add Shift" and set the first Shift entry. Once the first Shift entry is set, they should be able to click "Copy" or "Duplicate Entry" to right of the first entry or any entry thereafter, so that they can copy the entry and only need to change the day and not the hours.

**Describe alternatives you've considered**
See Additional Context below.

**Additional context**
In the future, in a pro version, it might be better, as LibreTime does it. I've posted a screenshot below.
<img width="329" alt="Screen Shot 2019-10-03 at 9 08 17 PM" src="https://user-images.githubusercontent.com/4053819/66216286-3547f500-e693-11e9-9abe-346528d4836e.png">

<img width="157" alt="Screen Shot 2019-10-03 at 9 08 39 PM" src="https://user-images.githubusercontent.com/4053819/66216296-3a0ca900-e693-11e9-96e0-e47bdf9f526a.png">

<img width="308" alt="Screen Shot 2019-10-03 at 9 08 46 PM" src="https://user-images.githubusercontent.com/4053819/66216304-3e38c680-e693-11e9-9b53-4d899d436d66.png">

**Comment by majick777** [comment]
Should be fairly easy to add the Duplicate button to a shift next to the Remove one. 
I created a separate issue for non-weekly repeating shifts as in the screenshots.

**Comment by majick777** [comment]
Have added this one in for 2.3.0, seems to be working fine.

**Comment by tonyzeoli** [comment]
When duplicating the Shift, the "Remove" button instead of the "X" displays.

**Comment by majick777** [comment]
True, I saw that and was gonna leave it because it helps distinguish it's a new shift... But we could add some other kind of indication for that? Anyway I have changed it now.

**Comment by tonyzeoli** [comment]
Oh, sorry, I didn't know that was the intent. I had just talked to you about the feature and it wasn't stated that this would be the functionality, so I didn't know that it was not a bug and that it was intended. It's fine either way. I just thought it was a bug, because the only information I had was that the X would replace the button.
