### ISSUE TITLE
Add Notification to Show Edit Screen that Post Body is for Show Description

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#74]
**Is your feature request related to a problem? Please describe.**
It seems that many users do not know that the Show Description and the Blog are distinctly separate and some Show Hosts are using the Description field to post hundreds of archives, when they are supposed to use the Post admin, then assign a Post to the Show and it will display under Blog Posts.

**Describe the solution you'd like**
Add some type of notification bar to the Show Edit screen that tells the User the Post Body is only for the Description and display a link to a blog post (I will create) that is a tutorial to use the Posts for Show Archive content.

Text: "This text field is for your Show(s) _description._ It is not recommended to edit the page and post your past show content or archives in this area, as it will affect the Show page layout your visitors see and possibly impact SEO, such that the archived content won't have its own page(s) and you won't be able to SEO and Social Meta rules. We recommend using your WordPress Posts function to add new posts and assign them to your Show(s) using the Show assignment meta box in the Posts Edit screen"

**Describe alternatives you've considered**
I thought about creating a CPT of _Show Blog_ and using that to run those Posts, because maybe the radio station doesn't want to use the main blog feed for Show posts. We could add a Setting to turn it on if the station wants a separate Posts per show or turn it off if they want to use Posts.

If they use Posts and the assignment, then they can't turn on the CPT if the Posts have entries, because we can't filter in two sets of Posts into that area and combine them in one. I think Posts and CPTs are separate and can't be combined if I'm not mistaken.

Likewise, if they use the CPT first, they can't go back and use the Blog.

They would also have to have custom taxonomy, as well. Categories and Tags that don't mix with the general Posts taxonomy.

**Additional context**

**Comment by tonyzeoli** [comment]
@majick777 I updated my description - so please check this page on Git and not rely on just the email that gets sent out.

**Comment by majick777** [comment]
Added for next release (2.3.0), slight modifications in text, can always be changed/added to later:

"The text field below is for your Show Description. It will display on the About tab of your Show page. It is not recommended to edit the page and post your past show content or archives in this area, as it will affect the Show page layout your visitors see. It may also possibly impact SEO, such that the archived content won't have its own page(s) and you won't be able to SEO and Social Meta rules. We recommend using your WordPress Posts function to add new posts and assign them to your Show(s) using the Show Assignment meta box in the Posts Edit screen. You can then assign them to a relevent Post Category for display on your site."
