### ISSUE TITLE
Add line-height to id="myplaylist-nowplaying"

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#75]
**Is your feature request related to a problem? Please describe.**
Line-height for Now Playing widget does not exist.

**Describe the solution you'd like**
Add 1.6em of line-height to id="myplaylist-nowplaying" to give proper spacing to now playing song/artist/title/label entry.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by majick777** [comment]
Added to next release (2.3.0)
