### ISSUE TITLE
[Docs] Review and Update Shortcodes and Attributes

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#76]
Some of the documentation (eg. readme FAQ) items regarding shortcodes may be outdated and are in need of review by matching up to the actual code to make sure they do what they say they do.

Also of note here is the addition of the the `[master-schedule list="tabs"]` shortcode option that displays the new Tabbed Schedule for the Master Schedule shortcode output.

**Comment by tonyzeoli** [comment]
@trystant Can you take a look at this when you get the chance?

**Comment by majick777** [comment]
Closing. These are all in the new documentation now.
https://netmix.com/docs/shortcodes/
