### ISSUE TITLE
[Docs] Update FAQs to ready for 2.3.0 release

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#82]
**Is your feature request related to a problem? Please describe.**

This ticket will update the FAQs for 2.3.0 to include:

- any change to shortcode functionality
- new admin panel
- new conflict checker
- new features
- screenshots

Will add/edit in comments after submitting this issue for tracking purposes.

**Describe the solution you'd like**

Updates to read.md

**Describe alternatives you've considered**

N/A

**Additional context**

Will add screenshots to this issue.

**Comment by majick777** [comment]
Related #85

Here's a rough list of the major features added in 2.3.0:
* Revamped Templates
* Improved Master Schedule
* Improved User Roles
* New Shortcodes
* Admin Options
* Show Producer Role
* Improved Show Images
* REST API Routes
* Shift Conflict Checking

And here is a more complete list fof readme.txt updates (so far!):
* Include: Plugin Loader (1.0.9) with plugin options and settings
* Include: Freemius SDK (2.3.0) and Freemius integration
* Feature: assign new Producer role to a Show for Show displays
* Feature: Schedule Show Shift Conflict checking 
* Feature: Show Shift saving completeness and conflict checking
* Feature: added REST/Feed endpoints (broadcast, schedule, shows, genres)
* Feature: options to set Page and default View for Master Schedule
* Feature: post type Archive Shortcodes and Show-related Shortcodes
* Feature: server and user time clock on Master Schedule table view
* Feature: added Show Header image to Shows for single Show display
* Improved: new Data Model and Schedule (with Override) Calculation
* Improved: new Show Content Template layout display method
* Improved: new Playlist Content Template layout display method
* Improved: Genre highlight selection on Master Schedule table view
* Improved: added Custom Field and Revision support to post types
* Improved: missing output sanitization in Shortcodes (shortcodes.php)
* Improved: added file hierarchy fallbacks for CSS, JS and Templates
* Roles: new Show Producer role (same capabilities as DJ / Host)
* Roles: new Show Editor role (edit permissions but not Admin)
* Roles: Changed DJ role Label to DJ / Host (for talk show usage)
* Admin: Added Plugin Settings Admin Page (via Plugin Loader)
* Admin: Added plugin Upgrade / Updated details admin notices
* Admin: Schedule conflict notice and Show conflicts in Shift column
* Admin: Show/Override content indicator columns to Admin Show list
* Admin: Show Description helper text metabox on Show edit screen
* Admin: Fix to restore Admin Bar New/Edit links for plugin post types
* Admin: Store installed version for future updates and announcements
* Disabled: automatic loading of old templates (non theme agnostic)

There is a lot we could talk about here, I think a blog post for the release could cover the major points, but that is still a heck of a lot of information and writing to do... What have I done, lol. :-O

**Comment by tonyzeoli** [comment]
@majick777 Very cool. We'll add this to the new Read.md pre-release when it's ready. Good work. What have you done? Basically some very cool stuff that is going to help a lot of people and moves Radio Station into the future!

**Comment by majick777** [comment]
Readmes have been updated with the latest changes/FAQs.
