### ISSUE TITLE
[Docs] Document REST Data Endpoints

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#84]
Add documentation for new REST API routes and Feed Data endpoints.

**Comment by VerumEmanio** [comment]
How have you been documenting these endpoints so far? I might be interested in lending a hand if you're looking for help.

**Comment by tonyzeoli** [comment]
@VerumEmanio Thanks for the offer of support/assistance. I wanted to acknowledge your offer yet leave it up to @majick777 to respond in detail.

**Comment by majick777** [comment]
@VerumEmanio Thanks for wanting to get involved on this.

So as it's only just been developed there is not really any documentation on this so far except for code comments in the `/includes/data-feeds.php` file (of develop branch).

`/wp-json/radio/station/` - List data of all the endpoint URLs.
`/wp-json/radio/broadcast/` - List data of stream, current and upcoming shows etc.
`/wp-json/radio/schedule/` - List data for the current full weekly Show Schedule.
`/wp-json/radio/shows/` - List data of all shows (optionally by specified show name slugs)
`/wp-json/radio/genres/` - List data of shows by Genre (optionally of specified Genre(s) )
`/wp-json/radio/languages/` - List data of shows by Language (optionally of specified Language(s) )

Some notes we need to include: 
- The initial base endpoint is discoverable (and how.)
- The endpoint basenames can be filtered (and how.)
- If REST is disabled, matching data / endpoints are available via Feeds instead (there is a plugin option to disabled either the REST endpoints or Feed endpoints.)

Apart from these what really needs to be documented is the array data structure for each of the endpoints, and these can be found from either reading the code or accessing the working endpoints on the demo site (`eg. https://radiostationdemo.com/wp-json/radio/schedule/`

**Comment by majick777** [comment]
These are now fully documented at: https://netmix.com/radio-station/docs/api/
