### ISSUE TITLE
[Docs] Documentation Section Display Strategy

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#85]
I have been thinking about an overall better strategy to handle the documentation. If we create a /docs/ folder in the repository and have .md files there for each major section of the plugin, they will be viewable in GitHub and we can link to the documentation index from the main readme.md... 

Then we can keep those as the updated docs and (automatically) pull them from the repo for display on the website, in a documentation section at say: https://netmix.com/radio-station/docs/ (or /documentation/ ?)

Something like this would be a decent section breakdown:
/docs/Index.md (Table of Contents)
/docs/Options.md (including Filters)
/docs/Pages.md (including Archives and Templates) 
/docs/Shortcodes.md (including Master Schedule)
/docs/Widgets.md (and Widget options)
/docs/Endpoints.md (REST and Feeds)
/docs/Roles.md (and related Capabilities)

...so each one would have it's own page eg. https://netmix.com/radio-station/docs/options/
and instead of having to keep syncing FAQ changes from the readme.txt to readme.md in future, and trying to have all the information there, we can come up with a more generalized FAQ that points to the website documentation locations (and from inside the plugin displays a markdown formatted documentation page included with the plugin.)

**Comment by tonyzeoli** [comment]
@majick777 This seems optimal. @trystant was working on an update to move to .md from .txt. Let's let him first complete the work on the the Pull Request he's issued. Then we can move to making this wholesale change.

**Comment by majick777** [comment]
Here's an updated list of proposed Documentation Sections:
Data Types | Shows, Overrides, Playlists, Genres, Languages
Pages | Automatic, Single and Archive Page Templates
Widgets | Current Show, Upcoming Shows, Playlist, Streaming Player
Shortcodes | Data List Archives and Master Schedule Views
Roles | Plugin Roles and related Capabilities
Endpoints | via the REST API and Feeds
Options | Plugin Option details and Value Filters
Roadmap | Feature Roadmap for both Free and Pro Features

**Comment by majick777** [comment]
These are the final documentation sections:

FAQ | Frequently Asked Questions
Options | Plugin Option Details and Value Filters
Display | Automatic Pages, Templates and Images
Manage | Admin Lists, Shift Editing, Conflict Checker
Roles | Plugin Roles and related Capabilities
Widgets | Current Show, Upcoming Shows, Current Playlist, Radio Clock, Streaming Player
Shortcodes | Data List Archives and Master Schedule Views
Data | Post Types, Taxonomies and Custom Filters
API | Data API via REST and Feed Endpoints
Roadmap | Feature Roadmap for Free and Pro Versions

These are now published at: https://netmix.com/radio-station/docs/
As such this issue can be closed. :-)

**Comment by tonyzeoli** [comment]
There are links within each section that are resulting in 404 page not found.

**Comment by majick777** [comment]
Good pickup. All the internal linking is via relative links for Github viewing, and yet we have a hierarchical docs page structure on Netmix.com... So I had to modify the markdown shortcode to account for this and all links should be fixed now.
