### ISSUE TITLE
Update Legacy Shortcodes and Widgets

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#86]
So far I have done my best to keep changes to legacy shortcodes and widgets to a minimal in 2.3.0 for backwards compatibility purposes. However, it would be nice to update these using the new data model support functions that are more comprehensively written.

There is also a code duplication between the current shortcodes and widget-shortcodes. This is not best practice as does not follow the DRY principle (don't repeat yourself.) It would be better to have the widgets call on the shortcodes, passing the user widget options as shortcode attributes, and relying on the shortcodes for output. This would remove the duplication.

**Comment by tonyzeoli** [comment]
@jmarx and @trystant Would you both be able to jump in here and work on this issue with shortcodes and widgets. @trystant would take the lead on making the changes and would consult with @jmarx for the best way to do that. You're both in New York, so maybe you could both meet one day to discuss? Mark would take on the development and Jeff would support with guidance and QA.

**Comment by tonyzeoli** [comment]
@jmarx @trystant just following up on my last message about Mark working on the shortcodes with Jeff as an advisor. Please let me know if you can take this one on. We need to have this looked at for 2.3.0 and that's coming very soon. So, if you can both get together and take a look, that would be helpful. Contact @majick777 if you have any questions and to get direction.

**Comment by majick777** [comment]
As the updates for this release are quite major and this issue would need to make use the new code, I am putting what I have so far as an interim development versions for testing / working / bugfixing on my fork at: https://github.com/majick777/radio-station/ (tagged as release "2.2.9")
It's time to do that anyway, but we wouldn't want anyone needing to double-handle given there is a lot that has been done that is useable here.

Since there is a lot of fresh code in this update, maybe @trystant and @jmarx you would like to familiarize yourself with it (especially the new support-functions.php and data-feeds.php) and download this copy and scan through it with some other sets of eyes over it - in a quick code review of sorts. It might turn up some silly bugs or simple fixes / enhancements that I've missed in the process. There are still a bunch of finicky things to do/test before it's releasable.

@tonyzeoli I have also put this version up on the Radio Station Demo site (and wpvm demo) so the shortcode displays can be checked (I've added a page for each shortcode.) Also check out the new Plugin Settings admin screen via the Admin area and see what you think. Unfortunately I will be out over the weekend as volunteering at an event, so I'll leave you to gather any notes together and we can discuss and work through any issues that come up start of next week.

I'd say just at this point reviewing this new code shoule come before updating these shortcodes / widgets (as they do work as they are, just a bit of a mess to be honest.) But some further notes on this issue for combining them:
Can ignore [show-list] legacy shortcode (replaced with rewritten [shows-archive])
Can ignore [get-playlists] legacy shortcode (replaced with rewritten [show-playlists-archive])
[dj-widget] ~= /includes/class-dj-widget.php
[dj-coming-up-widget] ~= /includes/class-dj-coming-up-widget.php
[now-playing] ~= /includes/class-now-playing-widget.php

A rough plan of attack for updating these:
- Matching up the widget options settings to shortcode attributes.
- Changing over to use new data functions in /includes/support-functions.php
(eg. radio_station_get_next_show / radio_station_get_next_shows etc., there is not one for playlists yet so we can leave the now-playing widget/shortcode until last.)
- Syncing the display markup between each widget/shortcode.
- The markup output will be handled by the shortcode and called from the display `widget` function of the widget class with the widget options converted to the proper shortcode attributes.

**Comment by tonyzeoli** [comment]
Okay, @majick777 - thank you for the detailed message here. I'll get in touch with @trystant and @jmarx Sunday EST to ask them if they can have a look in terms of a code review.

**Comment by majick777** [comment]
Update, I followed the procedure outlined above to convert the existing widgets to use shortcodes for display. Some styling still needs to be added.

**Comment by majick777** [comment]
After a few rounds of this, and updating the documention to match and finding and fixing a few more issues, I'm satisfied with how these are diplaying now, so I'm gonna finally close this one out.
