### ISSUE TITLE
Add Language Taxonomy

### ISSUE THREAD

**Issue by majick777** [netmix/radio-station#90]
For Radio Station's that have multilingual programming, this could be an optional feature that would allow for easier discovery of Shows in a particular language.

**Comment by tonyzeoli** [comment]
@majick777 how do the translations play into this?

**Comment by majick777** [comment]
I don't think they would need to, language taxonomy terms would simply be added as needed for a Show. They would work almost exactly the same as Genres do now really, just another indication for categorization.

For implementation, allow the user to pick a default language option for the Station that Shows would all be under until changed.

**Comment by tonyzeoli** [comment]
Okay, is this a PRO feature? Should possibly be PRO, no?

**Comment by majick777** [comment]
No because we want this information to be available via REST for pulling into directory listings on NetMix, so that language-specific programs are discoverable without the station with the listing needing to have the Pro version.

**Comment by tonyzeoli** [comment]
You're a genius. :)

Good stuff. Go with that.

**Comment by majick777** [comment]
Went out on a limb and added this one in for 2.3.0. Time to reign it in now, lol.
