### ISSUE TITLE
2.3.0 Code Review

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#92]
**Is your developer task related to a problem or a requirement? Please describe.**

N/A - this request is for a code review for 2.3.0

**Describe the solution you'd like**
Tyler B performs code review per instruction from @majick777 

**Describe alternatives you've considered**
N/A

**Additional context**
We'll add list of action items to this ticket.

**Comment by tonyzeoli** [comment]
@majick777 reach out to Tyler B at tylerb.media@gmail.com to submit your list for code review to him.

**Comment by tonyzeoli** [comment]
@majick777 Have you reached out to Tyler? Please update me on the progress of the code review.

**Comment by majick777** [comment]
@tonyzeoli yes I did, he said he'd have some time to look at it last week, I will check in how he is going with it maybe something else came up and didn't get to finish it yet.

**Comment by majick777** [comment]
@tonyzeoli So I have some issues back from Tyler (mostly relating to sanitization) which I am fixing up... He had less time than thought last week due to holiday, but will have a look at it again once I fix these up.

**Comment by tonyzeoli** [comment]
Awesome that he caught those. Glad to have a good eye helping out on this.
Working to get some beta testers too.

**Comment by majick777** [comment]
Didn't realize this ticket was still open, this was done a while ago now. Closing.
