### ISSUE TITLE
Add Patreon Support

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#95]
**Is your feature request related to a problem? Please describe.**
Add Patreon support.

**Describe the solution you'd like**
- Add field in Settings for Patreon ID
- If value is entered into field, display Patreon button linking to Patreon user page on Patreon.com
- Add button under Player in left column

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by majick777** [comment]
Feature added for 2.3.0 release.
