### ISSUE TITLE
[Master Schedule] Display Radio Time and Your Time on one line

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#96]
**Is your developer task related to a problem or a requirement? Please describe.**

The Display time currently displays to the right of Genres and Genres then breaks the line if too many genres.

**Describe the solution you'd like**
We should keep Genres at the top of the grid, but we can put the Radio Time and Your Time at the bottom of the grid, on one line. I don't think it's necessary to show it at the top of the grid at this time. That should be reserved for just genres only as the filter.

**Describe alternatives you've considered**

N/A

**Additional context**
<img width="665" alt="Screen Shot 2019-12-21 at 10 53 00 PM" src="https://user-images.githubusercontent.com/4053819/71316852-5bd12d00-2445-11ea-9fb2-e1bfe03d1046.png">

**Comment by majick777** [comment]
This can be done as part of #126. I'm really not sure if we should move it to below the schedule as it could get lost down there, but as where the timezone display is now and on one line would work fine.

**Comment by majick777** [comment]
I'm going to close this here as the one line issue itself is sorted.
