### ISSUE TITLE
Fix text for Show Description explanation

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station#97]
**Is your developer task related to a problem or a requirement? Please describe.**
The show description explanation line breaks make it read a bit weird.

**Describe the solution you'd like**
Remove line breaks and make one consistent paragraph

**Describe alternatives you've considered**

N/A
<img width="908" alt="Screen Shot 2019-12-22 at 11 23 29 AM" src="https://user-images.githubusercontent.com/4053819/71324531-c61db800-24ad-11ea-944a-16033ffe7ed3.png">

**Additional context**

**Comment by majick777** [comment]
You're right the single lines do seem excessive. One paragraph seems to be the other extreme though... I have made it two paragraphs hopefully that is a good balance?
